### PR TITLE
HIVE-25058: PTF: TimestampValueBoundaryScanner can be optimised during range computation pt2 - isDistanceGreater

### PR DESCRIPTION
**Pull request by abstractdog**
### What changes were proposed in this pull request?
Introduced faster TimestampWritableV2 handling into isDistanceGreater method.

### Why are the changes needed?
Performance improvement.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Unit test included, behavior is the same before/after the patch. Tested on cluster.

### CODE REVIEW

**Comment by abstractdog** [comment]
cc: @rbalamohan: we missed isDistanceGreater last time, please find flamegraph in jira
I'll include tests later

**Comment by abstractdog** [comment]
could please review this @rbalamohan? similar fix to HIVE-24746, unit test included

**Comment by abstractdog** [comment]
@rbalamohan , @pgaref : can I get a +1 on this one? the patch is working on customer's cluster right now

**Review by rbalamohan — APPROVED** [review]
+1. LGTM

**Pull request merged**
