### PR TITLE
HIVE-26645: Preparing for 4.0.0 development

### PR DESCRIPTION
**Pull request by deniskuzZ**

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
Isn't GA in the version name a bit too much? We can tell 4.0.0 is GA release, do we need to put that in the version name. I hardly saw any Apache project having GA in the release name.

Second, do we consider 4.0.0 as stable release, isn't a .0 is always an unstable release and 4.0.1 would be stable. (Coming from my Hadoop experience)

We need to create `4.0.0-alpha-2` branch as well before merging this?

**Comment by deniskuzZ** [comment]
@ayushtkn, @nrg4878  4.0.0-alpha-2 branch was already created, however, I was waiting for this PR to be merged first so we could cherry-pick everything that was merged to master after we branched and the new development version was created.

**Review by nrg4878 — APPROVED** [review]
Changes look good to me. +1

**Comment by nrg4878** [comment]
@ayushtkn Can you take a quick look as well before we merge it?

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
