### PR TITLE
HIVE-27151 : Revert "HIVE-21685: Wrong simplification in query with multiple IN cl…

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA : https://issues.apache.org/jira/browse/HIVE-27151

The multi_in_clause.q fails because Hive is not able to parse 
explain cbo
select * from very_simple_table_for_in_test where name IN('g','r') AND name IN('a','b')
If we want this to work, I am able to do it in my local. We have 2 options :
a. Either revert [HIVE-21685](https://issues.apache.org/jira/browse/HIVE-21685) since this scenario was not validated back then before adding this test.
b. This fix was present in https://issues.apache.org/jira/browse/HIVE-20718 but to cherry pick this we need to cherry pick https://issues.apache.org/jira/browse/HIVE-17040 since [HIVE-20718](https://issues.apache.org/jira/browse/HIVE-20718) has a lot of merge conflicts with  [HIVE-17040](https://issues.apache.org/jira/browse/HIVE-17040). But after cherry picking these we have other failures to fix.
 
I am reverting this ticket for now.

This reverts commit fdaa342534f9ccfac9f1a7b53ef367003366fce8.

### CODE REVIEW

**Comment by amanraj2520** [comment]
@vihangk1 Can you please review this

**Review by vihangk1 — APPROVED** [review]
LGTM

**Comment by vihangk1** [comment]
Retriggered tests to confirm if the `org.apache.hadoop.hive.metastore.client.TestRuntimeStats` test failure is not related. Rest of the failures are known failures.

**Comment by vihangk1** [comment]
I submitted http://ci.hive.apache.org/job/hive-flaky-check/620/console to confirm if the new failure is a flaky test. Lets wait to see if it is indeed flaky and then we can merge this PR.

**Comment by amanraj2520** [comment]
@vihangk1 Can you please merge this

**Comment by vihangk1** [comment]
That new test which fails doesn't seem to be flaky. Retriggered the tests.

**Pull request merged**
