### PR TITLE
HIVE-27825: Better error message for an empty quoted identifier

### PR DESCRIPTION
**Pull request by okumin**
### What changes were proposed in this pull request?

Show more hints such as a line number when a user hits the issue.
https://issues.apache.org/jira/browse/HIVE-27825

### Why are the changes needed?

The current message doesn't include any context about Hive's grammar. It is not helpful when a submitted SQL is complex.

### Does this PR introduce _any_ user-facing change?

The type of exception and an error message can change.

### Is the change a dependency upgrade?
No

### How was this patch tested?
Unit tests and manual tests on my local machine.

```
0: jdbc:hive2://hive-hiveserver2:10000/defaul> SELECT `` FROM ``;
Error: Error while compiling statement: FAILED: ParseException line 1:10 cannot recognize input near 'FROM' '<EOF>' '<EOF>' in select clause (state=42000,code=40000)
0: jdbc:hive2://hive-hiveserver2:10000/defaul> SELECT * FROM a.``;
Error: Error while compiling statement: FAILED: ParseException line 1:18 cannot recognize input near 'a' '.' '<EOF>' in table name (state=42000,code=40000)
```

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
can we not have .q files rather than these new java files? there are NegativeCLIDrivers I believe which can be used for -ve cases

**Comment by okumin** [comment]
We can add negative E2E test cases. Either is fine to me and I'm going to replace the unit tests.

**Comment by okumin** [comment]
@ayushtkn I updated the PR and CI tests passed

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by okumin** [comment]
Thank you!

**Pull request merged**
