### PR TITLE
HIVE-23628: Add Default Message for Github PRs

### PR DESCRIPTION
**Pull request by belugabehr**

### CODE REVIEW

**Comment by belugabehr** [comment]
@kgyrtkirk Can you take a look at this one.  I think it's safe to say here that "tests are unrelated" and push it. :)

**Comment by kgyrtkirk** [comment]
yeah - its true that it doesn't make much sense to test it....

**Comment by belugabehr** [comment]
@kgyrtkirk Can I get a +1 please?

**Comment by kgyrtkirk** [comment]
sure; +1
we might want to rethink how we want to continue placing votes on commits
https://issues.apache.org/jira/browse/HIVE-23628?focusedCommentId=17127614&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17127614

**Pull request merged**
