### PR TITLE
HIVE-24222: Upgrade ORC to 1.5.12

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Apache ORC from 1.5.10 to 1.5.12.

### Why are the changes needed?

This will bring the latest bug fixes.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CI with the existing test cases.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @sunchao . Could you re-trigger the failed CI?

**Comment by sunchao** [comment]
@dongjoon-hyun I think it is scheduled to be built? I _think_ when it is switched to build the state the test label will be changed.

**Comment by dongjoon-hyun** [comment]
Thank you for swift reply, @sunchao ~ But, my PR (1545) is failed in the CI when I clicked the `Details` link from there.
- http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-1545/1/pipeline

**Comment by dongjoon-hyun** [comment]
Ah, got it. It was due to my force push. I'll wait. Thank you so much, @sunchao !

**Comment by sunchao** [comment]
np!

**Review by pgaref — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @pgaref and @sunchao . It's passed.

**Review by sunchao — APPROVED** [review]
+1

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sunchao !

**Pull request merged**
