### PR TITLE
HIVE-21270: A UDTF to show schema (column names and types) of given q…

### PR DESCRIPTION
**Pull request by ShubhamChaurasia**
This UDTF helps to retrieve each column name and it's data type that would be produced in resultset when query is executed.
This UDTF can be executed as `SELECT GET_SCHEMA("<Some_Query>")`

### CODE REVIEW

**Comment by rmsmani** [comment]
Hi
One entry is required in show_functions.q.out check in #532 wherein I put entry for the UDF.

Since the udtf ends with e 2 entries are required, else pre commit tests will fail

**Comment by ShubhamChaurasia** [comment]
@rmsmani thanks, I added it to show_functions.q.out.
I am not sure I understand this:
> Since the udtf ends with e 2 entries are required

**Comment by rmsmani** [comment]
Hi
Test cases are defined in
ql/src/test/queries/clientpositive/show_functions.q
Where one test case is written to show the functions ending with e ie like operator.

**Comment by rmsmani** [comment]
Hi
Since this function gives the schema for the SQL query its better to have the function name as GET_SQL_SCHEMA

**Comment by rmsmani** [comment]
+1

**Comment by rmsmani** [comment]
@pvary  please merge the code with master

**Comment by rmsmani** [comment]
Hi @ashutosh-bapat, @sankarh
Can you merge the code

**Comment by rmsmani** [comment]
Source committed by @sankarh. Thanks
@ShubhamChaurasia close the PR

**Comment by rmsmani** [comment]
@ShubhamChaurasia 
As the sources merged, can you close this PR.

**Comment by ShubhamChaurasia** [comment]
@rmsmani thanks. Closed.

**Pull request closed without merging**
