### PR TITLE
HIVE-27580: Backport HIVE-20071: Migrate to jackson 2.x and prevent usage

### PR DESCRIPTION
**Pull request by wangyum**
### What changes were proposed in this pull request?

This is the third step to remove dependency on jackson-core-asl and jackson-mapper-asl.

### Why are the changes needed?

To fix SPARK-44719: `NoClassDefFoundError` when using Hive UDF.

### CODE REVIEW

**Comment by wangyum** [comment]
cc @sunchao @pan3793

**Comment by wangyum** [comment]
Add HIVE-22059 to fix:
```
 mvn clean install -DskipTests=true
cd service && mvn test -DwildcardSuites=none -Dtest=org.apache.hive.service.cli.session.TestSessionHooks test

[INFO] Running org.apache.hive.service.cli.session.TestSessionHooks
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.236 s <<< FAILURE! - in org.apache.hive.service.cli.session.TestSessionHooks
[ERROR] org.apache.hive.service.cli.session.TestSessionHooks.testSessionHook  Time elapsed: 3.128 s  <<< ERROR!
java.lang.NoSuchFieldError: ALLOW_LEADING_DECIMAL_POINT_FOR_NUMBERS
        at com.fasterxml.jackson.core.json.JsonReadFeature.<clinit>(JsonReadFeature.java:121)
        at org.apache.hadoop.hive.ql.udf.UDFJson.<clinit>(UDFJson.java:69)
...
```

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by sunchao** [comment]
Merged to branch-2.3, thanks @wangyum !

**Pull request merged**
