### PR TITLE
HIVE-27372：add bitmap function

### PR DESCRIPTION
**Pull request by cscsyiku123**
issue：https://github.com/apache/hive/commit/7bfc54ffc8baf5f3e7de326b750fe9355b11132b
change： add 30 bitmap functions in src/org.apache.hadoop.hive.ql.udf.bitmap and about some test in test/org.apache.hadoop.hive.ql.udf.bitmap

### CODE REVIEW

**Comment by cscsyiku123** [comment]
> Seems like the pom.xml has an issue. _incorrectly formatted pom.xmls_

solved

**Comment by cscsyiku123** [comment]
what means is lable of tests unstable

**Comment by aturoczy** [comment]
> t means is lable of tests unstable

There are tests that is executing for every PR, and a lot of this are integration tests, and sometimes the infrastructure or the test itself is unstable. We need to work on it to have more stable test environment and tests. It is likely not related to your code

**Comment by akshat0395** [comment]
@cscsyiku123 There is a q test failure, could you please check
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4355/4/tests

**Pull request closed without merging**
