### PR TITLE
HIVE-28636: partition_explain_ddl.q is flaky

### PR DESCRIPTION
**Pull request by okumin**
### What changes were proposed in this pull request?

Make EXPLAIN DDL deterministic.

https://issues.apache.org/jira/browse/HIVE-28636

### Why are the changes needed?

It would maek our integration test more stable. I guess the predictable result slightly contributes to the user experience.

### Does this PR introduce _any_ user-facing change?

The order of generated lines by EXPLAIN DDL could change. It is not a problem as it is not guaranteed.

### Is the change a dependency upgrade?

No.

### How was this patch tested?

I ran the entire integration tests and `partition_explain_ddl.q` has never failed. [hive-flaky-check](https://ci.hive.apache.org/blue/organizations/jenkins/hive-flaky-check/detail/hive-flaky-check/860/pipeline) also succeeded

### CODE REVIEW

**Comment by dengzhhu653** [comment]
Hi @okumin, thank you for PR, do we need to sort the `partName` as well? link: https://github.com/apache/hive/blob/afe05b968026dfdda631de1e2b090665f0820ef3/ql/src/java/org/apache/hadoop/hive/ql/exec/DDLPlanUtils.java#L672

**Comment by dengzhhu653** [comment]
Usually we also prove that the flakiness is gone after the fix using https://ci.hive.apache.org/job/hive-flaky-check/, can we also please do a check on this fix? Thank you!

**Comment by okumin** [comment]
@dengzhhu653

> Hi @okumin, thank you for PR, do we need to sort the partName as well? link:

I will check the remaining logic of EXPLAIN DDL.

> Usually we prove that the flakiness is gone after the fix using https://ci.hive.apache.org/job/hive-flaky-check/, can we also please do a check on this fix? Thank you!

I didn't know that. Do I need special permission to trigger it?

**Comment by dengzhhu653** [comment]
you need to login yourself firstly, no special permission needed. Filling this form https://ci.hive.apache.org/job/hive-flaky-check/build?delay=0sec and click the `Build` to run the validation.

**Comment by okumin** [comment]
@dengzhhu653 It requires some permission that you have. Can you give them to me?
image

**Comment by dengzhhu653** [comment]
It's strange, I don't know where to grant the permission, cc @ayushtkn @zabetak @nrg4878 
I will start a flack check on this fix

**Comment by zabetak** [comment]
@okumin Normally, you should be able to login to Jenkins with your GitHub credentials. If this doesn't work let me know and I will check further.

**Comment by zhangbutao** [comment]
Sorry i want to chip in about the jenkins login.
I can login the to Jenkins web-ui, but i can not start a new jenkinks test.  I'm not sure I'm missing some permission. I remember it was okay before.
 My Jenkins User ID: zhangbutao
jenkins_web

@zabetak Could you help to check this? Thx.

**Comment by zabetak** [comment]
@zhangbutao Normally, all users that are member of the apache group should have permissions to build/run jobs. I assume you are logging in using the GitHub authorization and your apache account is linked right?

**Comment by zhangbutao** [comment]
> @zhangbutao Normally, all users that are member of the apache group should have permissions to build/run jobs. I assume you are logging in using the GitHub authorization and your apache account is linked right?

Yes, i login in the jenkins using my github account. The jenkins id can also displays my github id : zhangbutao

**Comment by zabetak** [comment]
@zhangbutao @okumin let's continue the discussion about the Jenkins permissions issue under https://issues.apache.org/jira/browse/HIVE-28641 to avoid adding noise to the original purpose of this PR.

**Review by dengzhhu653 — APPROVED** [review]

**Comment by okumin** [comment]
@dengzhhu653 CI passed, and I made this PR ready. Could you please take a look? Thanks

**Pull request merged**
