### PR TITLE
HIVE-25912: Drop external table throw NPE if the location set to ROOT path

### PR DESCRIPTION
**Pull request by baifachuan**
### What changes were proposed in this pull request?

modify the HiveMetaStore. create_table_core function add this check:

```
if (!MetaStoreUtils.validateTblStorage(tbl.getSd())) {
    throw new InvalidObjectException(tbl.getTableName()
        + " location must not be root path");
}
```
If the path.getParent() is NULL we can be sure the location is ROOT path.  

the validateTblStorage implements:

```
/*
  * Check the table storage location must not be root path.
  */
 static public boolean validateTblStorage(StorageDescriptor sd) {
   return !(StringUtils.isNotBlank(sd.getLocation())
           && new Path(sd.getLocation()).getParent() == null);
 }
```

I add a test for this feature:

```
  @Test
  public void throwFailExceptionWithStorageIsRootPath() {
    StorageDescriptor sd = new StorageDescriptor();
    sd.setLocation("hdfs://localhost:8020");
    Assert.assertFalse(MetaStoreUtils.validateTblStorage(sd));

    sd.setLocation("hdfs://localhost:8020/");
    Assert.assertFalse(MetaStoreUtils.validateTblStorage(sd));

    sd.setLocation("hdfs://localhost:8020/other_path");
    Assert.assertTrue(MetaStoreUtils.validateTblStorage(sd));
  }
```

### Why are the changes needed?
If I create an external table using the ROOT path, the table was created successfully, but when I drop the table throw the NPE.  So I can't drop the table forever.

This is not a good phenomenon.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?

standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreUtils.java

test func is: throwFailExceptionWithStorageIsRootPath

mvn test -Dtest=SomeTest --pl common

### CODE REVIEW

**Comment by steveloughran** [comment]
Makes sense, but be aware that at lot of code doesn't like using / as a destination of work, as it is a special directory.

* paths are wrong
* rm / doesn't delete it

even after this is fixed, there's a risk that jobs to / will fail for other reasons.

**Comment by baifachuan** [comment]
> 

Yes,  I agree with it, but I think we should check the path throw a fail exception if the path is illegal,  create the table successfully but can not drop the table, this is not a good experience.

**Comment by baifachuan** [comment]
I fixed the bug with check the hive storage path, if it is a ROOT path throw an exception, broken the create table.

```
DEBUG : Shutting down query CREATE EXTERNAL TABLE `fcbai1`(
`inv_item_sk` int,
`inv_warehouse_sk` int,
`inv_quantity_on_hand` int)
PARTITIONED BY (
`inv_date_sk` int) STORED AS ORC
LOCATION
'hdfs://127.0.0.1:8020/'
Error: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. InvalidObjectException(message:fcbai1 location must not be root path) (state=08S01,code=1)
```

Ensure that creating tables and dropping tables behave the same.

**Comment by baifachuan** [comment]
@steveloughran can you invite me to join the hive slack discuss group? or

**Comment by steveloughran** [comment]
LGTM; and as its hard to test not worried about that. does need review from hive developers though

**Comment by baifachuan** [comment]
> assertFalse

Thanks for your suggestion, I have created a test for this feature.

**Comment by baifachuan** [comment]
> 

Thanks for your suggestion, I have created a test for this feature.

**Comment by pvary** [comment]
Maybe an overkill, but shall we create a test which makes sure that the method is not removed from the create table path?

Maybe something like this:
https://github.com/apache/hive/blob/master/standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java#L341

**Comment by baifachuan** [comment]
> Maybe an overkill, but shall we create a test which makes sure that the method is not removed from the create table path?
> 
> Maybe something like this: https://github.com/apache/hive/blob/master/standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java#L341

Thanks for your reply. I think this feature only adds a verification for the storage location, its compatibility with other tests.

I make sure to create fail when the location is ROOT path and make sure other tests pass.

So I add two tests to verify the ROOT path and not the ROOT path. 

TestTablesCreateDropAlterTruncate.java tests maybe like an E2E test.

I will consider adding a test for this case.

thx.

**Comment by zabetak** [comment]
@baifachuan Have you checked if the problem affects also the master branch?

**Comment by baifachuan** [comment]
> @baifachuan Have you checked if the problem affects also the master branch?

I'm sure the master also has this problem.

I test the master branch, have the same problem.

**Comment by baifachuan** [comment]
> @baifachuan Have you checked if the problem affects also the master branch?

I'm sure the master also has this problem.

I test the master branch, have the same problem.

I update the error info to jira.

**Comment by baifachuan** [comment]
I create a PR for the master branch, the link is: https://github.com/apache/hive/pull/3009

**Pull request closed without merging**
