### PR TITLE
HIVE-25384: Bump ORC to 1.6.9

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to bump ORC to 1.6.9.

### Why are the changes needed?

This will bring the latest bug fixes like ORC-804 .

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @pgaref

**Comment by dongjoon-hyun** [comment]
Also, cc @sunchao

**Review by sunchao — APPROVED** [review]
LGTM - pending CI.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sunchao !

**Review by pgaref — APPROVED** [review]
+1 from my side -- pending tests as I had to re-trigger them

**Comment by sunchao** [comment]
Merged. Thanks @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sunchao !

**Pull request merged**
