### PR TITLE
HIVE-24044: Implement listPartitionNames on temporary tables

### PR DESCRIPTION
**Pull request by dengzhhu653**
…orary tables

### What changes were proposed in this pull request?
Implement show partitions table_name with filter or order on temporary tables.

### Why are the changes needed?
If we use the show partitions table_name where condition on the temporary table,  a NoSuchObjectException will be thrown as the table does not save in metastore and show nothing to the end.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Unit tests

### CODE REVIEW

**Comment by dengzhhu653** [comment]
@laszlopinter86 @pvary could you please take a look? thanks

**Comment by dengzhhu653** [comment]
@laszlopinter86  cloud you take a look please? thank you!

**Review by laszlopinter86 — CHANGES_REQUESTED** [review]
Could you please add some q tests as well?

**Comment by dengzhhu653** [comment]
> Could you please add some q tests as well?

Done, could you please take another look? thanks much

**Review by laszlopinter86 — APPROVED** [review]

**Comment by dengzhhu653** [comment]
@lcspinter Could someone help push this in if there has no objections? thank you!

**Comment by lcspinter** [comment]
@dengzhhu653 Could you please provide your full name? I want this change to be credited to you.

**Comment by dengzhhu653** [comment]
> @dengzhhu653 Could you please provide your full name? I want this change to be credited to you.
Zhihua Deng

**Comment by dengzhhu653** [comment]
> @dengzhhu653 Could you please provide your full name? I want this change to be credited to you.

Zhihua Deng

**Comment by lcspinter** [comment]
Pushed to master. Thanks for the patch @dengzhhu653

**Comment by dengzhhu653** [comment]
> Pushed to master. Thanks for the patch @dengzhhu653

Thank you very much for the reviews and help, @lcspinter

**Pull request merged**
