### PR TITLE
HIVE-26948: Backport HIVE-21456 to branch-3

### PR DESCRIPTION
**Pull request by vihangk1**
### What changes were proposed in this pull request?
This PR backports HIVE-21456 to branch-3. To resolve some conflicts, following changes were done in addition to the original PR when compared to the master branch.
1. pom.xml --> updates the httpcomponents library version to 4.4.13 which is same as in master branch.

### Why are the changes needed?
Backport http transport support for Hive metastore in branch-3 so that users don't have to do a major upgrade to get this improvement.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Backported the tests from the original PR and made sure that they work.

### CODE REVIEW

**Comment by vihangk1** [comment]
The job says "There are 0 new tests failing, 21 existing failing and 261 skipped." so I think these are all previously failing tests. @amanraj2520 Any idea if these tests are known failures or not? Also, can you review this PR for branch-3?

**Comment by vihangk1** [comment]
The new failing test is probably due to infra issue. It works for me.
`[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.hive.ql.parse.TestParseDriver
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.709 s - in org.apache.hadoop.hive.ql.parse.TestParseDriver
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0`

**Comment by amanraj2520** [comment]
Hi @vihangk1 I see this new failures in the latest run testExoticSJSSubQuery

**Comment by vihangk1** [comment]
@amanraj2520 I ran the test multiple times locally and it did not fail. Also, looks unrelated to my PR.

**Comment by amanraj2520** [comment]
@vihangk1 Then the remaining test failures are because of the existing problems in branch-3 which I am fixing. So we are good as far as the test failures for this PR is concerned.

**Comment by zabetak** [comment]
@vihangk1 I would prefer if @sourabh912 reviews the changes here since he is the author of the original patch; I will +1 if he does!

In terms of process, I would prefer if we don't backport other changes till the build is stabilized; there are many times were failures seem unrelated to a specific PR but in practice they are not.

**Comment by vihangk1** [comment]
Thanks @zabetak, I am not sure if @sourabh912 is actively monitoring PRs in Hive, but I can reach out to him. Since this is not really a new code but a backport of the master branch, I feel this is still pretty low risk. Almost all the new code in this PR is under a config flag which is disabled by default. Additionally, @amanraj2520 confirmed that all the tests which are failing are known test failures.

**Comment by sourabh912** [comment]
Thanks @vihangk1 for the PR. I took a quick look and it looks good to me. +1 from my side.

**Comment by vihangk1** [comment]
Thanks @sourabh912 for the review. The test failure `TestObjectStore` looks like infra issue. I will retrigger the tests to make sure. Confirmed that the test works for me locally.

**Comment by vihangk1** [comment]
@amanraj2520 Do you know if the TestObjectStore which fails above with timeout issues is a known issue? I cannot reproduce it locally.

**Comment by amanraj2520** [comment]
@vihangk1 I do not see any failure related to TestObjectStore in the latest run http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3989/6/tests. Do you mean the TestRpc timeout issue?

**Comment by vihangk1** [comment]
Thanks @amanraj2520. Sorry I was referring to the [previous test run](http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3989/4/tests) for this PR. But the latest one passes that test. I cannot repro `TestRpc` and the [previous precommit run](http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3989/5/tests) on the same commit pass that test. So I think we should mark that test as flaky and disable it. I created https://issues.apache.org/jira/browse/HIVE-27062 sub-task to disable that test to ensure a green build.

**Comment by vihangk1** [comment]
Merged this. Thanks for your reviews and comments @sourabh912 @amanraj2520 @zabetak

**Pull request merged**
