### PR TITLE
HIVE-27508 : Backport of HIVE-21584 to branch-3

### PR DESCRIPTION
**Pull request by amanraj2520**

### CODE REVIEW

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Can you please review this as well. In continuation with https://github.com/apache/hive/pull/4493 for branch-3.1

**Comment by amanraj2520** [comment]
@kgyrtkirk @zmatyus @wangyum Can you please review this.

**Comment by amanraj2520** [comment]
Can someone in the community please review this

**Comment by vihangk1** [comment]
I took a quick look and compared with the PR from the master branch. The backport looks good to me. Thanks for backporting this. Do you know if the test failure is related?

**Comment by amanraj2520** [comment]
@vihangk1 No the test failure is not related at all. https://github.com/apache/hive/pull/4523 I have fixed it here. Once this is merged this PR will be green.

**Review by vihangk1 — APPROVED** [review]
LGTM. Lets wait for the CI job to come back green and then I can help merge this.

**Comment by amanraj2520** [comment]
Thanks a lot @vihangk1 for reviewing this.

**Comment by amanraj2520** [comment]
@vihangk1 Can you please merge this. Thanks a lot for reviewing.

**Comment by vihangk1** [comment]
merged into master. Thanks @amanraj2520

**Pull request merged**
