### PR TITLE
HIVE-25867: Partition filter condition should pushed down to metastor…

### PR DESCRIPTION
**Pull request by zzzzming95**
### What changes were proposed in this pull request?

If the partition filter condition in hql is an equivalent predicate, the metastore should be pushed down to RDBMS, which can optimize the query performance of hive large tables.

### Why are the changes needed?

If the hive table has too many partitions and there are multiple hql queries at the same time,RDBMS will increasing CPU IO_WAIT and affect performance.

### Does this PR introduce _any_ user-facing change?

No

### CODE REVIEW

**Comment by shezhiming** [comment]
@deniskuzZ  @pvary  @kasakrisz 

Can you please take a look at the patch?

**Comment by pvary** [comment]
With this change I think the filtering on the HMS DB side is effectively turned off. This would cause queries with smaller number of partitions become slow. Is this issue happening when there are too many partitions in the filter? Could we just turn off this filter if the number of partitions are too high?
What is the number of partitions in the query when you had experienced problems?

**Comment by zzzzming95** [comment]
> With this change I think the filtering on the HMS DB side is effectively turned off. This would cause queries with smaller number of partitions become slow. Is this issue happening when there are too many partitions in the filter? Could we just turn off this filter if the number of partitions are too high? What is the number of partitions in the query when you had experienced problems?

thanks @pvary .

in our case , We have a table (two partition fields) with about 60w partitions. When multiple sql jobs are executed at the same time, the HMS DB load will increase.

> Could we just turn off this filter if the number of partitions are too high?

According to my understanding, there should be no way for us to get the number of partitions before sql execution. Do you mean to cache the partitions number information in HMS to optimize ?

**Comment by pvary** [comment]
60w? - is this 60?
That should not cause to big of an issue for any backend db

**Comment by zzzzming95** [comment]
> 60w? - is this 60? That should not cause to big of an issue for any backend db

Sorry , "w" is a unique shorthand, I overlooked that.
60w=600000

**Comment by pvary** [comment]
600k partitions are always a pain.
We are working on integrating Iceberg that would help there.
I would guess that the solution is this case should be a configuration to turn off DB level filtering on query level. Maybe we already have a config for that.

**Comment by pvary** [comment]
Thanks for the explanation @zzzzming95! This was a misunderstanding on my side.

What happens if your query is like this - would the filtering work in this case?
```
select * from src_play_day WHERE dt='20211125' AND u_gtype='activity_workshop' limit 10;
```
Notice that I used `'`-s to convert 20211125 to string.

Another question is, how does this work with the other supported backend databases.
The issue with directSql is that we have to handle the differences between the SQL engines ourselves.

Also what happens when we have different types, like timestamp/binary/struct?

Thanks for investigating this issue, and coming up with possible solutions!

**Comment by zzzzming95** [comment]
> Notice that I used `'`-s to convert 20211125 to string.

@pvary 

This is our temporary solution, modify part of the history job hql , convert dt to string.

But we can't prevent our users from querying with dt=20211125, they will still use this non-standard usage, so we want to optimize this problem on the hive metastore side.

> Another question is, how does this work with the other supported backend databases.
> The issue with directSql is that we have to handle the differences between the SQL engines ourselves.

I will test various situations in the future, and reply the results below this issue.

**Comment by pvary** [comment]
Thanks @zzzzming95!
Also please check for possible sql injection - a quick cursory scan of the code shows that we use parametrised queries, but please make sure that we do so in every place.

Thanks again!
Peter

**Pull request closed without merging**
