### PR TITLE
HIVE-28355: Fix intermittent failure of TestHplSqlViaBeeLine#testUNIX_TIMESTAMPHplSQLFunction

### PR DESCRIPTION
**Pull request by KiranVelumuri**
### What changes were proposed in this pull request?

Compare absolute UNIX timestamps value instead of using regex.

### Why are the changes needed?

https://issues.apache.org/jira/browse/HIVE-28355

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

mvn test

### CODE REVIEW

**Comment by KiranVelumuri** [comment]
There were Sonarcloud issues for variable names not complying with the naming convention for some variables. So, I made the appropriate refactoring changes for these variables.

**Comment by KiranVelumuri** [comment]
@okumin Please review

**Comment by okumin** [comment]
I might need some more time since I am not familiar with the issue, maybe. Also, please note that you finally need to get +1 from a committer

**Review by okumin — APPROVED** [review]
The description of HIVE-28355 is super great. Thanks for the detailed explanation. This change would resolve the problem.

For reference, I am putting alternatives that came to my mind. I don't have preference and the current PR looks fine to me.
- Just to remove the non-deterministic test case
- To change the expected text to `{System.currentTimeMillis()/10000}|{System.currentTimeMillis()/10000 + 1}`

**Comment by shivjha30** [comment]
Have you worked on it?

**Comment by KiranVelumuri** [comment]
> The description of [HIVE-28355](https://issues.apache.org/jira/browse/HIVE-28355) is super great. Thanks for the detailed explanation. This change would resolve the problem.
> 
> For reference, I am putting alternatives that came to my mind. I don't have preference and the current PR looks fine to me.
> 
> * Just to remove the non-deterministic test case
> * To change the expected text to `{System.currentTimeMillis()/10000}|{System.currentTimeMillis()/10000 + 1}`
> * Control the output using `hive.test.currenttimestamp`

Thank you for the quick review. The first alternative would not work as the test result depends on the time of execution of test. For the latter one, the test would fail when the timestamp differs other than ten's digit. Could you please tag a committer to get +1? Thank you.

**Comment by KiranVelumuri** [comment]
@zhangbutao Could you also please review this? Thank you.

This issue is occuring intermittently depending on the time of execution of the test. 
Screenshot from recent occurence:
image

**Review by zhangbutao — APPROVED** [review]
+1 LGTM
Thanks for the fix!

**Comment by KiranVelumuri** [comment]
Thank you @okumin and @zhangbutao for the review!

**Pull request merged**
