### PR TITLE
HIVE-22981: DataFileReader is not closed in AvroGenericRecordReader#e…

### PR DESCRIPTION
**Pull request by losipiuk**
Clean cherry pick of HIVE-22981 to 3.1 branch.

JIRA: https://issues.apache.org/jira/browse/HIVE-24400

### CODE REVIEW

**Comment by findepi** [comment]
@kgyrtkirk can you please help analyze the test failure? is there something that needs to be changed in this PR?

**Comment by losipiuk** [comment]
This PR is still valid. What can I do @kgyrtkirk to push it forward?

**Comment by kgyrtkirk** [comment]
on branch-3 we didn't used this test system that much - I think we can merge this

**Comment by losipiuk** [comment]
> on branch-3 we didn't used this test system that much - I think we can merge this

Thanks @kgyrtkirk !

**Pull request merged**
