### PR TITLE
HIVE-26547: setting primary key constraint for DELEGATION_TOKENS tabl…

### PR DESCRIPTION
**Pull request by thakkardharmik**
…e in oracle

### CODE REVIEW

**Comment by nrg4878** [comment]
re-opening the PR for review. We need to review and merge this fix.

**Review by rtrivedi12 — CHANGES_REQUESTED** [review]
The beta-1 release is now out. So the filename will have to be renamed from hive-schema-4.0.0-alpha-2.sql to hive-schema-4.0.0..sql.

**Review by rtrivedi12 — CHANGES_REQUESTED** [review]
We need this change only in the recent schema file hive-schema-4.0.0.oracle.sql and upgrade script from 4.0.0-beta-1 to 4.0.0

**Comment by deniskuzZ** [comment]
@thakkardharmik, you should only change the latest schema and upgrade script

**Pull request closed without merging**
