### PR TITLE
HIVE-26895 : Backport of HIVE-22899: Make sure qtests clean up copied files from test directories

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-26895

### CODE REVIEW

**Review by cnauroth — COMMENTED** [review]
Hello @amanraj2520 . Did this pull request accidentally include changes unrelated to HIVE-22899?

**Comment by amanraj2520** [comment]
@cnauroth Yes I raised it just to check a few tests like compustat_avro.q which were failing due to formatting issues. Will re-raise this PR. That's why I did not ask anyone to review.

**Comment by amanraj2520** [comment]
@cnauroth @abstractdog Removed all the old commits and pushed latest change to the branch. Can you please check this and approve

**Review by cnauroth — COMMENTED** [review]
Hello @amanraj2520 . The backport looks good, but I tried applying the patch locally to test, and I still saw leftover files.

```
mvn -B -o test -Dtest=TestNegativeCliDriver -Dqfile=strict_managed_tables4.q

find . -name smt6_schema.avsc
./target/tmp/smt6_schema.avsc
```

When you test locally, are you seeing it clean up this file?

**Comment by amanraj2520** [comment]
@cnauroth Checking this.

**Comment by amanraj2520** [comment]
Hi @cnauroth you are correct
image


How to resolve this? Do you know by any chance. I am also looking into it. Ideally it should have removed this .avsc file right? Since at the end of the test it does call the remove command.

**Comment by amanraj2520** [comment]
I think I got the issue. Maybe because at the end we are calling "dfs -rm" instead of "rm" therefore it is not able to delete the file from the local file system. Is it not expected ?

**Review by cnauroth — APPROVED** [review]
`dfs -rm` should be the right command, analogous to the [Hadoop FileSystem Shell](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/FileSystemShell.html).

I did some testing on current master, and I see the same problem there:

```
mvn -B -o test -Dtest=TestNegativeLlapLocalCliDriver -Dqfile=strict_managed_tables4.q

find . -name smt6_schema.avsc
./target/tmp/smt6_schema.avsc
```

I think I understand the problem. For these negative tests, we're expecting a failure at some point. In strict_managed_tables4.q, the failure happens at the second `CREATE TABLE` (managed table) statement. The script is going to abort there, so it won't ever really run the `dfs -rm`. (There isn't anything like a `finally` block here to guarantee cleanup.)

I have no objection to this backport for the sake of consistency. I reviewed the original commit, and it looks like a clean backport, so I'll put my +1 (non-binding) on it. However, it appears that HIVE-22899 alone is not a complete solution.

**Comment by amanraj2520** [comment]
@cnauroth Got it. Thank your for approving this PR. So essentially how can we add something like a finally block in the test? I think we can try to add that in the TestNegativeLlapLocalCliDriver class right? Something like if the test fails, we can have another .q file having only a statement called from the finally block like "dfs -rm *.avsc". Or what do you suggest.

**Comment by cnauroth** [comment]
@amanraj2520 , yes, something like what you described would work.

Although maybe it's not even really necessary to guarantee this level of cleanup. The original problem before HIVE-22899 was that multiple tests were trying to copy to the same destination path, potentially causing a collision and a failure for some of the tests. Part of what this patch did is to guarantee tests were operating on unique destination paths (even if they were copying from the same source path), so no 2 tests should collide anymore. The cleanup is nice to have, but everything under `target` would get deleted on the next `mvn clean` anyway.

**Comment by amanraj2520** [comment]
@cnauroth Something like this we can think about:
image

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Can you please review and merge this patch.

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Please review and merge this.

**Comment by amanraj2520** [comment]
Hi @zabetak @abstractdog Kindly review this

**Review by abstractdog — APPROVED** [review]

**Comment by abstractdog** [comment]
after all the conversation, this looks good to me

**Pull request merged**
