### PR TITLE
HIVE-26423: Make commons-pool2 an explicit dependency (and upgrade to 2.11.1)

### PR DESCRIPTION
**Pull request by jfsii**
### What changes were proposed in this pull request?
Makes commons-pool2 an explicit dependency

### Why are the changes needed?
To prevent runtime issues and to make a dependency that we directly use explicit.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Through this PRs test framework and verification that the specified version of commons-pool2 is getting put in the packaging directory.

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
Makes sense to add it explicitly. Just to know the current version that was getting packaged was also 2.11.1?

**Comment by jfsii** [comment]
> Makes sense to add it explicitly. Just to know the current version that was getting packaged was also 2.11.1?
@ayushtkn 
I went with the newest version out of caution for CVEs, etc  (I didn't see any compilation issues and in my bit of local testing I did not see any ClassNotFoundException - the version getting packaged was 2.7.0.

I can certainly downgrade to 2.7.0 if you think that to be prudent.

**Review by ayushtkn — APPROVED** [review]
That should be ok. Just better to mention in the Jira/PR title as well that we are upgrading commons-pool2 dependency along with this PR.

Changes LGTM

**Comment by jfsii** [comment]
> That should be ok. Just better to mention in the Jira/PR title as well that we are upgrading commons-pool2 dependency along with this PR.
> 
> Changes LGTM

Done - I updated the the PR title, the commit title and included the version information in the JIRA.

**Pull request merged**
