### PR TITLE
HIVE-28404: Fix typo Overriden to Overridden

### PR DESCRIPTION
**Pull request by caicancai**
### What changes were proposed in this pull request?

fix typo Overriden to Overridden
https://issues.apache.org/jira/browse/HIVE-28404

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
can you create a HIVE jira and prefix that in the PR title

**Comment by caicancai** [comment]
> can you create a HIVE jira and prefix that in the PR title

Thanks for the reminder. I thought that simply correcting typos did not require creating a jira.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by caicancai** [comment]
@ayushtkn Hi, I only corrected the typos and don't understand why the cli failed

**Comment by ayushtkn** [comment]
I have triggered the build again. if it fails again, need to investigate, I think some running infra issue

**Comment by caicancai** [comment]
@ayushtkn Thanks

**Pull request merged**
