### PR TITLE
HIVE-27310: Upgrade jQuery to fix CVEs

### PR DESCRIPTION
**Pull request by devaspatikrishnatri**

### CODE REVIEW

**Comment by aturoczy** [comment]
Is there any breaking changes in jquery 3.6.4? 

From 3.3.1 to 3.5.1 is as big step as for 3.6.4. If it is OK to you we can try for the latest version to fix all the CVE's.

We also appreciate this change, but If we can use the latest would be even better :)

**Comment by devaspatikrishnatri** [comment]
Have used jQuery 3.6.4 and the build and tests have seemed to pass.

I think this upgrade can be done.

**Comment by devaspatikrishnatri** [comment]
@aturoczy Could you please check this ?
I used  3.6.4 and the build and tests have seemed to pass.

**Comment by aturoczy** [comment]
@deniskuzZ @ayushtkn Could you please check and merge? I think it is safe.

**Review by aturoczy — APPROVED** [review]
LGTM

**Review by aturoczy — APPROVED** [review]
LGTM

**Comment by devaspatikrishnatri** [comment]
@aturoczy I do not have any explicit list. I just try to fix CVEs as and when I get to know them.

**Pull request merged**
