### PR TITLE
HIVE-27466. (2.3) Remove obsolete reference to category-X JSON license from NOTICE

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Backport HIVE-27466 to 2.3.

### Why are the changes needed?

https://github.com/apache/spark/pull/45372#issuecomment-1977151289

### Does this PR introduce _any_ user-facing change?

No

### Is the change a dependency upgrade?

NO

### How was this patch tested?

Review

### CODE REVIEW

**Comment by pan3793** [comment]
cc @sunchao

**Comment by sunchao** [comment]
@pan3793 could you rebase this PR?

**Comment by pan3793** [comment]
After rebase, this patch becomes noop, it's already covered by #5148, close then

**Comment by pan3793** [comment]
@sunchao BTW, I took a look at HIVE-27504 (the last one you listed), looks like a little bit of overkill for a maintenance release, and the patch must be tuned because the dependency trees are quite different.

**Comment by sunchao** [comment]
Thanks. I think it should be OK too. It doesn't seem like a blocker.

**Comment by pan3793** [comment]
OK. Then the only pending PRs are https://github.com/apache/hive/pull/5151 and https://github.com/apache/hive/pull/4911, right? Please let me know how can I do to help speed up the 2.3.10 release

**Pull request closed without merging**
