### PR TITLE
[HIVE-13482][UDF] Explicitly define str_to_map args as regex

### PR DESCRIPTION
**Pull request by MichaelChirico**
Successor to https://github.com/apache/spark/pull/23888

See discussion there for some more details about the Hive side of this, in particular [my comment here](https://github.com/apache/spark/pull/23888#issuecomment-467742127) about existing StackOverflow answers and [here](https://github.com/apache/spark/pull/23888#issuecomment-467747788):

> My conclusion is that it's eminently ambiguous whether the _intended_ behavior in either Hive or SparkSQL is to treat the delimiters as regular expressions.

> BUT the behavior has been around for [8 years](https://github.com/apache/hive/commit/4f8294e578db449294a1186f0ac4efb041445dcb) and at least going off of the SO answers, it seems to be accepted as "known" behavior so things will probably break if we change it.

Thus, this PR intends to solidify the interpretation of `delimiter1` and `delimiter2` as regular expressions once and for all.

If the non-regexp behavior is strongly desired, eventually there could be a `fixed: bool` argument that behaves like the identically-named argument in R regular expression functions like [`gsub`](http://astrostatistics.psu.edu/su07/R/html/base/html/grep.html) and [`strsplit`](http://astrostatistics.psu.edu/su07/R/html/base/html/strsplit.html)...

### CODE REVIEW

**Comment by sankarh** [comment]
Attach a patch in the jira and let the ptest build run.

**Comment by MichaelChirico** [comment]
Is that something I could do on my end?

**Comment by sankarh** [comment]
@MichaelChirico 
Yes, just name your patch file as HIVE-13482.01.patch and you can attach it after assigning the jira ticket to yourself.
After attaching the patch, just click "submit patch" and ptest will automatically kick in.

**Comment by MichaelChirico** [comment]
@sankarh thanks. I've assigned myself but I'm not sure what a "patch file" is, some sort of diff?

**Comment by MichaelChirico** [comment]
@sankarh OK, done I think... though I update to master and now the diff on this PR looks huge, the patch file is the much smaller diff from the first commit here.

Please do advise if there's anything to fix

**Comment by rmsmani** [comment]
@MichaelChirico

Git pull to your local repo.

Run the below command
git diff --no-prefix <latest commit hash> > HIVE.XXXX.XX.PATCH

this will give the diff between the latest commit and your proposed changes.
The ln upload the for to the jira.
And do the submit patch.

**Comment by dlavati-hw** [comment]
@MichaelChirico for a more verbose explanation you can refer to https://cwiki.apache.org/confluence/display/Hive/HowToContribute

**Comment by dlavati** [comment]
@MichaelChirico for a more verbose explanation you can refer to https://cwiki.apache.org/confluence/display/Hive/HowToContribute

**Comment by MichaelChirico** [comment]
@rmsmani @dlavati thanks, sorry for the delay. Diff is back to just the docstring change & the `.01` patch on JIRA should reflect this. Hopefully good to go now.

**Comment by MichaelChirico** [comment]
@rmsmani @dlavati any update from your end?

**Comment by dlavati-hw** [comment]
@MichaelChirico your last patch attached to Jira had test failures which might need fixes even in the current upstream state.
Right now the testing infra is being refactored to use Github, but I'm not sure whether you'd need a new push to this PR to trigger a test. If you pull+rebase apache/master on your branch and push, you'd probably get a new test run here.
PRs will only get merged after a green run and a commiter's approval. (I'm not one, so someone else from the community might help when you have a good patch)

**Comment by kgyrtkirk** [comment]
I think probably an open/close should also trigger a new testrun...let's see

**Comment by kgyrtkirk** [comment]
you will need to also update 1 test to get this in:
```
mvn install -Dtest=TestMiniLlapCliDriver#testCliDriver[str_to_map] -Dtest.output.overwrite -Pitests
```

**Comment by MichaelChirico** [comment]
@kgyrtkirk thanks, I updated the string in that test, as well as updating to master.

Is there a reason to be testing exact docstrings in the test? I wouldn't have expected a test to fail because of a few words changing in the docs.

**Comment by kgyrtkirk** [comment]
you've edited the q.out file? please run the command I've wrote for you.

> Is there a reason to be testing exact docstrings in the test? I wouldn't have expected a test to fail because of a few words changing in the docs.

Hive could be improved from a lot of aspects; this might not be needed - one thing I could think of why this might be a usefull: in the annotation stuff you might not see the message formatted as it will appear on the terminal for users...

**Comment by MichaelChirico** [comment]
I ran that command but it failed on something else. I am not qualified to diagnose the reason.

Honestly frustrated that a simple documentation fix could take 16 months to fix. I'm giving up.

**Pull request closed without merging**
