### PR TITLE
HIVE-27477: Upgrade maven plugin versions

### PR DESCRIPTION
**Pull request by Aggarwal-Raghav**
### What changes were proposed in this pull request?
Upgrade maven plugins versions

### Why are the changes needed?
To use the latest plugins version

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
Yes, but only maven plugins versions.

### How was this patch tested?
By local build and test

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]
+1

**Comment by Aggarwal-Raghav** [comment]
PR failed with `Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project hive-classification: No tests matching pattern "noMatches" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.)`

Because of [SUREFIRE-1910](https://issues.apache.org/jira/browse/SUREFIRE-1910) the default value of `surefire.failIfNoSpecifiedTests` is set to `true`. Earlier the default value was not mentioned and this issue starts from surefire version 3.0.0-M6. Hence adding one xml tag in maven-surefire-plugin configuration `<failIfNoSpecifiedTests>false</failIfNoSpecifiedTests>`

**Review by zabetak — CHANGES_REQUESTED** [review]
This upgrade is too aggressive and unlikely to work without problems. Things like the surefire plugin are not trivial too update (check previous PRs and related JIRAs) and the same goes for some of the rest. @Aggarwal-Raghav It might be wiser to handle upgrade individually; at the very least keep `surefire` apart.

**Comment by Aggarwal-Raghav** [comment]
> This upgrade is too aggressive and unlikely to work without problems. Things like the surefire plugin are not trivial too update (check previous PRs and related JIRAs) and the same goes for some of the rest. @Aggarwal-Raghav It might be wiser to handle upgrade individually; at the very least keep `surefire` apart.

Sure @zabetak. Will update the PR accordingly. Thanks for the insights.

**Comment by Aggarwal-Raghav** [comment]
@zabetak, I have removed surefire upgrade from this PR. Will handle it separately. Let me know if this commit also needs to be split into individual maven plugin version upgrade.

**Review by zabetak — APPROVED** [review]
Tests passed so its good to go! Will merge soon.

**Pull request closed without merging**
