### PR TITLE
HIVE-27862: Map propertyContent to a wrong column in package.jdo

### PR DESCRIPTION
**Pull request by dengzhhu653**

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]

**Review by ayushtkn — COMMENTED** [review]
Ideally the column name in ``METASTORE_DB_PROPERTIES`` should have been ``PROPERTY_CONTENT`` like other columns, but I think we have to live with it now, due to compat issues...

There is no test which was checking the output?

**Comment by dengzhhu653** [comment]
> Ideally the column name in `METASTORE_DB_PROPERTIES` should have been `PROPERTY_CONTENT` like other columns, but I think we have to live with it now, due to compat issues...
> 
> There is no test which was checking the output?

There are some tests `HMSDirectTest` which are testing out the fetch or save of  `PROPERTY_CONTENT` on derby, but they get through the test, not sure why.

**Comment by ayushtkn** [comment]
hmm, do we need to catch someone from HMS side to figure out why those tests aren't working? I think it isn't an ideal situation for us, these bugs will keep on coming if those tests aren't working the way they should

**Review by ayushtkn — APPROVED** [review]
LGTM.
Thanx @dengzhhu653

**Pull request merged**
