### PR TITLE
HIVE-26971 : Test fix in load_data_using_job.q.out (Done as part of HIVE-20593 addendum patch)

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-26971
This fix was done is master using this commit id : dca6ef04 (Title : HIVE-20593 addendum)
Link to the failed test : http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3929/4/tests/

### CODE REVIEW

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Can you please review and merge this. Just a simple test fix also attached the ticket which caused this in CALCITE.

**Review by zabetak — COMMENTED** [review]
In the future, when you provide links to failures cite the reference branch (http://ci.hive.apache.org/job/hive-precommit/job/branch-3) not individual PRs to rule out possible interference due to the changes elsewhere.

A few questions:
* Why CALCITE-1413 causes these changes? I cannot easily see the connection.
* The test doesn't seem to fail consistently in branch-3; why is that?

**Comment by amanraj2520** [comment]
@zabetak I could not figure out why it has a specific connection with Calcite-1413. I had checked in some bad branch or something. I have changed the title to pick the change when this test was fixed in oss master. Kindly review it now

**Comment by amanraj2520** [comment]
@zabetak Can you please review this

**Comment by zabetak** [comment]
@amanraj2520 I merged the changes but I have some comments. 

The PR as well as the JIRA summary are misleading; the changes are NOT a backport of HIVE-20593. The changes is a simple update of a .q.out file. Please change the title here and the JIRA summary accordingly (see my commit message).

Moreover, the relation with HIVE-20593 is unclear. HIVE-20593 has been for a while in branch-3 but the test started failing recently. For instance when we enabled the tests in [branch-3](http://ci.hive.apache.org/job/hive-precommit/job/branch-3/1/#showFailuresLink) the test was not failing. Please be more meticulous and precise in further investigations.

**Comment by amanraj2520** [comment]
Hi @zabetak Thanks for your review. This was done as part of HIVE-20593 addendum patch. Please follow this commit id : https://github.com/apache/hive/commit/dca6ef04e376ea1e18cd8986c3baf210b51d7677. Can you please mark this as complete and close this. Apologies for not mentioning the commit id.

**Comment by amanraj2520** [comment]
@zabetak There is no specific JIRA created for this. So I have mentioned the commit id of master. Thanks for merging it.

**Comment by zabetak** [comment]
@amanraj2520 You created HIVE-26971 so there is a specific JIRA for the test failure; not sure what you mean that there is no specific JIRA for this.

The commit https://github.com/apache/hive/commit/dca6ef04e376ea1e18cd8986c3baf210b51d7677 mentions HIVE-20593 but as I wrote above the same reason does not seem to apply here. 

HIVE-20593 is in branch-3 for a while now so if the problem was HIVE-20593 then the test should fail from the beginning that we started running CI in branch-3; not after merging 15 patches. There somethings more to it.

**Comment by amanraj2520** [comment]
@zabetak What I meant is that when this change was committed to OSS master, then there was no specific JIRA created for this issue back then. It was done only under HIVE-20593 addendum patch. In order to fix this issue I compared the load_data_using_job.q.out between OSS/master and current branch-3(without this commit). The diff in these lines lead me to this commit https://github.com/apache/hive/commit/dca6ef04e376ea1e18cd8986c3baf210b51d7677 which was done in OSS/master without any JIRA ticket being created for this commit. If you go to this commit it simply says HIVE-20593 addendum patch. Not sure why there was no specific JIRA created for this test failure.
image

In order to answer your question why these tests did not fail on branch-3 even if HIVE-20593 has been on branch-3 for a long time is as follows:
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3847/1/tests - There was no Jenkins file committed to branch-3 before. Thats why I decided that when we do the 3.2.0 release from branch-3, I would ensure that all the test pass in branch-3. This is the first commit that I had made after committing the Jenkins file to branch-3(which means that this was the first pull request which ran the jenkins pipeline for the tests). I see the test failure even here : (Link : http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3847/1/tests) Attached the snapshot as well.

image

Can you please ping a link where you find this test passing because I think that as far as all the PR's I have merged in branch-3, I find this test failing in every PR since we setup the Jenkins pipeline.

**Comment by zabetak** [comment]
@amanraj2520 Thanks for the detailed explanation.

After checking all runs in [branch-3](http://ci.hive.apache.org/job/hive-precommit/job/branch-3/) here is what I found. 

The `load_data_using_job.q` was not running [when we enabled the tests in the branch](http://ci.hive.apache.org/job/hive-precommit/job/branch-3/1/#showFailuresLink); I wrongly assumed that it was passing since I didn't see it in the failure list.

It appears that the test started running after merging (https://github.com/apache/hive/commit/a25392b28576c620b37cf19336eab186697c3330) and since then it was always failing.

So indeed it can be due to [HIVE-20593](https://issues.apache.org/jira/browse/HIVE-20593).

**Comment by amanraj2520** [comment]
Thanks @zabetak

**Comment by amanraj2520** [comment]
Just for everyone's information, the changes have been merged into branch-3 for this PR using this commit id : 5205d575bb2d0a74383eaf73a8089b2fc8216f87

**Pull request closed without merging**
