### PR TITLE
HIVE-24325: Cardinality preserving join optimization fails when column is backtracked to a constant

### PR DESCRIPTION
**Pull request by jcamachor**

### CODE REVIEW

**Comment by jcamachor** [comment]
@kasakrisz , could you review? Thanks

**Review by kasakrisz — APPROVED** [review]
LGTM

**Comment by jcamachor** [comment]
@kasakrisz , I have changed the approach slightly (I think new code is better). Could you take another quick look? Thanks

**Review by kasakrisz — APPROVED** [review]

**Comment by kasakrisz** [comment]
:+1: new approach

**Comment by pvargacl** [comment]
@jcamachor cardinality_preserving_join_opt2.q is failing, because the current month changed :)
See an example: http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-1592/10/tests

**Comment by jcamachor** [comment]
Thanks @pvargacl . I will fix it and reenable it shortly.

**Pull request merged**
