### PR TITLE
HIVE-27012:Remove JavaEWAH dependency from HIVE to fix CVEs.

### PR DESCRIPTION
**Pull request by devaspatikrishnatri**
### What changes were proposed in this pull request?
Upgrade JavaEWAH to 1.1.7

### Why are the changes needed?
Fix CVEs

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Hive was build locally , then javaewah was removed and was successfully built again.

### CODE REVIEW

**Comment by devaspatikrishnatri** [comment]
@nrg4878 could you please take a look at this ?

**Review by saihemanth-cloudera — COMMENTED** [review]
I don't like the idea of removing this javaewah dependency in Hive. Can we upgrade this to CVE free version?

**Comment by devaspatikrishnatri** [comment]
I think we do not use this in HIVE anymore, so should be safe to remove.

**Review by saihemanth-cloudera — APPROVED** [review]
LGTM +1

**Pull request merged**
