### PR TITLE
HIVE-27453: Backport of HIVE-21498: Thrift version upgrade to 0.13.0

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-27453

### CODE REVIEW

**Comment by amanraj2520** [comment]
@saihemanth-cloudera Can you please review this

**Comment by amanraj2520** [comment]
@nrg4878 Can you please also review this.

**Comment by amanraj2520** [comment]
@vihangk1 Can you please review this.

**Comment by nrg4878** [comment]
@saihemanth-cloudera  Can you please review when you have a chance? Thank you

**Comment by amanraj2520** [comment]
@saihemanth-cloudera The tests have passed. Please review this.

**Review by saihemanth-cloudera — APPROVED** [review]
LGTM +1

**Comment by amanraj2520** [comment]
Thanks for the review @saihemanth-cloudera. Can you please merge this ticket.

**Comment by saihemanth-cloudera** [comment]
I'm planning on waiting for 24hrs to see if anyone has concerns. If not I'll merge it.

**Pull request merged**
