### PR TITLE
HIVE-27206: Backport of HIVE-20179: Some Tez jar-s are not on classpath so HS2 keeps too long

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-27206

This issue was already a part of Hive-3.1.3 so it should be cherry picked to branch-3

### CODE REVIEW

**Comment by amanraj2520** [comment]
@vihangk1 Can you please approve this. This was already present in branch-3.1 (Hive 3.1.3) but not in branch-3

**Review by vihangk1 — APPROVED** [review]
+1 LGTM

**Comment by vihangk1** [comment]
Looks like there is still some intermittent flakiness in the CI job. Retriggered the tests.

**Comment by amanraj2520** [comment]
@vihangk1 Can you please merge this.

**Comment by amanraj2520** [comment]
@vihangk1 Can we please merge this. The tests have passed

**Comment by amanraj2520** [comment]
@vihangk1 Can you please merge this.

**Review by sankarh — APPROVED** [review]

**Pull request merged**
