### PR TITLE
HIVE-24922: Remove redundant code and improve readability

### PR DESCRIPTION
**Pull request by dh20**
What changes were proposed in this pull request?

Get rid of the extra code
Why are the changes needed?
Compaction observability
Submit code quality
Does this PR introduce any user-facing change?
No

How was this patch tested?
Unit test

### CODE REVIEW

**Review by miklosgergely — APPROVED** [review]
Please add a more specific commit message, something that refers to the fact that you are removing those codes from ExecDriver

**Comment by dh20** [comment]
> Please add a more specific commit message, something that refers to the fact that you are removing those codes from ExecDriver

ok.sir

1. In the mwork object, nummaptasks, maxsplitsize, minsplitsize, minsplitsize pernode, minsplitsize perrack, numreeducetasks have been added. Declaration becomes the corresponding value type, so I don't think it's necessary to use longvalue () and intvalue () to get them, which is redundant
2. getcurrentdb() is only used in the current class execdriver class, so it should be modified by private

**Comment by dh20** [comment]
- [ ] 

> [``](

- 

1. url

)

**Comment by dh20** [comment]
@sunchao hi, sir！ Can you review it for me？thanks

**Comment by dh20** [comment]
@aasha hi,Can you review it for me?thanks

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by dh20** [comment]
@sunchao sir,Can you merge it for me? thanks

**Comment by sunchao** [comment]
Merged. Thanks @dh20 .

**Pull request merged**
