### PR TITLE
HIVE-24559: Fix some spelling issues

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

This pull request fixes some minor typos.

### Why are the changes needed?

This pull request fixes some minor typos.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No need to be tested.

### CODE REVIEW

**Comment by rickyma** [comment]
Hey @vihangk1, here's another patch to master, just fixing some typo issues~~ Could you please merge this again? Thanks a lot.

**Comment by rickyma** [comment]
Hey @vihangk1, could you please help me merge this? The patch does not have any code changes, just fixing some typo issues~

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by rickyma** [comment]
@sunchao Thanks a lot.

**Pull request merged**
