### PR TITLE
HIVE-27381 : Upgrade Arrow to 7.0.0

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-27381

### CODE REVIEW

**Comment by amanraj2520** [comment]
@ayushtkn @abstractdog @zabetak Request you to review this.

**Comment by aturoczy** [comment]
The change is itself not huge, but I'm curious why you did not choose the latest 12 version? is there any incompatibility with that?

Were you able to test it? (I guess there is not much interface differences between the versions just for safety reason.)

**Review by aturoczy — COMMENTED** [review]
The change is itself not huge, but I'm curious why you did not choose the latest 12 version? is there any incompatibility with that?

Were you able to test it? (I guess there is not much interface differences between the versions just for safety reason.)

**Comment by amanraj2520** [comment]
Hi @aturoczy I did this change to align Hive with latest Spark 3.3 which uses arrow 7.0.0. As such I do not think arrow will bring in any breaking change since in Spark as well this upgrade was done without any major code change. Arrow 7.0.0 just brought in a flatbuffer version issue which I have upgraded and the tests run fine.

**Comment by amanraj2520** [comment]
Can someone please help to review and merge this.

**Comment by amanraj2520** [comment]
@aturoczy Can you please approve and merge this

**Comment by amanraj2520** [comment]
@warriersruthi Can you please review this.

**Comment by InvisibleProgrammer** [comment]
@ayushtkn , @veghlaci05 , @deniskuzZ : Can I ask for a review on that?

**Comment by akshat0395** [comment]
arrow-vector 7.0 has multiple CVE issues, [Arrow Maven](https://mvnrepository.com/artifact/org.apache.arrow/arrow-vector/7.0.0)
I suggest we upgrade to latest which is 12 as @aturoczy mentioned to avoid introducing new CVEs in Hive.

**Review by aturoczy — APPROVED** [review]
+1

**Comment by warriersruthi** [comment]
+1 LGTM

**Review by veghlaci05 — APPROVED** [review]
LGTM

**Review by deniskuzZ — APPROVED** [review]
+1

**Comment by deniskuzZ** [comment]
sorry, I missed @akshat0395 comment just checked that there is a binding +1. Should we upgrade arrow-vector to version 12?

**Comment by InvisibleProgrammer** [comment]
Hi @amanraj2520 ,

Based on the previous commits, could you please upgrade it to 12 instead of 7? 

Quick note about Spark: at the most recent version, they use 12 as well: https://github.com/apache/spark/blob/480b14f4b45a4e01e7e4bdea82475d4c77a6b89f/pom.xml#L219
And at the last release (3.4), they use 11:  https://github.com/apache/spark/blob/a2c915db50c76fee1290d8a6a6aab9f41100a60b/pom.xml#L223

Thank you

**Pull request merged**
