### PR TITLE
HIVE-24051 : Hive lineage information exposed in ExecuteWithHookContext

### PR DESCRIPTION
**Pull request by szehon-ho**
The lineage information is not populated unless certain hooks are enabled.

However, this is a bit fragile, and no way for another hook that we write to get this information. This proposes a flag to enable this instead.

### CODE REVIEW

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by szehon-ho** [comment]
Shoot sorry can you open this again when you have the chance?  I still seem not to have permissions.

**Comment by sunchao** [comment]
Oops. I forgot about this. Already approved. I'll merge it once the CI finishes.

**Comment by sunchao** [comment]
Merged to trunk. Thanks @szehon-ho !

**Comment by szehon-ho** [comment]
Thanks a lot @sunchao !

**Pull request merged**
