### PR TITLE
HIVE-25249: Fix TestWorker

### PR DESCRIPTION
**Pull request by deniskuzZ**
### Why are the changes needed?

Flaky test

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

http://ci.hive.apache.org/job/hive-flaky-check/309

### CODE REVIEW

**Comment by klcopp** [comment]
So we expect the visibility id to always be different?

**Comment by deniskuzZ** [comment]
recheck

**Review by klcopp — COMMENTED** [review]
So we expect the visibility id to always be different?

**Comment by deniskuzZ** [comment]
> So we expect the visibility id to always be different?

No, but it could be if tests are executed in parallel. Also, we shouldn't hardcode it anyways but rather extract from the compaction queue.

**Comment by klcopp** [comment]
I remember when I was refactoring query-based compaction, I left out the drop temp table operations. I only realized my mistake because the visibility ids were hard-coded in the tests.
I think if we want these tests to run in parallel we should reset the DB before each test (instead of before each test class), no?

**Comment by deniskuzZ** [comment]
> I remember when I was refactoring query-based compaction, I left out the drop temp table operations. I only realized my mistake because the visibility ids were hard-coded in the tests.
> I think if we want these tests to run in parallel we should reset the DB before each test (instead of before each test class), no?

reverted visibility ids check, there was another issue

**Comment by klcopp** [comment]
> reverted visibility ids check, there was another issue

What is MetastoreConf.ConfVars.TXN_OPENTXN_TIMEOUT=2 doing now? Or what was the issue?

**Comment by deniskuzZ** [comment]
> > reverted visibility ids check, there was another issue
> 
> What is MetastoreConf.ConfVars.TXN_OPENTXN_TIMEOUT=2 doing now? Or what was the issue?

The issue was with txn not being opened/registered within the defined TXN_OPENTXN_TIMEOUT. In that case, txn was cleaned and retried.

**Review by klcopp — APPROVED** [review]

**Pull request merged**
