### PR TITLE
HIVE-27398: SHOW CREATE TABLE doesn't output backticks for CLUSTERED by Col names

### PR DESCRIPTION
**Pull request by rtrivedi12**
### What changes were proposed in this pull request?
Included backticks for CLUSTERED BY column names in output of SHOW TABLE COMMAND.

### Why are the changes needed?
When SHOW CREATE TABLE output is used for table creation, the command fails with ParseException if any bucket column identifier matches reserved keywords.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manually

### CODE REVIEW

**Review by rkirtir — APPROVED** [review]

**Review by ayushtkn — COMMENTED** [review]
you need to add a test as well

**Comment by simhadri-g** [comment]
Can you please check if setting this conf `hive.support.quoted.identifiers ` helps with this issue?
 https://github.com/apache/hive/blob/7cd3107a76d633ef5fae2ffb8ec16953ac968092/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java#LL4702C3-L4713C7

**Comment by rtrivedi12** [comment]
@simhadri-g Thanks for the review! Tested with conf `hive.support.quoted.identifiers` to column and none, it doesn't help. Will add a test for it.

**Comment by rtrivedi12** [comment]
> you need to add a test as well

Added a test for it.

**Comment by rtrivedi12** [comment]
> Please add a test for it. I think this change could cause some issue in different RDBMS.

Added a test for it in show_create_table.q file.

**Comment by aturoczy** [comment]
> > Please add a test for it. I think this change could cause some issue in different RDBMS.
> 
> Added a test for it in show_create_table.q file.

Thank you! Checking

**Review by aturoczy — CHANGES_REQUESTED** [review]
-1 Seems the test are failing, and those test are show table related.

**Review by dengzhhu653 — APPROVED** [review]

**Review by nrg4878 — APPROVED** [review]
Looks good to me. +1

**Pull request merged**
