### PR TITLE
HIVE-28020: Iceberg: Upgrade iceberg version to 1.4.3

### PR DESCRIPTION
**Pull request by simhadri-g**
### What changes were proposed in this pull request?

Upgrade iceberg version to 1.4.3.

### Why are the changes needed?

Iceberg version 1.4.3 has been released -https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.4.3  
Diff: https://github.com/apache/iceberg/compare/apache-iceberg-1.4.2...apache-iceberg-1.4.3 

### Does this PR introduce _any_ user-facing change?

No

### CODE REVIEW

**Review by zhangbutao — COMMENTED** [review]
Can you delete the patched iceberg class as well? Iceberg1.4.3 has fixed this class, we can remove it from hive code.
https://github.com/apache/hive/blob/master/iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/PartitionsTable.java

**Review by aturoczy — CHANGES_REQUESTED** [review]
Fair point @zhangbutao. Let's remove to have a clean part.

**Comment by simhadri-g** [comment]
Thanks @zhangbutao  and @aturoczy  for the review ! 

I have remove [PartitionsTable.java](https://github.com/apache/hive/blob/master/iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/PartitionsTable.java) from patched-iceberg-core.

**Review by zhangbutao — APPROVED** [review]
LGTM

**Pull request merged**
