### PR TITLE
HIVE-26057: Clean useless methods in QueryWrapper

### PR DESCRIPTION
**Pull request by dengzhhu653**

### CODE REVIEW

**Comment by dengzhhu653** [comment]
Hi @pvary, sorry for the poor changes that I made, I want to make some improvements, could you please take a look if have secs? Thank you!

**Comment by pvary** [comment]
> sorry for the poor changes that I made

@dengzhhu653: HIVE-23633 solved a serious issue. That was important to get in.
Any specific reason you think this is solution is much better?

**Comment by dengzhhu653** [comment]
> > sorry for the poor changes that I made
> 
> @dengzhhu653: [HIVE-23633](https://issues.apache.org/jira/browse/HIVE-23633) solved a serious issue. That was important to get in. Any specific reason you think this is solution is much better?

Before this, There are 76 overriden methods in QueryWrapper, most of which take no effect, so after cleaned, there are about 18 methods in QueryWrapper, it can reduce further maintaince of this proxy class.

**Comment by dengzhhu653** [comment]
it removes the useless methods that introduced from [HIVE-23633](https://issues.apache.org/jira/browse/HIVE-23633), no changes to the original code path.

**Comment by pvary** [comment]
> it removes the useless methods that introduced by [HIVE-23633](https://issues.apache.org/jira/browse/HIVE-23633), no changes to the original code path.

Ok, lets get a green test run. You might have to rebase

**Review by pvary — APPROVED** [review]

**Pull request merged**
