### PR TITLE
HIVE-27216: Upgrade postgresql to 42.5.1 from 9.x in branch-3

### PR DESCRIPTION
**Pull request by amanraj2520**
### What changes were proposed in this pull request?

Upgrade postgresql to 42.5.1 from 9.x in branch-3

### Why are the changes needed?

The changes are needed to fix critical CVE's like mentioned here https://mvnrepository.com/artifact/org.postgresql/postgresql

### Does this PR introduce _any_ user-facing change?

No this just upgrades the postgres version
### How was this patch tested?

Jenkins build

### CODE REVIEW

**Comment by amanraj2520** [comment]
@zabetak Can you please review this. I have used a ticket raised by you in OSS master #HIVE-23965 but I did not cherry pick the entire ticket since there were a lot of merge conflicts because of the tests. The remaining tickets I have cherry-picked completely.

**Comment by amanraj2520** [comment]
@vihangk1 Can you also review this

**Comment by amanraj2520** [comment]
@zabetak @abstractdog @vihangk1 Can you please review this. The only part I am skeptical of is the partial cherry pick of #HIVE-23965. Need your suggestions on that since there were a lot of merge conflicts if I cherry pick the entire ticket.

**Comment by vihangk1** [comment]
I don't think we need to backport the entire HIVE-23965 since it is pretty big and not intended to upgrade the postgres version. The partial backport makes sense to me. +1

I will wait for @zabetak or others to give them a chance to review as well. If we don't hear back from them in the next day or two, I can merge this.

**Review by guptanikhil007 — APPROVED** [review]

**Comment by amanraj2520** [comment]
@zabetak Can you review this once.

**Comment by amanraj2520** [comment]
@vihangk1 We can merge this now.

**Comment by vihangk1** [comment]
Merged. Thanks @amanraj2520

**Pull request merged**
