### PR TITLE
HIVE-15191: Fix typo in conf/hive-env.sh.template

### PR DESCRIPTION
**Pull request by dongjinleekr**
'Libraries', not 'ibraries'.

### CODE REVIEW

**Comment by winningsix** [comment]
Thanks @dongjinleekr  for the contribution. Can you help create a ticket at [Jira page](https://issues.apache.org/jira/browse/HIVE/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel)?

**Comment by dongjinleekr** [comment]
No problem - this Pull Request solves [HIVE-15191](https://issues.apache.org/jira/browse/HIVE-15191).

**Comment by winningsix** [comment]
Thank you! Can you please update the title to "HIVE-15191: Fix typo in conf/hive-env.sh.template"? And attach file following the rule in [WIKI](https://cwiki.apache.org/confluence/display/Hive/HowToContribute#HowToContribute-CreatingaPatch) to trigger precommit test.

**Comment by dongjinleekr** [comment]
Thanks for your kind guidance. I just submitted the patch following the guide.

**Pull request closed without merging**
