### PR TITLE
HIVE-26865 : Fix TestSQL11ReservedKeyWordsNegative test in branch-3

### PR DESCRIPTION
**Pull request by amanraj2520**
HIVE-26865:  Tests are failing due to this commit - https://issues.apache.org/jira/browse/HIVE-21293. So reverting it for now. After fixing these tests also the branch-3 won't turn green. So to compare whether they have been fixed or not we can refer this http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3850/1/tests/ pipeline where they were failing in branch-3.

I am open to discuss whether there is a fix for this or is it okay to revert this commit for the test to go through.

### CODE REVIEW

**Comment by amanraj2520** [comment]
@abstractdog Kindly review this and we can discuss the fix or revert this accordingly.

**Comment by abstractdog** [comment]
please let's not revert HIVE-21923, it has fixed an issue and refactored an awful test class
if we're sure that it cause the exception:
```
In TestSQL11ReservedKeyWordsNegative, this is also failing. Kindly have a look :
java.lang.NullPointerException: Conf non-local session path expected to be non-null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
at org.apache.hadoop.hive.ql.session.SessionState.getHDFSSessionPath(SessionState.java:822)
at org.apache.hadoop.hive.ql.Context.<init>(Context.java:312)
at org.apache.hadoop.hive.ql.Context.<init>(Context.java:298)
at org.apache.hadoop.hive.ql.parse.TestSQL11ReservedKeyWordsNegative.parse(TestSQL11ReservedKeyWordsNegative.java:52)
at org.apache.hadoop.hive.ql.parse.TestSQL11ReservedKeyWordsNegative.access$000(TestSQL11ReservedKeyWordsNegative.java:40)
at org.apache.hadoop.hive.ql.parse.TestSQL11ReservedKeyWordsNegative$TestSQL11ReservedKeyWordsNegativeParametrized.testNegative(TestSQL11ReservedKeyWordsNegative.java:104)
```
let's fix it, let me take a look

**Comment by abstractdog** [comment]
@amanraj2520 : the only thing that failed on my side was REAL keyword, after I removed it, test passed:
https://github.com/abstractdog/hive/commit/09471bae5e2ad4117e7f183753c9ac3155cc829b

were you able to reproduce the checkNotNull error?

**Comment by amanraj2520** [comment]
Hi @abstractdog Yes I also could not reproduce the checkNotNull error in my local. I only got the REAL issue you talked about. Let me try reproducing it again. But you can see the Jenkins pipeline, for the error. When I reverted it back, the Jenkins pipeline had also passed. But still let me repro this error

**Comment by abstractdog** [comment]
thanks @amanraj2520, let me investigate too, let's fix it

**Comment by abstractdog** [comment]
fixed in https://github.com/apache/hive/pull/3869

**Comment by amanraj2520** [comment]
Thanks a lot @abstractdog for taking care of this fix and merging it.

**Pull request closed without merging**
