### PR TITLE
HIVE-28017: Add generated protobuf code.

### PR DESCRIPTION
**Pull request by ayushtkn**
### What changes were proposed in this pull request?

Add the generated protobuf code

### Why are the changes needed?

Since protobuf is already upgraded

### Does this PR introduce _any_ user-facing change?

Should be NO, Protobuf is compatible over the wire

### Is the change a dependency upgrade?

It is a by product of a dependency upgrade

### How was this patch tested?

Jenkins Run

### CODE REVIEW

**Review by aturoczy — COMMENTED** [review]
@ayushtkn Were these files missed? How it just came recently?

**Comment by ayushtkn** [comment]
Was a miss during: https://github.com/apache/hive/pull/3814

**Comment by aturoczy** [comment]
> Member

Ack

**Review by aturoczy — APPROVED** [review]

**Review by zhangbutao — APPROVED** [review]
LGTM

BTW, should we enforce check on protobuf & thrift when mvn building? For example:
`mvn clean install -Pthriftif -Pprotobuf ...`

**Review by dengzhhu653 — APPROVED** [review]

**Comment by ayushtkn** [comment]
> BTW, should we enforce check on protobuf & thrift when mvn building? For example:
mvn clean install -Pthriftif -Pprotobuf ...

Yep, I created https://issues.apache.org/jira/browse/HIVE-27940, but didn't follow later, but yes we should do this

**Pull request merged**
