### PR TITLE
HIVE-24559: Fix some spelling issues

### PR DESCRIPTION
**Pull request by rickyma**
### What changes were proposed in this pull request?

This pull request fixes some minor typos.

### Why are the changes needed?

This pull request fixes some minor typos.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No need to be tested.

### CODE REVIEW

**Review by miklosgergely — APPROVED** [review]

**Comment by rickyma** [comment]
I force pushed to fix more spelling mistakes.

**Comment by rickyma** [comment]
Just some typo fixes in some comments, there is no need to pass all the checks. Can anyone please merge this?

**Comment by rickyma** [comment]
Hey @vihangk1, could you please merge this? Just some typo issues~~ Thanks a lot.

**Comment by vihangk1** [comment]
The patch does not have any code changes. Merging the patch. Thanks @rickyma for the patch.

**Review by vihangk1 — APPROVED** [review]

**Pull request merged**
