### PR TITLE
HIVE-27966: Disable flaky testFetchResultsOfLogWithOrientation

### PR DESCRIPTION
**Pull request by wecharyu**
### What changes were proposed in this pull request?
org.apache.hive.service.cli.operation.TestOperationLoggingAPIWithMr#testFetchResultsOfLogWithOrientation test is flaky and can easily result into CI failed.

Here are some affected pipelines:
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4959/3/tests

http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4755/15/tests

http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4966/1/tests

http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4517/25/tests

### Why are the changes needed?
Disable unstable test.

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
Pass existing tests.

### CODE REVIEW

**Review by akshat0395 — COMMENTED** [review]
@wecharyu Thanks for checking this out, can you attach the flaky test job link as well in case you ran it. Otherwise lets do a flaky check before disabling the test.
http://ci.hive.apache.org/job/hive-flaky-check/

**Comment by wecharyu** [comment]
@ayushtkn has ran this flaky test, the result is as follows:
http://ci.hive.apache.org/job/hive-flaky-check/780/testReport/junit/org.apache.hive.service.cli.operation/TestOperationLoggingAPIWithMr/testFetchResultsOfLogWithOrientation_3/
cc: @akshat0395

**Comment by akshat0395** [comment]
Thanks for sharing @wecharyu, LGTM +1

**Review by akshat0395 — APPROVED** [review]

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
