### PR TITLE
HIVE-27331: Iceberg: Rows are not deleted from table when execution mode is vectorized llap.

### PR DESCRIPTION
**Pull request by kasakrisz**
### What changes were proposed in this pull request?
Disable Llap read of TS on Iceberg tables when virtual columns are projected in vectorized mode.

### Why are the changes needed?
The Iceberg specific virtual column `ROW_POSITION` can not be populated. In non-llap mode the row position is provided by the Orc reader. However in case of llap mode the read is driven by `LlapRecordReader` which does not provide the row positions.

### Does this PR introduce _any_ user-facing change?
Yes. Fix data corruption. Deleted rows are not appear in the result of a query.

### How was this patch tested?
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergLlapLocalCliDriver -Dqfile=llap_iceberg_read_orc.q -pl itests/qtest-iceberg -Pitests,iceberg -Drat.skip
```

### CODE REVIEW

**Review by ayushtkn — CHANGES_REQUESTED** [review]
Have we started duping tickets? rather than review comments? This indeed is a very cheap activity.

**Comment by deniskuzZ** [comment]
> Have we started duping tickets? rather than review comments? This indeed is a very cheap activity.

@ayushtkn, I think that was done just do verify if a simpler approach could work before commenting out in the original PR. That is the only way to run all the tests.

**Comment by ayushtkn** [comment]
@deniskuzZ this is a pathetic defence and @kasakrisz can take that, but that is indeed cheap. btw we have dowsntream ways to run tests as well. Apache resources aren't meant to be experimented, they are limited....

**Review by deniskuzZ — APPROVED** [review]
LGTM +1
@ayushtkn, sorry you took that the wrong way, that wasn't intended.

**Review by ayushtkn — CHANGES_REQUESTED** [review]
Yahh for some people like @kasakrisz ethics doesn't mater. but a side note lets not do it with new contributors, stealing from them won't be good and making metrics against them won't be great.

**Comment by ayushtkn** [comment]
I think we wait for sometime for others to take a look after a binding vote? Reverting....

**Comment by aturoczy** [comment]
Guys I understand the frustration, but we are belong to the same community, and we have the same goal to make this product better. Friction, miss understanding and so many things could happen, but let's focus on our goal. There could be and will be in conflict in any community, but even in our heart is full or feeling - even it is right or not - we have to be patient. 

The whole ASF is based on this principals, we should not break these rules - other rules also no need to break-, even written or not written.  I just want to remind, the second point in ASF Code

_Be empathetic, welcoming, friendly, and patient. We work together to resolve conflicts, assume good intentions, and do our best to act in an empathetic fashion. We may all experience some frustration from time to time, but we do not allow frustration to result in a personal attack. A community where people feel uncomfortable or threatened is not a productive one. We should be respectful when dealing with other community members as well as with people outside our community._

I think everybody told his point of view, now we should close this, and in the future we have to avoid similar issues. I think all of us are learn for this issue.  All of you are great and respectful talents that made this community unique and powerful. 

-Attila

**Pull request merged**
