### PR TITLE
HIVE-27468: Restore original license in PriorityBlockingDeque

### PR DESCRIPTION
**Pull request by zabetak**
### What changes were proposed in this pull request?
1. Remove ASF header;
2. Add RAT check exclusion;
3. Restore original copyright in the file;

### Why are the changes needed?
Comply to ASF guidelines concerning 3-party work (https://www.apache.org/legal/src-headers.html#3party). We shouldn't relicense 3rd-party code.

### Does this PR introduce _any_ user-facing change?
No
### Is the change a dependency upgrade?
No

### How was this patch tested?
Not needed

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]
Hive 4 beta is coming :)

**Review by ayushtkn — COMMENTED** [review]
is PriorityBlockingDeque an exact copy? if yes, why can't we directly use it? if not and we have changed, don't we need our licence? We can't release our code under another licence/copyright?

**Comment by zabetak** [comment]
@ayushtkn The class is an exact copy minus whitespace and formatting changes. I assume that the artifacts from infomancers-collections were not available in a maven repository thus copying the class was the fastest way to advance when the class was copied to Hive.

The https://www.apache.org/legal/src-headers.html#3party section outlines how to handle such cases in terms of licensing and copyright; this is not "our" code.

**Review by ayushtkn — APPROVED** [review]
Thanx @zabetak, Makes sense.
Changes LGTM

**Pull request closed without merging**
