### PR TITLE
HIVE-25723: Found some typos

### PR DESCRIPTION
**Pull request by fengpan0403**
Fix some typos in the program.

### CODE REVIEW

**Comment by kgyrtkirk** [comment]
hey @fengpan0403 !
thank you for your interest in the project, welcome aboard !
for submitting changes - you will need a jira ticket as well; you could find pointers in this document:
https://cwiki.apache.org/confluence/display/Hive/HowToContribute#HowToContribute-ContributingYourWork
by the way @jsoref have been also working recently on fixing typos in the project; I think you might be able to help him :)
https://issues.apache.org/jira/browse/HIVE-24390

**Comment by fengpan0403** [comment]
> hey @fengpan0403 ! thank you for your interest in the project, welcome aboard ! for submitting changes - you will need a jira ticket as well; you could find pointers in this document: https://cwiki.apache.org/confluence/display/Hive/HowToContribute#HowToContribute-ContributingYourWork by the way @jsoref have been also working recently on fixing typos in the project; I think you might be able to help him :) https://issues.apache.org/jira/browse/HIVE-24390

Thank you for the help.

**Comment by jsoref** [comment]
Yeah, I have a series of fixes for `a`..`z`, but we're landing them in small digestible chunks.

**Comment by jsoref** [comment]
atm, the series is here: https://github.com/apache/hive/commits/37c83c580e11cc23e4342f23dd2af56a5a6f0a1a and af536fabacb2cdb41280c67e3c3a66d6b474db13 covers your typo.

The grammatical error is unlikely to be in my series -- I try not to mix other fixes w/ typo fixes, especially when my series get on the long side.

**Comment by jsoref** [comment]
Sigh

**Comment by jsoref** [comment]
Sigh

**Comment by jsoref** [comment]
Sigh

**Review by ayushtkn — COMMENTED** [review]
Change LGTM. But I am not sure if fixing one-one word is a good choice

**Comment by jsoref** [comment]
Sigh

**Comment by jsoref** [comment]
Sigh

**Pull request closed without merging**
