### PR TITLE
HIVE-27925: HiveConf: unify ConfVars enum and use underscore for better readability

### PR DESCRIPTION
**Pull request by kokila-19**
### What changes were proposed in this pull request?
HiveConf: unify ConfVars enum and use underscore for better readability

### Why are the changes needed?
Better readability

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
Build and Unit tests.

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]
+1 it is just a rename refactor which is nice

+1 for @abstractdog for this detailed describtion:
When I read something like "[BASICSTATSTASKSMAXTHREADSFACTOR](https://github.com/apache/hive/blob/70f34e27349dccf5fabbfc6c63e63c7be0785360/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java#L753)" I feel someone in the world laughs out loud thinking of me struggling. I can read it, but I hate it  imagine what if we have vars like [HIVE_MATERIALIZED_VIEW_ENABLE_AUTO_REWRITING_SUBQUERY_SQL](https://github.com/apache/hive/blob/70f34e27349dccf5fabbfc6c63e63c7be0785360/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java#L1921) without underscores...okay, let me help, it is: HIVEMATERIALIZEDVIEWENABLEAUTOREWRITINGSUBQUERYSQL

Made my day :D 

btw: This is a real and meaningful Hungarian word: megszentségteleníthetetlenségeskedéseitekért (same as our enums :) useless)

**Comment by aturoczy** [comment]
@ayushtkn @abstractdog @deniskuzZ Could you please check this PR as well. Many files are touched but it is a simple rename.

**Review by abstractdog — APPROVED** [review]
+1

**Comment by dom93dd** [comment]
This change seems to break the compatibility with apache.iceberg.hive dependency:

E.g. here:
https://github.com/apache/iceberg/blob/6f0d9dd47c693dc2aa13a38fab3d56473d925563/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java#L95

We have been using the HiveCatalog of apache.iceberg prior the newly introduced changes of 4.0.0 Alpha 1. With this change, this isn't possible anymore. Furthermore, if I switch to apache.hive HiveCatalog then the necessary included shading of fasterxml breaks everything. Because the JsonUtil class in apache.iceberg includes the fasterxml dependency without the relocated path. Anyone an idea what to do here?

Here is my feature request for apache.iceberg to introduce the ENV changes there too: https://github.com/apache/iceberg/issues/10254

Here is my jira issue where I specified the current problem I have with the shading:
https://issues.apache.org/jira/browse/HIVE-28229

Thanks!

**Pull request merged**
