### PR TITLE
HIVE-27999: Upgrade to Java 17 to run sonar analysis

### PR DESCRIPTION
**Pull request by wecharyu**
### What changes were proposed in this pull request?
Upgrade to java 17 in CI to run sonar analysis.

### Why are the changes needed?
To make CI pass.

### Does this PR introduce _any_ user-facing change?
No.

### Is the change a dependency upgrade?
No.

### How was this patch tested?
Pass CI.

### CODE REVIEW

**Comment by zabetak** [comment]
@wecharyu It seems that we need also changes in https://github.com/kgyrtkirk/hive-dev-box to fix this issue. Are you planning to raise a PR there as well?

**Comment by wecharyu** [comment]
Yes, I'm trying to add jdk 17 by following this path https://github.com/kgyrtkirk/hive-dev-box/commit/4de03758bd750291e0973918668adca7f0aa0a89#diff-407e75354c3f4d4ba0290f1a41a629b943ad51520a7ef16c898282e036333c85.

**Comment by zhangbutao** [comment]
Looks like the new CI have failed on the sonar check stage. http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4999/4/pipeline/601

**Review by aturoczy — APPROVED** [review]

**Review by zabetak — APPROVED** [review]
LGTM, will merge shortly!

**Comment by zhangbutao** [comment]
It looks like sonar still failed  after upgrading jdk. http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-5009/5/pipeline/414

`[2024-01-17T13:06:33.547Z] [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project hive: Error while running Node.js. A supported version of Node.js is required for running the analysis of JS in HTML files. Please make sure a supported version of Node.js is available in the PATH. Alternatively, you can exclude JS in HTML files from your analysis using the 'sonar.exclusions' configuration property. See the docs for configuring the analysis environment: https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/languages/javascript-typescript-css/: Error when running: 'node -v'. Is Node.js available during analysis?: Cannot run program "node": error=2, No such file or directory -> [Help 1]`

**Comment by SourabhBadhya** [comment]
I think this patch also introduced these 3 new test failures related to timestamp in the current master branch -
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/master/2034/tests

cc @wecharyu @zabetak

**Comment by wecharyu** [comment]
> Error when running: 'node -v'. Is Node.js available during analysis?: Cannot run program "node": error=2, No such file or directory

@zhangbutao This error also exists in the original case, so I ignored it. Currently it would fail sometimes, we may need a new path to fix it.

> I think this patch also introduced these 3 new test failures related to timestamp in the current master branch -

@SourabhBadhya It should be caused by the jdk bug,  the original jdk version is **1.8.0_262-b19**, and the new jdk version become **1.8.0_392-b08**. It could be reproduced in my machine for the new jdk, so I will test and update to the right jdk version.

**Comment by abstractdog** [comment]
```
wecharyu/hive-dev-box:executor
```
following up, haven't we got an apache-like docker repo to store our images?

**Comment by zabetak** [comment]
@abstractdog I think that before pushing the hive-dev-box images to our official apache docker repo we have to be sure that the hive-dev-box source code is apache compliant and bring the latter under the apache namespace.

**Comment by zabetak** [comment]
The relevant discussion is here: https://lists.apache.org/thread/3z6f0srnts3n2m36yh5573lhyd5khyp2

**Comment by zabetak** [comment]
@kgyrtkirk I plead guilty but I had good intentions. I was overconfident that the change would only affect Sonar which was anyways broken for days so wanted to quickly unblock all the others hitting that problem.

**Comment by zhangbutao** [comment]
I think CI green is back. PR-4981 and PR5001 are green again.
 http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/activity

@wecharyu maybe have fixed the docker image.

**Pull request closed without merging**
