### PR TITLE
HIVE-27645: Refactor assertFalse(equals()) using assertNotEquals & @Test(excepted) using assertThrows

### PR DESCRIPTION
**Pull request by Taher-Ghaleb**
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice.

The first smell is when inappropriate assertions are used, while there exist better alternatives. For example, in [TestJdbcDriver2.java](https://github.com/apache/hive/commit/04a9ddaa91c549a3c3041a45ab9871c4bc70f76d#diff-71a2f75f4a5dc07d285255a36e87deaab739ca7c486c2b1ddc3930f69f46783d), I refactored `assertFalse(queryId.equals(queryId1));` with `assertNotEquals(queryId, queryId1);`.

The second smell is when exception handling can alternatively be implemented using assertion rather than annotation. For example, in [TestJdbcDriver2.java](https://github.com/apache/hive/commit/04a9ddaa91c549a3c3041a45ab9871c4bc70f76d#diff-71a2f75f4a5dc07d285255a36e87deaab739ca7c486c2b1ddc3930f69f46783d), I used `assertThrows(HiveSQLException.class, () -> {...});` instead of `@Test(expected = HiveSQLException.class)`.

While there could be several cases like this, we aim in this pull request to get your feedback on these particular test smells and their refactorings. Thanks in advance for your input.

### CODE REVIEW

**Comment by ayushtkn** [comment]
Sounds good, but you need to create a jira first, and then prefix the jira id in your PR title.
https://cwiki.apache.org/confluence/display/Hive/HowToContribute#HowToContribute-JIRA

**Comment by Taher-Ghaleb** [comment]
Thanks, @ayushtkn. I have submitted a form for account creation and will create a Jira report once the account is approved.

I would also like to get your input on these changes, please. In your opinion, why is `assertFalse(equals())` is still used instead of `assertNotEquals`, or even `assertTrue(equals())` instead of `assertEquals`? Typically, `assertNotEquals` improves the readability of a test case and makes equality checks more explicit and intuitive, unlike `assertFalse` or `assertTrue` combined with `equals`, which indirectly checks if two objects are not equal. Also, `assertNotEquals` typically provides more informative failure messages, as it can include details about the expected and actual values if the assertion fails, making it easier to diagnose and fix the issue.

**Comment by Taher-Ghaleb** [comment]
[Jira issue report](https://issues.apache.org/jira/browse/HIVE-27645) is created and its id is prefixing the PR title. Thanks.

**Comment by ayushtkn** [comment]
Thanx @Taher-Ghaleb, I think these may be just old codes, or lack of awareness b/w the contributors and reviewers then... Though Test(Expected) ain't considered a bad practice

**Comment by ayushtkn** [comment]
the only failure is the oracle docker init, known flaky, merging

**Pull request merged**
