### PR TITLE
HIVE-27368: Vectorization: ArrayIndexOutOfBoundsException when map key vector has repeating values

### PR DESCRIPTION
**Pull request by maswin**
Addendum to this PR: https://github.com/apache/hive/pull/3492

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
is there any scope to extend a test for this case?
btw. you should create a new ticket for this rather than an addendum, HIVE-26447 seems to be released, AFAIK addendums only till a ticket isn't released

**Comment by aturoczy** [comment]
> is there any scope to extend a test for this case? btw. you should create a new ticket for this rather than an addendum, [HIVE-26447](https://issues.apache.org/jira/browse/HIVE-26447) seems to be released, AFAIK addendums only till a ticket isn't released

[This is a follow-up on this comment](https://github.com/apache/hive/pull/3492#discussion_r1200967679)

**Comment by maswin** [comment]
> is there any scope to extend a test for this case? btw. you should create a new ticket for this rather than an addendum, [HIVE-26447](https://issues.apache.org/jira/browse/HIVE-26447) seems to be released, AFAIK addendums only till a ticket isn't released

I can change the JIRA title if required. 
Internally we have an ORC file in which this issue happens and we tested the query with the fix and it works fine. 
For the issue to happen the keyStart array needs to have some garbage value, something other than 0 (probably due to array reuse) so that keyStart[keyOffset] returns some value other than 0. 
When I test with small dataset and a simple query, since all values in the array are initialized to 0, keyStart[keyOffset] always returns 0 which is the expected start. Not sure how to add a simple test case.

**Comment by ayushtkn** [comment]
Good to create a new ticket, the original is released in alpha-2 already

rest should be ok then

**Comment by maswin** [comment]
> Good to create a new ticket, the original is released in alpha-2 already
> 
> rest should be ok then

Done. Changed the JIRA,PR and commit message.

**Review by ayushtkn — APPROVED** [review]
LGTM.
I forgot to merge this, will merge this tomorrow first thing!!!

**Pull request merged**
