### PR TITLE
HIVE-28204: Remove some HMS obsolete scripts

### PR DESCRIPTION
**Pull request by dengzhhu653**

### CODE REVIEW

**Comment by dengzhhu653** [comment]
Under standalone-metastore/metastore-server/src/main/sql, there are scripts for 1.2.0, mainly for TestSchemaToolForMetastore to test the upgrade from 1.2.0.

**Comment by InvisibleProgrammer** [comment]
Hi, is that some legacy way how we handled the metastore upgrade scripts at an old Hive version?

**Comment by dengzhhu653** [comment]
> Hi, is that some legacy way how we handled the metastore upgrade scripts at an old Hive version?

The upgrade story is almost the same, while these deleted scripts are for Hive version <= 2.3(including the upgrade scripts).
For the scripts target at 1.x or 0.x, I think we can remove them safety.
For the scripts target at 2.x, the branch 2.x already contains the scripts for initializing, we don't need to keep them on the 4.x branch, 
the scripts under https://github.com/apache/hive/tree/master/standalone-metastore/metastore-server/src/main/sql/postgres  can upgrade to the latest version from any releases that newer than 1.2.0, so I remove the upgrade scripts from the directories as well.

**Comment by deniskuzZ** [comment]
> > Hi, is that some legacy way how we handled the metastore upgrade scripts at an old Hive version?
> 
> The upgrade story is almost the same, while these deleted scripts are for Hive version <= 2.3(including the upgrade scripts). For the scripts target at 1.x or 0.x, I think we can remove them safety. For the scripts target at 2.x, the branch 2.x already contains the scripts for initializing, we don't need to keep them on the 4.x branch, the scripts under https://github.com/apache/hive/tree/master/standalone-metastore/metastore-server/src/main/sql/postgres can upgrade to the latest version from any releases that newer than 1.2.0, so I remove the upgrade scripts from the directories as well.

what if customer decided to upgrade from 2.0 to 4.0, won't we miss some of the upgrade script?

**Comment by dengzhhu653** [comment]
> > > Hi, is that some legacy way how we handled the metastore upgrade scripts at an old Hive version?
> > 
> > 
> > The upgrade story is almost the same, while these deleted scripts are for Hive version <= 2.3(including the upgrade scripts). For the scripts target at 1.x or 0.x, I think we can remove them safety. For the scripts target at 2.x, the branch 2.x already contains the scripts for initializing, we don't need to keep them on the 4.x branch, the scripts under https://github.com/apache/hive/tree/master/standalone-metastore/metastore-server/src/main/sql/postgres can upgrade to the latest version from any releases that newer than 1.2.0, so I remove the upgrade scripts from the directories as well.
> 
> what if customer decided to upgrade from 2.0 to 4.0, won't we miss some of the upgrade script?

https://github.com/apache/hive/tree/master/standalone-metastore/metastore-server/src/main/sql/postgres this directory contains the scripts for upgrading to 4.0, 

https://github.com/apache/hive/blob/master/standalone-metastore/metastore-server/src/main/sql/postgres/upgrade.order.postgres

**Comment by dengzhhu653** [comment]
Hello @nrg4878, @saihemanth-cloudera cloud you please take a look as well if have cycles?

**Comment by nrg4878** [comment]
@dengzhhu653 Given there is a RC for 2.3.10 release, should we retain the upgrade scripts from 2.3 to the latest version?

**Comment by dengzhhu653** [comment]
> @dengzhhu653 Given there is a RC for 2.3.10 release, should we retain the upgrade scripts from 2.3 to the latest version?
This https://github.com/apache/hive/tree/master/standalone-metastore/metastore-server/src/main/sql/postgres directory contains the scripts for upgrading to 4.0 from 2.3 or 1.2. The PR removes the scripts in metastore module

**Review by henrib — COMMENTED** [review]
Non binding, but LGTM :-)

**Comment by dengzhhu653** [comment]
@kuczoram would you please take a look if have secs? Thank you in advance!

**Review by saihemanth-cloudera — APPROVED** [review]
LGTM +1

**Pull request merged**
