### PR TITLE
HIVE-27845:Upgrade protobuf to 3.24.4 to fix CVEs

### PR DESCRIPTION
**Pull request by tanishq-chugh**
What changes were proposed in this pull request?
In order to resolve the CVEs caused by 3.21.7 version of protobuf-java, we are trying to upgrade it to 3.24.4 version.

Why are the changes needed?
We need to update the protobuf-java version in hive's pom.xml to resolve the CVEs.

Does this PR introduce any user-facing change?
No

Is the change a dependency upgrade?
Yes

How was this patch tested?
Manual tests.
After updating the protobuf-java version, we build the hive project again.
After manually testeing some DDL and SQL commands, hive is working as expected.

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]

**Review by SourabhBadhya — APPROVED** [review]
LGTM +1 (pending tests)

**Comment by Aggarwal-Raghav** [comment]
Thanks for pursuing this @tanishq-chugh, but I see you closed the same PR earlier https://github.com/apache/hive/pull/5065 and created this for same branch. Any specific reason for it?
In my Opinion, it's not correct as it makes it difficult to track the comment history for future reference.

**Comment by ayushtkn** [comment]
There are objections by folks for having a new PR,
@tanishq-chugh / @Aggarwal-Raghav you guys need to negotiate & reach an agreement

the dependency tree isn't attached either as per the PR template: https://github.com/apache/hive/blob/master/.github/pull_request_template.md?plain=1#L40-L44

**Comment by tanishq-chugh** [comment]
> Thanks for pursuing this @tanishq-chugh, but I see you closed the same PR earlier #5065 and created this for same branch. Any specific reason for it? In my Opinion, it's not correct as it makes it difficult to track the comment history for future reference.

@Aggarwal-Raghav it was my first PR and since a lot of changes were required, i thought to raise a new PR. But i realised that its not a good practise, and will keep that in mind up ahead.

**Comment by Aggarwal-Raghav** [comment]
Sure, no worries @tanishq-chugh 👍🏻.

**Comment by tanishq-chugh** [comment]
[dependency_tree.txt](https://github.com/apache/hive/files/14357632/dependency_tree.txt)

**Comment by tanishq-chugh** [comment]
@pgaref Can you please review this?

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
