### PR TITLE
HIVE-24849 CreateTableDesc() calls isEmpty() after isExternal(); optimize Table.…

### PR DESCRIPTION
**Pull request by glapark**
…isEmpty()

### What changes were proposed in this pull request?
https://issues.apache.org/jira/browse/HIVE-24849
1. CreateTableDesc() calls isEmpty() after isExternal().
2. optimize Table.isEmpty() by checking individual files rather than collecting all files only to check their size.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manually tested in a local cluster with MinIO simulating S3.

### CODE REVIEW

**Review by steveloughran — COMMENTED** [review]
LGTM

In hadoop-3.3.1; both S3A and ABFS's listStatusIterator() prefetch/page results. If you want to stop fetching before finishing, do call Closeable.close() *if the iterator supports Closeable. See: https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/functional/RemoteIterators.java#L262
You get the IOStats in listStatusIterator for S3A. If you log the iterator at debug, we will print out stats like 

```
2021-08-05 16:33:09,230 [shutdown-hook-0] INFO  statistics.IOStatisticsLogging (IOStatisticsLogging.java:logIOStatisticsAtLevel(269)) - IOStatistics: counters=((audit_request_execution=24)
(audit_span_creation=2)
(object_continue_list_request=23)
(object_list_request=1)
(op_list_files=1)
(store_io_request=29));

gauges=();

minimums=((object_continue_list_request.min=64)
(object_list_request.min=3652)
(op_list_files.min=4535));

maximums=((object_continue_list_request.max=709)
(object_list_request.max=3652)
(op_list_files.max=4535));

means=((object_continue_list_request.mean=(samples=23, sum=9187, mean=399.4348))
(object_list_request.mean=(samples=1, sum=3652, mean=3652.0000))
(op_list_files.mean=(samples=1, sum=4535, mean=4535.0000)));

```

This is a real run of a deep tree with 23K files. Time for a cleanup there.

**Comment by mr3project** [comment]
Okay, I added a note saying that close() should be called in Hadoop 3.3.1+.

**Comment by steveloughran** [comment]
(cut a bit of superfluousness from my comment; part of an email which combined the details with some compat statement across versions)

**Comment by steveloughran** [comment]
>  Okay, I added a note saying that close() should be called in Hadoop 3.3.1+.

you can call close to any version if the stream implements Closeable()

**Review by kgyrtkirk — APPROVED** [review]

**Pull request merged**
