### PR TITLE
HIVE-27670: Failed to build the image locally on Apple silicon

### PR DESCRIPTION
**Pull request by dengzhhu653**
### Does this PR introduce _any_ user-facing change?
Introduce an env variable SCHEMA_COMMAND for Hive 3, usage:
docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --env SCHEMA_COMMAND= upgradeSchema  --name hive3 apache/hive:3.1.3

### Is the change a dependency upgrade?
No

### How was this patch tested?
Build the image and run the container successfully on my M1 laptop.

### CODE REVIEW

**Comment by zratkai** [comment]
I run into the same issue with missing \ in build.sh. So LGTM.

**Review by ayushtkn — COMMENTED** [review]
Thanx @dengzhhu653 I think we should mention the ``SCHEMA_COMMAND`` as part of the docker readme as well here:
https://github.com/apache/hive/blob/master/packaging/src/docker/README.md

We do have a quick start here as well:
https://github.com/apache/hive-site/blob/main/content/Developement/quickStart.md

I can update the later once this is merged

**Comment by dengzhhu653** [comment]
> Thanx @dengzhhu653 I think we should mention the `SCHEMA_COMMAND` as part of the docker readme as well here: https://github.com/apache/hive/blob/master/packaging/src/docker/README.md
> 
> We do have a quick start here as well: https://github.com/apache/hive-site/blob/main/content/Developement/quickStart.md
> 
> I can update that later once this is merged

Done

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by bkyryliuk** [comment]
I am still getting 
```
+ : derby
+ SKIP_SCHEMA_INIT=false
+ export HIVE_CONF_DIR=/opt/hive/conf
+ HIVE_CONF_DIR=/opt/hive/conf
+ '[' -d '' ']'
+ export 'HADOOP_CLIENT_OPTS= -Xmx1G '
+ HADOOP_CLIENT_OPTS=' -Xmx1G '
+ [[ false == \f\a\l\s\e ]]
+ initialize_hive
+ COMMAND=-initOrUpgradeSchema
++ echo 3.1.3
++ cut -d . -f1
+ '[' 3 -lt 4 ']'
+ COMMAND=-upgradeSchema
+ /opt/hive/bin/schematool -dbType derby -upgradeSchema
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
	at org.apache.hadoop.mapred.JobConf.setJar(JobConf.java:518)
	at org.apache.hadoop.mapred.JobConf.setJarByClass(JobConf.java:536)
	at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:430)
	at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5144)
	at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5107)
	at org.apache.hive.beeline.HiveSchemaTool.<init>(HiveSchemaTool.java:96)
	at org.apache.hive.beeline.HiveSchemaTool.main(HiveSchemaTool.java:1473)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
+ '[' 1 -eq 0 ']'
+ echo 'Schema initialization failed!'
```

When running 
```
docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --env SCHEMA_COMMAND= upgradeSchema --name hive3 apache/hive:3.1.3
```
Are there any other settings / gotchas needed to run hive:3.1.3 in docker?

**Comment by dengzhhu653** [comment]
> I am still getting
> 
> ```
> + : derby
> + SKIP_SCHEMA_INIT=false
> + export HIVE_CONF_DIR=/opt/hive/conf
> + HIVE_CONF_DIR=/opt/hive/conf
> + '[' -d '' ']'
> + export 'HADOOP_CLIENT_OPTS= -Xmx1G '
> + HADOOP_CLIENT_OPTS=' -Xmx1G '
> + [[ false == \f\a\l\s\e ]]
> + initialize_hive
> + COMMAND=-initOrUpgradeSchema
> ++ echo 3.1.3
> ++ cut -d . -f1
> + '[' 3 -lt 4 ']'
> + COMMAND=-upgradeSchema
> + /opt/hive/bin/schematool -dbType derby -upgradeSchema
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
> Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
> 	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
> 	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
> 	at org.apache.hadoop.mapred.JobConf.setJar(JobConf.java:518)
> 	at org.apache.hadoop.mapred.JobConf.setJarByClass(JobConf.java:536)
> 	at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:430)
> 	at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5144)
> 	at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5107)
> 	at org.apache.hive.beeline.HiveSchemaTool.<init>(HiveSchemaTool.java:96)
> 	at org.apache.hive.beeline.HiveSchemaTool.main(HiveSchemaTool.java:1473)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
> 	at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
> + '[' 1 -eq 0 ']'
> + echo 'Schema initialization failed!'
> ```
> 
> When running
> 
> ```
> docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --env SCHEMA_COMMAND= upgradeSchema --name hive3 apache/hive:3.1.3
> ```
> 
> Are there any other settings / gotchas needed to run hive:3.1.3 in docker?

I guess there are different versions of guava in HMS classpath, what's the Hadoop version of the Docker? the default hadoop version in Hive 3.1.3 is 3.1.0.

**Comment by bkyryliuk** [comment]
I realized that there is a need to export env variable with hadoop version, not only pass it to the build script. However it is still not working :( Here are the repro steps:

```
export HADOOP_VERSION=3.1.0
export HIVE_VERSION=3.1.3
export TEZ_VERSION=0.10.1
./build.sh -hadoop 3.1.0 -tez 0.10.1 -hive 3.1.3
docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --env SCHEMA_COMMAND=upgradeSchema --name hive3 apache/hive:3.1.3
docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --env SCHEMA_COMMAND=upgradeSchema --name hive3 apache/hive:3.1.3
docker logs e9e09f7e580f3575fba91531227fd077194d0b009b86aa875db178bd915be6b9
```

And there is still and error msg, however a new one:

```org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version, Cause:Table/View 'VERSION' does not exist.
Use --verbose for detailed stacktrace.
*** schemaTool failed ***
+ '[' 1 -eq 0 ']'
+ echo 'Schema initialization failed!'
+ exit 1
Schema initialization failed!```

**Comment by ayushtkn** [comment]
Did you try the already published image: 
https://hub.docker.com/layers/apache/hive/3.1.3/images/sha256-d102ba29ad07e93c303894896203a80b903c0001d80221f1cb9fea92dcac06e4?context=explore

**Comment by simhadri-g** [comment]
We haven't pushed arm64 based images for 3.1.3 to docker hub.

**Comment by dengzhhu653** [comment]
> I realized that there is a need to export env variable with hadoop version, not only pass it to the build script. However it is still not working :( Here are the repro steps:
> 
> ```
> export HADOOP_VERSION=3.1.0
> export HIVE_VERSION=3.1.3
> export TEZ_VERSION=0.10.1
> ./build.sh -hadoop 3.1.0 -tez 0.10.1 -hive 3.1.3
> docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --env SCHEMA_COMMAND=upgradeSchema --name hive3 apache/hive:3.1.3
> docker logs e9e09f7e580f3575fba91531227fd077194d0b009b86aa875db178bd915be6b9
> ```
> 
> And there is still and error msg, however a new one:
> 
> ```
> org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version, Cause:Table/View 'VERSION' does not exist.
> Use --verbose for detailed stacktrace.
> *** schemaTool failed ***
> + '[' 1 -eq 0 ']'
> + echo 'Schema initialization failed!'
> + exit 1
> Schema initialization failed!
> ```

I think this failure is due to no hive schema is here for upgrading, please try with "--env SCHEMA_COMMAND= initSchema" or just ignore this argument, for example:
```
docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --name hive3 apache/hive:3.1.3

**Comment by bkyryliuk** [comment]
Thanks ! that worked

**Pull request merged**
