### PR TITLE
HIVE-23682 : TestMetrics is flaky

### PR DESCRIPTION
**Pull request by rkirtir**
### What changes were proposed in this pull request?
HIVE-23682

### Why are the changes needed?
To enable test in testsuite

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
testcse

### CODE REVIEW

**Comment by rkirtir** [comment]
Flakey test jenkins job is successful

http://ci.hive.apache.org/job/hive-flaky-check/656/console

**Comment by TuroczyX** [comment]
Is it not flaky anymore?

**Comment by rkirtir** [comment]
> http://ci.hive.apache.org/job/hive-flaky-check/656/console

**Review by veghlaci05 — APPROVED** [review]
LGTM, if not flaky anymore it can be re-enabled

**Pull request merged**
