### PR TITLE
Backport HIVE-24851: Fix reader leak in AvroGenericRecordReader to branch-3.1

### PR DESCRIPTION
**Pull request by losipiuk**
This is a cherry-pick of #2040 (https://issues.apache.org/jira/browse/HIVE-24851) to branch-3.1

Followup after cherry-pick to `branch-3` from https://github.com/apache/hive/pull/2104.

### CODE REVIEW

**Comment by losipiuk** [comment]
@pvary this is the last one. I promise :)

**Comment by pvary** [comment]
> @pvary this is the last one. I promise :)

Never say never 😄

**Comment by pvary** [comment]
> @pvary it looks CI failed. How can I check if that is related (I very much doubt that)

I am not entirely sure. Either we can ask on the dev list, or we can run a test with a "null" change, and see the test results there as well.

**Comment by losipiuk** [comment]
> > @pvary it looks CI failed. How can I check if that is related (I very much doubt that)
> 
> I am not entirely sure. Either we can ask on the dev list, or we can run a test with a "null" change, and see the test results there as well.

I added "empty" commit. Let's see if it will trigger CI

**Comment by findepi** [comment]
@pvary can you please help diagnose the build results?

**Comment by pvary** [comment]
> @pvary can you please help diagnose the build results?

I would go to the failure list, and ignore the ones which are failing in both patches. I see 1 fixed (most important to check), and 2 new failures (less important but I would check anyway). If the failures are flaky or green on local. Then I would push again my changes and hope for a "green" run.

**Comment by losipiuk** [comment]
Based on 3 runs it looks like all the test failures are flakes. Same tests (which FWIW seem totally unrelated to the change) fail on on run and pass on the other.
* (1) http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-2129/1/tests/
  * Only preexisting failures
* (2) http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-2129/2/tests/
  * TestSlotZnode.testConcurrencyNoFallback failed (green on (1) and (3))
  * TestSlotZnode.testConcurrencyAndFallback failed (green on (1) and (3))
* (3) http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-2129/3/tests/
  * TestJdbcDriver2.testSelectExecAsync2 failed (was green on (2)

**Comment by losipiuk** [comment]
@pvary mergable?

**Comment by pvary** [comment]
Merged.

Thanks for the fix and the work done to backport the change @losipiuk!

**Pull request merged**
