### PR TITLE
HIVE-27171: Backport HIVE-20680 to branch-3

### PR DESCRIPTION
**Pull request by vihangk1**
### What changes were proposed in this pull request?
This PR backports HIVE-20680 to branch-3 needed to fix TestReplicationScenariosAcrossInstances

### Why are the changes needed?
Fix TestReplicationScenariosAcrossInstances

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
CI Job

### CODE REVIEW

**Comment by vihangk1** [comment]
@amanraj2520 Can you please review this. We need to backport HIVE-20680 and HIVE-20953 to fix the TestReplicationScenariosAcrossInstances on branch-3. I tested these backports fix the test in https://github.com/apache/hive/pull/4147

**Comment by amanraj2520** [comment]
@vihangk1 What a coincidence!! I identified the same tickets and raised the PR at the same time as you. PR for reference - https://github.com/apache/hive/pull/4149

**Comment by amanraj2520** [comment]
@vihangk1 I see this test still failing on this PR. Any difference between #4147  and this?

**Comment by amanraj2520** [comment]
@vihangk1 This is the exact and accurate fix I had in mind for this test. +1 from my side. Once we cherry pick FunctionTask changes, we can merge this

**Comment by vihangk1** [comment]
Thanks @amanraj2520. Merged.

**Pull request merged**
