### PR TITLE
HIVE-26915: Disable TestCodahaleMetrics.testFileReporting flaky

### PR DESCRIPTION
**Pull request by amanraj2520**
This commit was done in the mast branch without raising a JIRA ticket, Please check this commit : 130f80445d589cdd82904cea1073c84d1368d079. Disabling this test since it is flaky.

### CODE REVIEW

**Review by cnauroth — APPROVED** [review]
+1 (non-binding)

Thank you, @amanraj2520 !

**Comment by amanraj2520** [comment]
@abstractdog Can we merge this as well

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Can you please review and merge this as well.

**Review by zabetak — CHANGES_REQUESTED** [review]
@amanraj2520 Can you provide some proofs that the test is flaky in branch-3 (see https://lists.apache.org/thread/55botwq7trf6vo68333mfn1m6rxm60o4) ? We don't want to disable tests unless there are evidence that they are flaky; please also include such information in the JIRA ticket.

**Comment by amanraj2520** [comment]
Hi @zabetak Please refer this http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3900/8/tests/. In this run it is failing.

**Comment by amanraj2520** [comment]
@zabetak Also here http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3859/11/tests/

**Comment by amanraj2520** [comment]
@zabetak Here is another flakiness http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3954/4/tests

**Comment by amanraj2520** [comment]
@zabetak @abstractdog Can you please review and merge this

**Comment by amanraj2520** [comment]
@zabetak @abstractdog Please review this.

**Review by abstractdog — APPROVED** [review]

**Pull request merged**
