### PR TITLE
HIVE-27096 : Fix test dbtxnmgr_showlocks.q

### PR DESCRIPTION
**Pull request by amanraj2520**
The test is passing in my local. Not sure why is it failing on Jenkins. Anyways, I think it is just a CompactionID change so I don't think it is a major breaking change. This fix would fix it on Jenkins build.
The test fails due to the following Assertion ERROR :
Client Execution succeeded but contained differences (error code = 1) after executing dbtxnmgr_showlocks.q
73c73
< 5 default partitioned_acid_table p=abc MINOR initiated — --- — ---
—
> 1 default partitioned_acid_table p=abc MINOR initiated — --- — ---
 
It expects a Compaction ID 1 but gets 5.

### CODE REVIEW

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Can you please review this. This test passes on my local

**Review by zabetak — COMMENTED** [review]
If you cannot repro the problem locally then most likely it is a side-effect of other test cases running before `dbtxnmgr_showlocks.q`. Try running the whole split locally and see if you can repro the failure
```
mvn install -pl itests/qtest -Pitests,qsplits -Dtest=org.apache.hadoop.hive.cli.split3.TestCliDriver -Dtest.output.overwrite
```
I suspect that there are other compaction tests in the same split, and running them before dbtxnmgr_showlocks.q` is causing this failure.

If that is true then updating the value from `1 to 5` is not sufficient; when the test sequence changes things will break again. 

I get the impression that the problem can also affect master so when you find which sequence of tests is causing this please create a PR against master as well.

**Comment by amanraj2520** [comment]
Hi @zabetak You were right. I was able to repro this. I agree we need to fix this in master. Investigating this. Here is the list of test cases that run before this test : https://drive.google.com/file/d/1wCe6ZLU42xYD2gr3oNc_6rS35xVl3T6c/view?usp=sharing

**Comment by amanraj2520** [comment]
@zabetak dbtxnmgr_compact1.q (increments by 1), dbtxnmgr_compact2.q (increments by 2) and dbtxnmgr_compact3.q (increments by 1) And then dbtxnmgr_showlocks.q runs which gets CompactionID as 5. Can you please suggest should we remove the show compactions statement or should I write a separate CliDriver only for this dbtxnmgr_showlocks.q which would run it as a separate test.

Also, "show compactions" is only present in this test only.

**Comment by zabetak** [comment]
@amanraj2520 I would suggest to make use of `--! qt:replace` option to mask the compaction id since I don't think it is important for the test case. Please create a new JIRA for master with proper summary and description (including your analysis here) and then create a PR for it.

After that this becomes a simple backport.

**Comment by amanraj2520** [comment]
Hi @zabetak I tried to use the  '--! qt:replace' option but the issue is that in branch-3 we do not have the commit which added QTestReplaceHandler.java. This was done in HIVE-22297. But backport HIVE-22297 is not straightforward. We need to backport multiple JIRAs in order to have a clean backport. And only a single test is failing because of this in branch-3. So I think we can either remove the show compactions or update it to 5 for now.

Having said that, I will raise a ticket in master to ensure this is taken care of there. Please let me know if this sounds good or should we spend some time in backporting all the qtest related changes.

**Comment by zabetak** [comment]
@amanraj2520 Let's update it to 5 for now.

**Comment by amanraj2520** [comment]
@zabetak In that case can you please merge this PR if it looks good.

**Comment by zabetak** [comment]
@amanraj2520 The test currently fails. You seem to have missed some white space changes.

**Comment by amanraj2520** [comment]
Sure will do

**Comment by amanraj2520** [comment]
@zabetak Can you please review and merge this. Somehow the space was not getting committed from my local machine. Now the test is passing.

**Review by zabetak — APPROVED** [review]

**Pull request closed without merging**
