### PR TITLE
[HIVE-20771] LazyBinarySerDe fails on empty structs

### PR DESCRIPTION
**Pull request by cvaliente**

### CODE REVIEW

**Comment by belugabehr** [comment]
@jcamachor Can you take a look at this?  Does it make sense to enable this?

**Comment by zaboron** [comment]
@jcamachor @belugabehr 
I think this very much makes sense, it is a bugfix. The LazyBinarySerDe serializes empty structs but is no longer able to deserialize said object. 
A serde should always be able to deserialize objects it serialized?

**Comment by belugabehr** [comment]
Can you provide new PR based on master?

**Comment by jcamachor** [comment]
LGTM.

**Comment by belugabehr** [comment]
@cvaliente Can you please create a new PR against the master branch?

**Comment by belugabehr** [comment]
Merging into master as from #1298

**Pull request closed without merging**
