### PR TITLE
HIVE-25144: Add NoReconnect Annotation to CreateXXX Methods With AlreadyExistsException

### PR DESCRIPTION
**Pull request by belugabehr**
…on Methods

### CODE REVIEW

**Comment by belugabehr** [comment]
@nrg4878 Mind taking a look?

**Comment by nrg4878** [comment]
@belugabehr How does adding this annotation create AlreadyExistsException? I havent looked into this in a very long time but its my recollection that this annotation was used by either the RetryingHMSHandler or RetryingMetastoreClient to determine whether or not to retry this operation. I would have guess it was the RetryingHMSHandler but given this change, I suspect it is the latter.
So how exactly does this result in a AlreadyExistsException? What if the failure was due to a DB_LOCK timeout (Where another transaction has the lock on the table). 
Also, do the implementing classes inherit annotations from the interface? I thought it was limited to just the javadoc annotations.

**Comment by belugabehr** [comment]
@nrg4878 I have changed the title of the PR.  It's not about _creating_ the exception.  I've added the annotation to any createXXX method which also throws an AlreadyExistsException.  It does not make sense to re-try these methods because you could be in a situation where the operation completes from the perspective of HMS but the connection is killed and then a "AlreadyExists" exception is thrown which is very confusing from the client perspective.  Best to just throw an error and have the client software decide how to handle it.

re: Annotation inheritance, I'll double-check, but there already exists one on this interface.

**Comment by belugabehr** [comment]
@nrg4878 Here is the code I'm looking at:

https://github.com/apache/hive/blob/0c7903d7fd4675d82f653f8d305d96509a84e186/standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java#L167-L176

**Comment by belugabehr** [comment]
@nrg4878 Thanks for the gut-check.  Ignore everything I've said thus far.  I was confusing things. I thought it was the client that was re-trying.  It's actually the HMS Handler. Ick. Ugh.  I need to dig deeper on this.

**Pull request closed without merging**
