### PR TITLE
 HIVE-27824 : Upgrade ivy to 2.5.2 and htmunit to 2.70.0

### PR DESCRIPTION
**Pull request by devaspatikrishnatri**
### What changes were proposed in this pull request?
Upgrade ivy to 2.5.2 and htmunit to 2.70.0

### Why are the changes needed?
CVE Fixing

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
Yes

### How was this patch tested?
Locally built , relying on precommit.

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]
+1

**Comment by aturoczy** [comment]
@devaspatikrishnatri I know there are breaking change in htmlUnit 3, but don't you want to try out to update to the latest one? The 2 is a legacy line

**Comment by devaspatikrishnatri** [comment]
@aturoczy I was trying this so as to upgrade ivy to 2.5.2 , as in last attempt there were some problems discovered as mentioned in https://issues.apache.org/jira/browse/HIVE-27849.I am not sure if this will work , but hoping that upgrading both these dependencies won't cause the replication failures as 2.70.0 has some changes related to parsing xmlattributes,
https://htmlunit.sourceforge.io/changes-report.html#a2.70.0.

But , yes will surely try to upgrade html unit to 3.x line , in a separate PR (hoping this feels reasonable).

**Comment by aturoczy** [comment]
@SourabhBadhya @deniskuzZ Could you pls merge it if it is acceptable?

**Review by SourabhBadhya — APPROVED** [review]
LGTM +1

**Review by SourabhBadhya — COMMENTED** [review]
@devaspatikrishnatri Does the htmlunit version upgrade solve the replication unit tests in this case?
I would advise to run the flaky test job ( http://ci.hive.apache.org/job/hive-flaky-check/ ) on the replication tests so that we can confirm with certainty that we are not causing the same issue again.

**Comment by devaspatikrishnatri** [comment]
@SourabhBadhya Is this run acceptable ?
http://ci.hive.apache.org/job/hive-flaky-check/778/

The tests seems to be passing..

**Comment by SourabhBadhya** [comment]
@devaspatikrishnatri Seems good to me. I will proceed with merging.

**Pull request merged**
