### PR TITLE
HIVE-23976: Enable vectorization for multi-col semi join reducers

### PR DESCRIPTION
**Pull request by abstractdog**
### What changes were proposed in this pull request?
Implement vectorized expression for murmur hash.

### Why are the changes needed?
Implement vectorized expression for murmur hash in order to stay vectorized for multi-key bloom filter path.

### Does this PR introduce _any_ user-facing change?
No, but this is an improvement change, which appears in the explain plan.

### How was this patch tested?
Unit test attached.
Explain plan shows expected results.

### CODE REVIEW

**Comment by abstractdog** [comment]
@t3rmin4t0r , @zabetak , @ramesh0201: could you please take a look? good-old vectorization coverage patch, murmurhash with 2 column params

**Comment by jcamachor** [comment]
@abstractdog , @zabetak , this PR has been labeled as stale and is about to be closed automatically. What is the status: Does it need more work or is it ready to be pushed?

**Comment by zabetak** [comment]
There are some comments in the JIRA case but we could possibly treat them as follow-ups if necessary. This PR is in good shape already so I think it can be merged as is.

**Comment by jcamachor** [comment]
@abstractdog , can you trigger tests again?

**Comment by abstractdog** [comment]
> @abstractdog , can you trigger tests again?

yeah, rebased to master, and pushed for new tests

**Review by jcamachor — APPROVED** [review]

**Pull request merged**
