### PR TITLE
HIVE-25963: Addendum: ported unit test fixes from PR #3040

### PR DESCRIPTION
**Pull request by sourabh912**
Ported back commits from https://github.com/apache/hive/pull/3040/
that are missing in master branch

### CODE REVIEW

**Comment by sourabh912** [comment]
@nrg4878 : Please review

**Comment by nrg4878** [comment]
@sourabh912 looks like this change might still be missing from this patch.
(https://github.com/apache/hive/pull/3040/commits/c45f4100ee3932609063688e573f67f85e677512)

**Comment by nrg4878** [comment]
PR merged. Please close the PR

**Comment by sourabh912** [comment]
Thank you for approving and merging the PR, @nrg4878

**Pull request closed without merging**
