### PR TITLE
HIVE-27738 : Fix Schematool version so that it can pickup correct schema script file after 4.0.0-beta-1 release

### PR DESCRIPTION
**Pull request by rkirtir**
…ema script file after 4.0.0-beta-1 release

### What changes were proposed in this pull request?
hive.version.shortname has been fixed from / pom.xml and standalone-metastore/pom.xml so that it should pick up hive-schema-4.0.0-beta-2.mysql.sql file correctly

### Why are the changes needed?
hive.version.shortname has been fixed from / pom.xml and standalone-metastore/pom.xml so that it should pick up hive-schema-4.0.0-beta-2.mysql.sql file correctly

### Does this PR introduce _any_ user-facing change?
NO

### Is the change a dependency upgrade?
NO

### How was this patch tested?
manually with below command
./schematool --dbType mysql -initSchema

### CODE REVIEW

**Review by zabetak — COMMENTED** [review]
LGTM, thanks for catching this @rkirtir !

It seems that this is not the first time that this is happening. Is it possible to add some test cases that do some sanity checks. For instance, we could check that:
* `fullVersion` without "-SNAPSHOT" is equal to `shortVersion`
* `shortVersion` is a prefix of `fullVersion`.

**Comment by rkirtir** [comment]
Thanks for review!!
https://issues.apache.org/jira/browse/HIVE-27745 created and will add that test

**Comment by wecharyu** [comment]
Nice catch! I have also suffered version issue in #4744, this PR fix my test cases.

**Comment by rkirtir** [comment]
Upstream precommit infra is shaky again.. it takes hell lot of time to complete the build and at the end it fails with different flakey tests which nothing to do with the changes in that commit :disappointed:  . Some of the tests like orc_merge*.q are flakey as it needs masking. If re-triggering few times makes the build pass, means either we are having infra resource starvation or test suite computations/assertions/teardown after test needs to be revised test by test. Appreciate your inputs here.

I juts got luck to get green build just now, requesting review

**Review by zabetak — APPROVED** [review]
I already approved the changes before. Will merge this now.

**Comment by zabetak** [comment]
> BTW, I think hive.version is already able to cover all cases, do we still need hive.version.shortname

@wecharyu Maybe we don't need it but there is some history behind it so if we can/want to get rid of it we can do it as separate ticket.

**Pull request closed without merging**
