### PR TITLE
HIVE-27351: Hive metastore metrics is not getting initialised even if metrics is enabled

### PR DESCRIPTION
**Pull request by arshadmohammad**
### What changes were proposed in this pull request?

Use configured value of hive.service.metrics.hadoop2.component

### Why are the changes needed?

hive metasore metrics is not getting enabled

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Build the hive after the change, replaced related jar, started metastore verified that metrics sink is started

### CODE REVIEW

**Review by rkirtir — APPROVED** [review]

**Comment by rkirtir** [comment]
I think it needs to be retriggered.

**Comment by ayushtkn** [comment]
where is the PR for master branch?

**Comment by arshadmohammad** [comment]
> where is the PR for master branch?
This issue is already fixed in master branch. [HIVE-19989](https://issues.apache.org/jira/browse/HIVE-19989) fixed the issue.
I have skipped recordName change from "general-metadata" to "General" because this change will introduce backward incompatibility in a minor version, other than this, changes in this PR are exactly same as  HIVE-19989

**Comment by arshadmohammad** [comment]
Looks failed test cases are not related to this PR change.

**Pull request closed without merging**
