### PR TITLE
HIVE-24083: Fix WebHCat is not compatible with Hadoop 3.3.x

### PR DESCRIPTION
**Pull request by kevinw66**

### CODE REVIEW

**Comment by kevinw66** [comment]
@deniskuzZ @nrg4878 @szlta @zabetak 
Can you help review this PR? thanks.

**Comment by zabetak** [comment]
Thanks for the PR @kevinw66 .

I am mainly focusing on problems affecting the `master` branch and I don't have much experience in this are so cannot review this PR.

**Comment by kevinw66** [comment]
> Thanks for the PR @kevinw66 .
> 
> I am mainly focusing on problems affecting the `master` branch and I don't have much experience in this are so cannot review this PR.

@zabetak `master` branch might has same problem, since it's the compatible issue with Hadoop 3.3.x, I tested with hive 3.1.3 with hadoop 3.3.4
Hadoop changed his auth mechanism since Hadoop 3.3.0
https://github.com/apache/hadoop/commit/4ea6c2f457496461afc63f38ef4cef3ab0efce49#diff-680cfa76ea617a05a7a414540076bf6570a82f244f46e94bd745e3c4d259304a

**Comment by zabetak** [comment]
I left some comments under the JIRA. Keep in mind that whatever lands in branch-3.1 (or older branches) must first land in `master`.

**Pull request closed without merging**
