### PR TITLE
HIVE-27217: Rethrow unhandled exception in addWriteNotificationLogInB…

### PR DESCRIPTION
**Pull request by jfsii**
…atch

### What changes were proposed in this pull request?
Rethrow an unhandled exception in  addWriteNotificationLogInBatch to make failures much more visible.

### Why are the changes needed? 
If we don't re-throw the exception, a failure to write to the notification log could be hard to notice. It is very hard to debug after the fact.

### Does this PR introduce _any_ user-facing change?
In very rare cases addWriteNotificationLogInBatch failures will become visible when they were not.

### How was this patch tested?
Local dev environment against a HMS implementation that throw an TApplicationException that addWriteNotificationLogInBatch did not handle.

### CODE REVIEW

**Comment by TuroczyX** [comment]
This is truly a best practice in any OOP language to rethrow the exception.  To swallow it is rarely a good idea, but **could be** a good choice especially when the domain logic should manage those error scenario where exception is an expected behaviors' from the business logic perspective. 

Here as I see this notification log is mainly for 
`TApplicationException.UNKNOWN_METHOD ||  TApplicationException.WRONG_METHOD_NAME) `

Which is the main use-case when a method is not implemented and it can't be goes into notification log. Do we have here different use cases as well? If yes then your point is right to rethrow it.

Also if you rethrow where it will be catched?

**Comment by jfsii** [comment]
Re: @TuroczyX 
When it is re-thrown it will bubble up to the user as an exception during execution. It would be treated as other thrift exceptions would be - such as if the HMS server went down or the call timed out.

It is not a good choice to swallow here, because a missing write notification will affect various systems such as maybe event notification and replication. It is much preferable to fail and make it visible so a user can take action (either by checking HMS logs, making sure HMS connectivity is good, etc) rather than having to figure out why the notification log is missing entries long after the fact. I feel like this is an oversight when attempting the fallback mechanism rather than a purposeful choice to ignore these exceptions.

The reason I found this is due to the Impala catalogd implementation not implementing add_write_notification_log_in_batch which causes it to throw a different TApplicationException and thus the add_write_notification_log_in_batch is failed silently. Since catalogd also relies on the notification log/events, depending on timing of events, the metadata cache would end up  containing incorrect metadata because it didn't realize a partition was updated. This could be fixed on the catalogd side of things to throw a UNKNOWN_METHOD or WRONG_METHOD_NAME exception, but it is still entirely possible for a TApplicationException of a different type to still be thrown. I've seen "UNKNOWN" in the past, but there also exists INVALID_MESSAGE_TYPE/BAD_SEQUENCE_ID/MISSING_RESULT which could very well show up depending on network conditions and/or issues during the processing on the HMS side.

**Review by scarlin-cloudera — APPROVED** [review]
LGTM

**Review by zabetak — APPROVED** [review]
LGTM!

I am +2 as it is but if had a test that goes along I would be +100 :) 

Would it be feasible/easy to do something similar to `TestHiveMetaStoreClientApiArgumentsChecker` where we have  a fake `IMetaStoreClient` that throws and then put `Hive.loadDynamicPartitions` under test? If it is too complicated I am perfectly fine merging this as is.

**Comment by jfsii** [comment]
> LGTM!
> 
> I am +2 as it is but if had a test that goes along I would be +100 :)
> 
> Would it be feasible/easy to do something similar to `TestHiveMetaStoreClientApiArgumentsChecker` where we have a fake `IMetaStoreClient` that throws and then put `Hive.loadDynamicPartitions` under test? If it is too complicated I am perfectly fine merging this as is.

@zabetak I can certainly try - if it turns out that it becomes too complex for the benefit, I'll say something.

**Pull request closed without merging**
