### PR TITLE
HIVE-24331: Add Jenkinsfile for branch-3.1

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Two changes combined in this PR:
- backport [HIVE-23323](https://issues.apache.org/jira/browse/HIVE-23323) to enable better parallelism for qtests
- Add Jenkinsfile

### Why are the changes needed?

Without a Jenkinsfile we won't trigger CI for new PRs against the branch-3.1. This allows ppl to test their code.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by sunchao** [comment]
seems the `TestMiniDruidKafkaCliDriver` is timing out and we need https://issues.apache.org/jira/browse/HIVE-19170

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @sunchao !

**Comment by dongjoon-hyun** [comment]
Interesting. It seems that we need more patches.
```
There are 1 new tests failing, 62 existing failing and 249 skipped.
```

**Comment by sunchao** [comment]
I think these failures are not related to the PR - at least the PR itself gives us a baseline for the test results.

**Comment by sunchao** [comment]
cc @kgyrtkirk could you take a look? thanks.

**Comment by kgyrtkirk** [comment]
thank you @sunchao for working on this! these failures were most likely there before as well. I haven't noticed anything problematic (with the test execution stuff)
+1

**Comment by dongjoon-hyun** [comment]
Thank you, @kgyrtkirk and @sunchao .
Then, can we merge this and proceed to fix the bug based on this CI failures?

**Comment by sunchao** [comment]
Thanks @kgyrtkirk . I'll backport HIVE-23323 and HIVE-19170 separately to the branch-3.1 to retain a clean commit history, and then create a new PR with just the jenkins file change and merge it.

**Comment by sunchao** [comment]
Merged. Thanks @kgyrtkirk for the review.

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Pull request merged**
