### PR TITLE
HIVE-26579. Prepare for Zookeeper, Hadoop switching to Reload4j

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Zookeeper and Hadoop moved from Log4j1 to Reload4j ([ZOOKEEPER-4455](https://issues.apache.org/jira/browse/ZOOKEEPER-4455), [HADOOP-18088](https://issues.apache.org/jira/browse/HADOOP-18088)) . The goal of this task is to prepare Hive for these changes:

 * Hive build fails if ZK and Hadoop dependencies are upgraded, due to `useStrictFiltering=true` setting in some assemblies, because excluded dependency log4j is no longer present.
 * Exclude `ch.qos.reload4j:*` in addition to current `log4j:*` to avoid polluting the assemblies and shaded jars.

```
$ mvn -DskipTests -Dhadoop.version=3.3.4 -Dzookeeper.version=3.5.10 -Pdist clean install
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.2.0:single (assemble) on project hive-standalone-metastore-server: Assembly is incorrectly configured: bin: Assembly is incorrectly configured: bin: 
[ERROR] Assembly: bin is not configured correctly: One or more filters had unmatched criteria. Check debug log for more information.
```

https://issues.apache.org/jira/browse/HIVE-26579

## How was this patch tested?

CI build was successful:
https://github.com/adoroszlai/hive/actions/runs/3158692928/jobs/5141014133

Built Hive locally, checked artifacts affected by the change still do not have Log4j1 jar/classes:

```
$ mvn -DskipTests -Pdist clean install
...
[INFO] BUILD SUCCESS

$ tar tzvf standalone-metastore/metastore-server/target/apache-hive-standalone-metastore-server-4.0.0-alpha-2-SNAPSHOT-bin.tar.gz | grep log4j
-rw-r--r-- root/root      2731 2020-01-22 16:10 apache-hive-metastore-4.0.0-alpha-2-SNAPSHOT-bin/conf/metastore-log4j2.properties
-rw-r--r-- root/root     24801 2020-01-22 16:10 apache-hive-metastore-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-slf4j-impl-2.18.0.jar
-rw-r--r-- root/root    315115 2020-01-22 16:10 apache-hive-metastore-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-api-2.18.0.jar
-rw-r--r-- root/root    349845 2020-01-22 16:10 apache-hive-metastore-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-1.2-api-2.18.0.jar
-rw-r--r-- root/root   1861441 2020-01-22 16:10 apache-hive-metastore-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-core-2.18.0.jar

$ tar tzvf packaging/target/apache-hive-4.0.0-alpha-2-SNAPSHOT-bin.tar.gz | grep log4j 
-rw------- root/root      3086 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/conf/hive-log4j2.properties.template
-rw------- root/root      2274 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/conf/hive-exec-log4j2.properties.template
-rw------- root/root      1596 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/conf/beeline-log4j2.properties.template
-rw------- root/root      7093 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/conf/llap-daemon-log4j2.properties.template
-rw------- root/root      3558 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/conf/llap-cli-log4j2.properties.template
-rw-r--r-- root/root      2708 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/hcatalog/etc/webhcat/webhcat-log4j2.properties
-rw-r--r-- root/root    349845 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-1.2-api-2.18.0.jar
-rw-r--r-- root/root    315115 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-api-2.18.0.jar
-rw-r--r-- root/root     36166 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-web-2.18.0.jar
-rw-r--r-- root/root     24801 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-slf4j-impl-2.18.0.jar
-rw-r--r-- root/root   1861441 2020-01-22 16:10 apache-hive-4.0.0-alpha-2-SNAPSHOT-bin/lib/log4j-core-2.18.0.jar

$ unzip -t jdbc/target/hive-jdbc-4.0.0-alpha-2-SNAPSHOT-standalone.jar | grep log4j 
    testing: hive-log4j2.properties   OK
    testing: META-INF/org/apache/logging/log4j/   OK
    testing: META-INF/org/apache/logging/log4j/core/   OK
    testing: META-INF/org/apache/logging/log4j/core/config/   OK
    testing: META-INF/org/apache/logging/log4j/core/config/plugins/   OK
    testing: META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat   OK
    testing: llap-cli-log4j2.properties   OK
    testing: llap-daemon-log4j2.properties   OK
```

Also built Hive with Hadoop 3.3.4 and Zookeeper 3.5.10:

```
$ mvn -DskipTests -Dhadoop.version=3.3.4 -Dzookeeper.version=3.5.10 -Pdist clean install
...
[INFO] BUILD SUCCESS

$  tar tzvf standalone-metastore/metastore-server/target/apache-hive-standalone-metastore-server-4.0.0-alpha-2-SNAPSHOT-bin.tar.gz | grep -e log4j -e reload4j
(same as before)

$ tar tzvf packaging/target/apache-hive-4.0.0-alpha-2-SNAPSHOT-bin.tar.gz | grep -e log4j -e reload4j                                                        
(same as before)

$ unzip -t jdbc/target/hive-jdbc-4.0.0-alpha-2-SNAPSHOT-standalone.jar | grep -e log4j -e reload4j
    testing: hive-log4j2.properties   OK
    testing: META-INF/org/apache/logging/log4j/   OK
    testing: META-INF/org/apache/logging/log4j/core/   OK
    testing: META-INF/org/apache/logging/log4j/core/config/   OK
    testing: META-INF/org/apache/logging/log4j/core/config/plugins/   OK
    testing: META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat   OK
    testing: llap-cli-log4j2.properties   OK
    testing: llap-daemon-log4j2.properties   OK
    testing: META-INF/maven/org.slf4j/slf4j-reload4j/   OK
    testing: META-INF/maven/org.slf4j/slf4j-reload4j/pom.xml   OK
    testing: META-INF/maven/org.slf4j/slf4j-reload4j/pom.properties   OK
```

### CODE REVIEW

**Comment by adoroszlai** [comment]
@nrg4878 may I ask you to review?

**Review by ayushtkn — COMMENTED** [review]
Give a check if we need to explicitly exclude reload4j dependencies like we have for log4j from hadoop artifcats as mentioned in HADOOP-18088

**Review by ayushtkn — COMMENTED** [review]
Guess we need two exclusions right?
We need to add:
```
<exclusion>
  <groupId>ch.qos.reload4j</groupId>
  <artifactId>reload4j</artifactId>
</exclusion>
```

That is what the [HADOOP-18088](https://issues.apache.org/jira/browse/HADOOP-18088) said in the release notes, and I can find ``ch.qos.reload4j:reload4j:jar:1.2.22:compile`` being pulled from Hadoop jars in the mvn dependency:tree output as well

**Comment by adoroszlai** [comment]
Thanks @ayushtkn for the review.  Since `log4j:log4j` is not excluded in POMs, I assumed we do not have to exclude `ch.qos.reload4j:reload4j` either.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
