### PR TITLE
HIVE-24035: Add Jenkinsfile for branch-2.3

### PR DESCRIPTION
**Pull request by sunchao**
### What changes were proposed in this pull request?

Enable precommit tests for github PR against branch-2.3.

### Why are the changes needed?

Adding a new Jenkinsfile for the repo. This is almost the same file used in the master branch, except changing timeout from 6 to 12 hours.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by sunchao** [comment]
@kgyrtkirk the jenkins job is just taking way too long to run - I've changed the threshold to 36 hours and it still timed out. I'm seeing some errors like:
```
Cannot contact hive-precommit-pr-1398-7-s1hnr-sxk50-z5v6w: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@59e81d65:JNLP4-connect connection from 10.0.1.14/10.0.1.14:41634": Remote call on JNLP4-connect connection from 10.0.1.14/10.0.1.14:41634 failed. The channel is closing down or has closed down
```

which seems like some infra issue is going on. Curious if you have any clue and suggestions on how to proceed this.

**Comment by sunchao** [comment]
kindly ping @kgyrtkirk - wonder if you have any idea on the jenkins issue. Thanks.

**Comment by kgyrtkirk** [comment]
sorry, I missed your previous message

did that exception happens all the time? i've alao seen it a few times....but it seemed intermittent
So far i had no time to investigate it further

I'll restart tests to see if it passes

**Comment by sunchao** [comment]
Thanks @kgyrtkirk ! I got the error message a few times but this times seem the tests finished in a few hours, which is great. Lots of tests failed though so I'll take a look at those.

**Comment by kgyrtkirk** [comment]
there are a lot of failures connected to some calcite CNF issues.... I would guess that either multiple versions of calcite is present via shading/etc - on the master once there were some issues because druid also has a calcite

**Comment by sunchao** [comment]
Yeah I remember seeing this in either branch-2 or branch-2.3 test failures before, but this time the number is much higher. Let me see if I can reproduce this locally.

**Comment by sunchao** [comment]
We made some progress in enabling this for branch-2.3, _only_ 781 tests are failing right now. 

@viirya it seems #1356 has caused some issues related to Guava, and that I merged it too early :(. There are lots of errors like the following:
```

[2020-09-01T21:07:31.008Z] Caused by: java.lang.NoSuchMethodError: location = jar:file:/home/jenkins/agent/workspace/hive-precommit_PR-1398/.git/m2/org/apache/calcite/calcite-core/1.10.0/calcite-core-1.10.0.jar!/org/apache/calcite/rel/RelCollationImpl.class. error msg = org.apache.calcite.rel.RelCollationImpl.<init>(Lorg/apache/hive/com/google/common/collect/ImmutableList;)V
[2020-09-01T21:07:31.008Z]     at org.apache.hadoop.hive.ql.optimizer.calcite.RelOptHiveTable.getCollationList(RelOptHiveTable.java:186)
[2020-09-01T21:07:31.008Z]     at org.apache.calcite.rel.metadata.RelMdCollation.table(RelMdCollation.java:175)
[2020-09-01T21:07:31.008Z]     at org.apache.calcite.rel.metadata.RelMdCollation.collations(RelMdCollation.java:122)
[2020-09-01T21:07:31.008Z]     at GeneratedMetadataHandler_Collation.collations_$(Unknown Source)
[2020-09-01T21:07:31.008Z]     at GeneratedMetadataHandler_Collation.collations(Unknown Source)
[2020-09-01T21:07:31.008Z]     at org.apache.calcite.rel.metadata.RelMetadataQuery.collations(RelMetadataQuery.java:482)
[2020-09-01T21:07:31.008Z]     at org.apache.calcite.sql2rel.RelFieldTrimmer.trimChild(RelFieldTrimmer.java:189)
[2020-09-01T21:07:31.008Z]     at org.apache.calcite.sql2rel.RelFieldTrimmer.trimFields(RelFieldTrimmer.java:374)
[2020-09-01T21:07:31.008Z]     at org.apache.hadoop.hive.ql.optimizer.calcite.rules.HiveRelFieldTrimmer.trimFields(HiveRelFieldTrimmer.java:273)
[2020-09-01T21:07:31.008Z]     ... 47 more
```

like following. Please ignore the debugging message I inserted into the `NoSuchMethodError`. Note that the `RelCollationImpl` constructor is referring to the shaded Guava class instead of the original one.

**Comment by viirya** [comment]
@sunchao Ok. I see. We can revert it first. I can continue looking into it.

**Comment by sunchao** [comment]
OK will do that. We can then add the file to branch-2.3 so that we can have a base line of test results.

**Comment by viirya** [comment]
Ok, cool!

**Comment by sunchao** [comment]
@kgyrtkirk can you review this PR? I think this is ready now - I've tried a few times already and it can successfully run most test cases with a few hundreds failed ones, which is similar to branch-2.

**Comment by kgyrtkirk** [comment]
something is off here:
```
[2020-09-09T05:06:53.645Z] Running org.apache.hadoop.hive.cli.TestMiniLlapLocalCliDriver
[2020-09-09T17:17:29.852Z] Sending interrupt signal to process
[2020-09-09T17:17:29.852Z] Killing processes
[2020-09-09T17:17:30.065Z] kill finished with exit code 0
[2020-09-09T17:17:44.109Z] Terminated
[2020-09-09T17:17:44.120Z] script returned exit code 143
```
and seems like more than 1 pod have tried to execute the TestMiniLlapLocalCliDriver;

**Comment by kgyrtkirk** [comment]
I've taken a quick look at the Jenkinsfile - I don't see reason for running the same stuff in multiple pods
I'm not sure but it might be possible that branch-2 uses an ancient surefire plugin which doesn't even understand the inclusion/exclusion options?

**Comment by sunchao** [comment]
> and seems like more than 1 pod have tried to execute the TestMiniLlapLocalCliDriver;

@kgyrtkirk thanks, yes I noticed this too and I think this is causing the tests timeout. Let me check if the branch-2 is indeed using some outdated surefire plugin.

**Comment by sunchao** [comment]
Hmm `includesFile` and `excludesFile` [should be supported](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html) in 2.13+, and branch-2.3 is using 2.18.1 so should be OK

**Comment by sunchao** [comment]
@kgyrtkirk it is indeed surefire issue - after upgrading to 3.0.0-M4 the issue was resolved and each pod was able to only run tests assigned to it. The job seems still timed out though since one pod was assigned `TestMiniLlapLocalCliDriver` which seems to be very slow. 

Could you take another look?

**Comment by sunchao** [comment]
kindly ping @kgyrtkirk ~~

**Comment by sunchao** [comment]
ping @kgyrtkirk and also @belugabehr

**Comment by kgyrtkirk** [comment]
sorry for the late response...I've many things going on

it looks much better now - it seem like the minillap driver have reached the global timeout limit

I think we might want to cherry-pick the qtests profile patch from HIVE-23323 - which (for my biggest surprise) seem to apply cleanly.

**Comment by sunchao** [comment]
@kgyrtkirk no worries! 

> I think we might want to cherry-pick the qtests profile patch from HIVE-23323 - which (for my biggest surprise) seem to apply cleanly.

Yes this applies cleanly. Thanks for the pointer! Let me put it together in this PR and trigger another test run. If this works we can cherry-pick it separately into branch-2.3.

**Comment by sunchao** [comment]
@kgyrtkirk the latest run went great and only took 10 hours or so. Could you take another look? Thanks!

**Comment by kgyrtkirk** [comment]
That's awesome! I believe most of these failures were already there...
I think we can merge these changes as it will enable branch-2.3 to run tests!

**Review by kgyrtkirk — APPROVED** [review]

**Comment by sunchao** [comment]
Thanks @kgyrtkirk for all the help! I'll cherry-pick HIVE-23323 separately and commit it to branch-2.3 first (to keep good git history). Then I'll  exclude it from this PR and merge. Does it sound good to you?

**Comment by kgyrtkirk** [comment]
sounds great!

**Comment by sunchao** [comment]
Merged. Thanks again @kgyrtkirk !

**Pull request merged**
