### PR TITLE
HIVE-25497: Bump ORC to 1.7.0

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to bump ORC to version 1.7.0.

### Why are the changes needed?
[Apache ORC 1.7.0](https://orc.apache.org/news/2021/09/15/ORC-1.7.0/) is a new release with the following new features and improvements.

ORC-377 Support Snappy compression in C++ Writer
ORC-577 Support row-level filtering
ORC-716 Build and test on Java 17-EA
ORC-731 Improve Java Tools
ORC-742 LazyIO of non-filter columns
ORC-751 Implement Predicate Pushdown in C++ Reader
ORC-755 Introduce OrcFilterContext
ORC-757 Add Hashtable implementation for dictionary
ORC-780 Support LZ4 Compression in C++ Writer
ORC-797 Allow writers to get the stripe information
ORC-818 Build and test in Apple Silicon
ORC-861 Bump CMake minimum requirement to 2.8.12
ORC-867 Upgrade hive-storage-api to 2.8.1
ORC-984 Save the software version that wrote each ORC file

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .

The one failure at `verify` stage looks like an irrelevant one.

**Comment by dongjoon-hyun** [comment]
Thank you for updating.

cc @pgaref

**Comment by pgaref** [comment]
Thanks for the PR @williamhyun  -- unfortunately bumping to 1.7 wont be that straightforward as Hive leverages many of the internal ORC APIs such as TreeReaderFactory. Have already done some preliminary work here and can take over the ticket the work but let me know if you want to invest more time into it.

**Review by pgaref — CHANGES_REQUESTED** [review]
Thanks for the PR @williamhyun -- unfortunately bumping to 1.7 wont be that straightforward as Hive leverages many of the internal ORC APIs such as TreeReaderFactory. Have already done some preliminary work here and can take over the ticket the work but let me know if you want to invest more time into it.

**Comment by williamhyun** [comment]
Thank you @pgaref !
Please feel free to take over.

**Comment by dongjoon-hyun** [comment]
Hi, @pgaref . @williamhyun closed his PR for your taking over. Could you open your PR and share the progress to us please?
> Have already done some preliminary work here and can take over the ticket but let me know if you want to invest more time into it.

**Comment by dongjoon-hyun** [comment]
Gentle ping, @pgaref .

**Pull request closed without merging**
