### PR TITLE
HIVE-26916: Disable TestJdbcGenericUDTFGetSplits.testGenericUDTFOrderBySplitCount1

### PR DESCRIPTION
**Pull request by amanraj2520**
This was done as part of https://issues.apache.org/jira/browse/HIVE-22942 since it is flaky. Cherry picked only the relevant test which is failing.

### CODE REVIEW

**Review by cnauroth — APPROVED** [review]
+1 (non-binding)

There were other ignored tests as part of HIVE-26916, but it looks like the other ones are not needed/relevant for branch-3.

**Comment by amanraj2520** [comment]
@abstractdog can we merge this as well

**Comment by amanraj2520** [comment]
@abstractdog Requesting you to review and merge this.

**Review by zabetak — CHANGES_REQUESTED** [review]
@amanraj2520 Same comment I did in another PR. When disabling or claiming that a test is flaky please provide some evidence showing the failure:
* URL to the failing test in a precommit run of the target branch (branch-3 in this case)
* or URL to a http://ci.hive.apache.org/job/hive-flaky-check/ run reproing the failure

**Comment by amanraj2520** [comment]
Hi @zabetak Sorry for not attaching those instances. http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3859/11/tests/ Please refer to this build for the same.

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Kindly merge this

**Comment by zabetak** [comment]
Hey @amanraj2520 , please check my previous comment. The URL with the failure should be from the target branch or the flaky-checker; not from another PR. I haven't seen the test failing in the recent branch-3 runs.

**Comment by amanraj2520** [comment]
Hi @zabetak I agree this is not failing for recent runs. So closing this then. Will re-activate if its starts failing again

**Pull request closed without merging**
