### PR TITLE
HIVE-27885 : Cast decimal from string with space without digits before dot returns NULL

### PR DESCRIPTION
**Pull request by nareshpr**
### What changes were proposed in this pull request?
Support valid decimal which has only scale.

### Why are the changes needed?
Incorrect results

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
Yes, added testcase in cast2.q file

### CODE REVIEW

**Review by ramesh0201 — APPROVED** [review]

**Comment by ramesh0201** [comment]
+1 LGTM

**Review by aturoczy — COMMENTED** [review]
with the .0000 is applicable in SQL standard?
.00 is more likely a Culture Info and it is bit US specific. 
cc: @ayushtkn @abstractdog

**Comment by nrg4878** [comment]
@ayushtkn any concerns with this or are we good to merge?

**Comment by ayushtkn** [comment]
yep, no objections from my side. go ahed!!!

**Pull request merged**
