### PR TITLE
HIVE-27566: Fix some yarn cluster options for tests

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
why?

**Comment by abstractdog** [comment]
> why?

please find description and repro in jira

**Review by simhadri-g — APPROVED** [review]
Faced issue because of this before. Had to manually update this before starting minihs2. 

LGTM +1

**Comment by abstractdog** [comment]
@ayushtkn : could this be merged?

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
