### PR TITLE
HIVE-26260: Use `Reader.getSchema` instead of deprecated `Reader.getTypes`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to use `org.apache.orc.Reader.getSchema` instead of the deprecated `org.apache.orc.Reader.getTypes` API.

### Why are the changes needed?

`getTypes` was deprecated.

- https://github.com/apache/orc/blob/main/java/core/src/java/org/apache/orc/Reader.java#L144
```java
  /**
   * Get the list of types contained in the file. The root type is the first
   * type in the list.
   * @return the list of flattened types
   * @deprecated use getSchema instead
   * @since 1.1.0
   */
  List<OrcProto.Type> getTypes();
```

In addition, AS-IS implementation is only a slow-wrapper.
- https://github.com/apache/orc/blob/1e2962064b209f1b00188877f08d4226da85c640/java/core/src/java/org/apache/orc/impl/ReaderImpl.java#L259-L262
```java
  @Override
  public List<OrcProto.Type> getTypes() {
    return OrcUtils.getOrcTypes(schema);
  }
```

- https://github.com/apache/orc/blob/1e2962064b209f1b00188877f08d4226da85c640/java/core/src/java/org/apache/orc/OrcUtils.java#L108-L112
```java
  public static List<OrcProto.Type> getOrcTypes(TypeDescription typeDescr) {
    List<OrcProto.Type> result = new ArrayList<>();
    appendOrcTypes(result, typeDescr);
    return result;
  }
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The CI seems to be unstable even in master branch
```
[2022-05-24T01:16:27.260Z] waiting for mysql to be available...
[2022-05-24T01:21:33.971Z] timeout reached before the port went into state "inuse"
```

Could you review this please, @sunchao and @prasanthj ?

**Comment by prasanthj** [comment]
lgtm, +1

**Comment by dongjoon-hyun** [comment]
Thank you for review, @prasanthj .

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @sunchao !

**Comment by sunchao** [comment]
Merged, thanks @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sunchao !

**Pull request merged**
