### PR TITLE
HIVE-26173: (2.3) Upgrade derby to 10.14.2.0

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Backport HIVE-26173 to branch-2.3: Upgrade derby to 10.14.2.0

### Why are the changes needed?

Address CVEs, and fix some starting issues.

I found the current Derby can not start on my Ubuntu machine, upgrading fix it.
```
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Zulu 8.72.0.17-CA-linux64) (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (Zulu 8.72.0.17-CA-linux64) (build 25.382-b05, mixed mode)
```
```
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException:null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:606)
        at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:330)
        at org.datanucleus.store.AbstractStoreManager.registerConnectionFactory(AbstractStoreManager.java:203)
        at org.datanucleus.store.AbstractStoreManager.<init>(AbstractStoreManager.java:162)
        at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManager.java:285)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:606)
        at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:301)
        at org.datanucleus.NucleusContextHelper.createStoreManagerForProperties(NucleusContextHelper.java:133)
        at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:422)
        at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:817)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError:Could not initialize class org.apache.derby.impl.services.monitor.FileMonitor
        at org.apache.derby.iapi.services.monitor.Monitor.startMonitor()
        at org.apache.derby.iapi.jdbc.JDBCBoot.boot()
        at org.apache.derby.jdbc.EmbeddedDriver.boot()
        at org.apache.derby.jdbc.EmbeddedDriver.<clinit>()
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.datanucleus.store.rdbms.connectionpool.AbstractConnectionPoolFactory.loadDriver(AbstractConnectionPoolFactory.java:47)
        at org.datanucleus.store.rdbms.connectionpool.BoneCPConnectionPoolFactory.createConnectionPool(BoneCPConnectionPoolFactory.java:54)
        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSources(ConnectionFactoryImpl.java:213)
        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.initialiseDataSources(ConnectionFactoryImpl.java:117)
        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.<init>(ConnectionFactoryImpl.java:82)
```

### Does this PR introduce _any_ user-facing change?

No.

### Is the change a dependency upgrade?

Yes

### How was this patch tested?

Pass CI

### CODE REVIEW

**Comment by pan3793** [comment]
cc @wangyum @sunchao

**Review by wangyum — APPROVED** [review]

**Review by sunchao — APPROVED** [review]

**Comment by sunchao** [comment]
Merged, thanks @pan3793 and @wangyum !

**Comment by sunchao** [comment]
@pan3793 @wangyum it looks like there are new tests start failing after this PR. In the [previous PR](https://github.com/apache/hive/pull/4870), there were only 28 tests failing, but after this there were 60. Could you check if this is something we should pay attention to? Thanks!

**Comment by pan3793** [comment]
ack, will take a look soon

**Pull request merged**
