### PR TITLE
HIVE-25495: Upgrade JLine to version 3

### PR DESCRIPTION
**Pull request by LA-Toth**
### What changes were proposed in this pull request?

- Update jline to 3.21 - the behaviour is quite different. So a modified version of the JLine2's StringCompleter is added in hive-common.
- Update sqlline to 1.12 as it uses jline 3.21
- Add some missing dependencies to pom.xml files (the lack of these didn't cause issue possibly due to transitive dependency)

### Why are the changes needed?
It's a step required to use JDK 17

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By existing tests.

### CODE REVIEW

**Comment by LA-Toth** [comment]
I created it partially based on pull request 2617.

**Comment by abstractdog** [comment]
I just found this one, is there a chance that we can reopen, rebase @LA-Toth?
I was thinking about proper multiline support in [HIVE-26542](https://issues.apache.org/jira/browse/HIVE-26542) and I think we have a better chance with jline3

**Comment by LA-Toth** [comment]
I still can't run the tests:

latest  kgyrtkirk/hive-dev-box:executor docker image
freshly cloned hive repo from github (master branch)
`mvn clean install -DskipTests -T 1C
 mvn clean install -pl beeline/ 
 mvn clean install -pl beeline/ -Dtest=TestHiveCli#testDatabaseOptions
`
results:
`[ERROR] Failures:
[ERROR]   TestHiveCli.testDatabaseOptions:107->verifyCMD:270 The expected keyword "testtbl" occur in the output:
[ERROR]   TestHiveCli.testSetHeaderValue:89->verifyCMD:270 The expected keyword "testtbl.a testtbl.b" occur in the output:
[ERROR]   TestHiveCli.testSourceCmd:114->verifyCMD:270 The expected keyword "sc1" occur in the output:
[ERROR]   TestHiveCli.testSourceCmd2:122->verifyCMD:270 The expected keyword "sc3" occur in the output:
[ERROR]   TestHiveCli.testSourceCmd4:138->verifyCMD:270 The expected keyword "testtbl" occur in the output:
[ERROR]   TestHiveCli.testSqlFromCmdWithDBName:166->verifyCMD:270 The expected keyword "testtbl" occur in the output:`

and
`[ERROR] Failures:
[ERROR]   TestHiveCli.setup:295->initFromFile:321->executeCMD:256 Supported return code is 0 while the actual is 2`

**Comment by LA-Toth** [comment]
with this change:

   diff --git a/beeline/src/test/org/apache/hive/beeline/cli/TestHiveCli.java             b/beeline/src/test/org/apache/hive/beeline/cli/TestHiveCli.java
   index 5ea4d11b7a..f7be6875ee 100644
   --- a/beeline/src/test/org/apache/hive/beeline/cli/TestHiveCli.java
   +++ b/beeline/src/test/org/apache/hive/beeline/cli/TestHiveCli.java
   @@ -291,8 +291,8 @@ public static void init(){
      public void setup() throws IOException, URISyntaxException {
        System.setProperty("datanucleus.schema.autoCreateAll", "true");
        cli = new HiveCli();
   -    initFromFile();
        redirectOutputStream();
   +    initFromFile();
      }

   private void redirectOutputStream() {

**Comment by nrg4878** [comment]
@LA-Toth I have re-opened this to get some reviews. Seems like there is a conflict. Any chance we could have this rebased? seems like there is a conflict.

**Comment by LA-Toth** [comment]
Rebase itself seems to be relatively easy, the tests are still broken, at least:

```
[ERROR] Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.667 s <<< FAILURE! - in org.apache.hadoop.hive.cli.TestCliDriverMethods
[ERROR] org.apache.hadoop.hive.cli.TestCliDriverMethods.testRun  Time elapsed: 0.829 s  <<< ERROR!
java.lang.NullPointerException
```

The first conflict during the rebase:
`src/java/org/apache/hadoop/hive/cli/CliDriver.java`' - the apache/master branch's changes are fine, but the code requries one more import:
`import com.google.common.base.Splitter;`

After two years I don't remember too much, it was just a regular change for me. And I haven't used Java for a while.
So, anyone who works on Hive daily can fix this faster than me.

Please feel free to improve my changes.

**Comment by abstractdog** [comment]
thanks @LA-Toth!
I just rebased the patch on top of the master, compiled locally, so I just started a new PR, we'll see the results

**Pull request closed without merging**
