### PR TITLE
HIVE-25784: Upgrade arrow to 2.0.0

### PR DESCRIPTION
**Pull request by adesh-rao**

### CODE REVIEW

**Comment by adesh-rao** [comment]
@kgyrtkirk The worker nodes are going offline and pipeline is failing. I tried running this in multiple PR's with same change but seeing the same issue (ephemeral storage is getting full). Can you with the logs to see what is filling up the node's ephemeral storage?

**Comment by kgyrtkirk** [comment]
@adesh-rao interesting....I now see outofspace issues in other testruns - could it be that after the upgrade it started writing a lot of things to the disk which have filled them up?
could you try running locally:
```
-Dtest=org.apache.hadoop.hive.cli.split8.TestMiniLlapLocalCliDriver -Pqsplits -pl itests/qtest
```
and see if any wierd things happen?

I'll try to fix the test system now...

**Comment by adesh-rao** [comment]
> -Dtest=org.apache.hadoop.hive.cli.split8.TestMiniLlapLocalCliDriver -Pqsplits -pl itests/qtest

Ran it locally and find out that tasks were failed and re-tried multiple times which was bloating the log file size (~21GB before I killed the job). 

Fixed it and running the tests again.

**Comment by adesh-rao** [comment]
Thanks @kgyrtkirk for the help. Modified the PR to avoid generating so much logs after the local build.

**Review by sankarh — APPROVED** [review]

**Comment by kgyrtkirk** [comment]
@sankarh could you please wait 24 hours between approval and merge in case someone else would like to also take a look?

**Pull request merged**
