### PR TITLE
HIVE-24470 - Separate HiveMetastore Thrift and Driver logic

### PR DESCRIPTION
**Pull request by Noremac201**
### What changes were proposed in this pull request?

1. Refactor HiveMetastore.HMSHandler into its own class

### Why are the changes needed?

This will pave the way for cleaner changes since now we don't have the driver class nested with 10,000 line HMSHandler file so there is a clearer separation of duties.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing unit tests, building/running manually
Not additional tests were added since this was a pure refactoring

### CODE REVIEW

**Comment by fenglu-g** [comment]
@nrg4878 and others, PTAL, thanks.

**Review by miklosgergely — APPROVED** [review]

**Comment by mwalenia** [comment]
@miklosgergely can you run the tests again?

**Comment by miklosgergely** [comment]
retest

**Comment by miklosgergely** [comment]
recheck

**Comment by miklosgergely** [comment]
@mwalenia please push your changes again to your remote branch, with a new commit having the same content.

**Comment by belugabehr** [comment]
@mwalenia Go ahead and just close the PR manually for 30s and then re-open.  That should trigger the tests again.

**Comment by belugabehr** [comment]
Also, please create a feature branch (HIVE-24470) on your local repository and PR from there.

```
git checkout -b HIVE-24470
```

**Comment by mwalenia** [comment]
since I'm not the PR creator, we'll need to wait with this for @Noremac201. Thanks for the tips!

**Comment by Noremac201** [comment]
Superseded by #1777

**Pull request closed without merging**
