### PR TITLE
HIVE-23998: Upgrade guava to 27 for Hive 2.3 branch

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This PR proposes to upgrade Guava to 27 in Hive 2.3 branch.

### Why are the changes needed?

When trying to upgrade Guava in Spark, found the following error. A Guava method became package-private since Guava version 20. So there is incompatibility with Guava versions > 19.0.

```
sbt.ForkMain$ForkError: sbt.ForkMain$ForkError: java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.hadoop.hive.ql.exec.FetchOperator
	at org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:108)
	at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:87)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:541)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1317)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1457)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1227)
```

### Does this PR introduce _any_ user-facing change?

Yes. This upgrades Guava to 27.

### How was this patch tested?

Built Hive locally.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao Thanks.

**Comment by sunchao** [comment]
@viirya I wonder if we can create another PR targeting branch-2. It seems there is minimum conflict between branch-2.3 and branch-2 for this, and the testing seems to be working for branch-2 (see [this](https://github.com/apache/hive/pull/1234) as example).

**Comment by viirya** [comment]
@sunchao OK, let me try it. But I think by the end the 2.3.8 should be from branch-2.3, right?

**Comment by sunchao** [comment]
Yes that's right. If tests pass on branch-2 we can cherry-pick this to branch-2.3 and probably commit it directly, I think.

**Pull request closed without merging**
