### PR TITLE
Introduce gRPC Proto Definition

### PR DESCRIPTION
**Pull request by rohansonecha**
Change-Id: I38dd936e4ad710e05e95d78f05b5e07585cb1660

### What changes were proposed in this pull request?

This pull request adds a new proto3 file which was based off of the existing hive_metastore.thrift file. The proto3 file is complete with all the requisite object and method header definitions to implement native gRPC support for Hive Metastore. This doesn’t include the same method with different signature, i.e. get_databases(string db_id) is usurped by get_databases(GetDatabasesRequest request).

The necessary dependencies were also added to the relevant pom.xml files to enable gRPC support.

### Why are the changes needed?

The proto file is necessary because in order to have native gRPC support in Hive Metastore, there needs to be gRPC equivalents of all the preexisting Thrift objects as well as method header definitions in gRPC for Thrift counterparts. 

### Does this PR introduce _any_ user-facing change?

Not yet, while this will allow developers to use this proto to generate clients (i.e. in Impala) before full support for gRPC is added in Hive Metastore.

### How was this patch tested?

No tests were added in this PR other than making sure that the proto file and pom.xml files compile without issues and checking the target/ directory for generated files.

### CODE REVIEW

**Comment by deniskuzZ** [comment]
hi @rohansonecha, thank you for submitting the PR. Is there an upstream JIRA to track this activity?

**Comment by rohansonecha** [comment]
Hello @deniskuzZ, yes there is. I have linked the JIRA ticket here: (https://issues.apache.org/jira/browse/HIVE-26484).

**Review by deniskuzZ — APPROVED** [review]
LGTM +1

**Comment by deniskuzZ** [comment]
hi @rohansonecha, are you planning on contributing to Hive gRPC support? This PR looks abandoned and would be marked as stale after a while.

**Pull request closed without merging**
