### PR TITLE
HIVE-17155: findConfFile() in HiveConf.java has some issues with the conf path

### PR DESCRIPTION
**Pull request by baibaichen**
Cherry pick HIVE-17155 from master branch

### What changes were proposed in this pull request?
make `findConfigFile` can handle jar protocol

### Why are the changes needed?
When **spring-boot-maven-plugin** is used, we use  `java -jar` to launch program, and have to use  `org.springframework.boot.loader.LaunchedURLClassLoader` to load class, in such case, jar protocol is used.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
current UT

### CODE REVIEW

**Comment by baibaichen** [comment]
This PR just change initialized code path, don't know why it failed

**Comment by baibaichen** [comment]
retest please

**Comment by wangyum** [comment]
cc @sunchao

**Review by sunchao — APPROVED** [review]
LGTM - will merge soon.

**Comment by baibaichen** [comment]
@sunchao could it be included in hive 2.3.8? I think this issue is low risk, but we need it for spark 3

**Comment by wangyum** [comment]
Hive 2.3.8 has been released.

**Comment by sunchao** [comment]
Yes Hive 2.3.8 is already released and Spark has upgraded to it in the master branch. This will be included in the 2.3.9 release (no date yet).

**Comment by baibaichen** [comment]
Thanks

**Pull request merged**
