### PR TITLE
HIVE-14483

### PR DESCRIPTION
**Pull request by szador87**
Fix java.lang.ArrayIndexOutOfBoundsException org.apache.orc.impl.TreeReaderFactory$BytesColumnVectorUtil.commonReadByteArrays

### CODE REVIEW

**Comment by prasanthj** [comment]
+1, lgtm

**Comment by lidialiker** [comment]
any chance this is getting merged? I'm seeing this exception as well when using ORC file format in Pig with OrcStorage.

**Comment by szador** [comment]
Fix Version/s: 1.3.0, 2.2.0, 2.1.1, 2.0.2

**Comment by lidialiker** [comment]
@szador thanks!

**Pull request closed without merging**
