### PR TITLE
HIVE-27451: Upgrade Kafka dependencies to latest 3.5.0

### PR DESCRIPTION
**Pull request by akshat0395**
### What changes were proposed in this pull request?

[HIVE-27451](https://issues.apache.org/jira/browse/HIVE-27451)

### Why are the changes needed?

Keeping Kafka dependencies upto date

### Does this PR introduce _any_ user-facing change?

No
### Is the change a dependency upgrade?

Yes

### How was this patch tested?

Existing UT

### CODE REVIEW

**Comment by akshat0395** [comment]
Dependency Tree post upgrade: [kafkaUpgrade.txt](https://github.com/apache/hive/files/11787505/kafkaUpgrade.txt)

**Review by kokila-19 — APPROVED** [review]

**Review by zabetak — CHANGES_REQUESTED** [review]
The Kafka upgrade to 3.4.0 broke badly the Kafka storage handler. I don't think we are/were ready for an upgrade. Actually, at this stage I think that a downgrade to the old version (i.e., 2.5.0) is preferred.

**Comment by difin** [comment]
@akshat0395 more context on the previous upgrade [PR-4082](https://github.com/apache/hive/pull/4082):
It was needed to shade zstd-jni in hive-ql after upgrading parquet version dowstream, otherwise Tez couldn't work with parquet and zstd encryption. Parquet and kafka-client both use zstd-jni. In PR-4082 I upgraded kafka-client to latest version which used zstd-jni version close to the version in parquet.

**Comment by akshat0395** [comment]
Moving forward with a downgrade in Kafka version as of this point, closing this PR.
PR for downgrade: #4460

**Pull request closed without merging**
