### PR TITLE
HIVE-26381: Fix link in Javadoc of MetaStoreUtils::getCurrentClassPaths

### PR DESCRIPTION
**Pull request by xuzifu666**

### CODE REVIEW

**Comment by xuzifu666** [comment]
@ayushtkn have a review please，link in MetaStoreUtils.java is error，and fix it，thanks

**Comment by ayushtkn** [comment]
@xuzifu666 can you create a Hive jira as well, and add the jira id in the title of the PR. 
Rest code change looks good.
example:
https://issues.apache.org/jira/browse/HIVE-25001

**Comment by xuzifu666** [comment]
> @xuzifu666 can you create a Hive jira as well, and add the jira id in the title of the PR. Rest code change looks good. example: https://issues.apache.org/jira/browse/HIVE-25001

done，thanks ~

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
