### PR TITLE
HIVE-26631: Remove unused variable requestTimeout and beBackoffSlotLength in the initServer method of the ThriftBinaryCLIService class

### PR DESCRIPTION
**Pull request by xiuzhu9527**
### What changes were proposed in this pull request?

1. Remove variable requestTimeout and beBackoffSlotLength in method initServer of class ThriftBinaryCLIService
2. Remove hive.server2.thrift.exponential.backoff.slot.length and hive.server2.thrift.login.timeout in HiveConf

### Why are the changes needed?

Remove unused variable and hiveConf for ThriftBinaryCLIService class

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by xiuzhu9527** [comment]
@ayushtkn I was wondering if you got the chance to read my PR？I will thank you very much！

**Review by zabetak — APPROVED** [review]
LGTM. @xiuzhu9527 can you please check which commit/JIRA ticket made these variables unused and if it was intentional? Then add this information and the respective links under the current ticket.

**Review by zabetak — CHANGES_REQUESTED** [review]
Changing my vote; let's first confirm that the changes which made the variables unused were intentional. I have some doubts.

**Comment by xiuzhu9527** [comment]
@zabetak  I don't think the variables unused are intentional. In thrift issuse（https://issues.apache.org/jira/browse/THRIFT-5297 ），the parameters requestTimeout and beBackoffSlotLength are removed, because it adds a lot of complexity to the code and doesn't make a whole lot of sense.

**Review by zabetak — APPROVED** [review]
After the latest discussion here and under the JIRA I am convinced that it makes sense to remove the unused configuration parameters.

**Pull request closed without merging**
