### PR TITLE
HIVE-24225: Revert HIVE-23158 Optimize S3A recordReader policy for Random IO formats

### PR DESCRIPTION
**Pull request by pgaref**
This reverts commit c87e60d4

Change-Id: Ie8b783e0b1e0e32d9a54f6663e9aae5dd0a0f94f

### CODE REVIEW

**Review by abstractdog — APPROVED** [review]

**Comment by steveloughran** [comment]
why the revert?

**Comment by pgaref** [comment]
Hey @steveloughran  --- the approach of the above patch was a bit off, one problem was that the Fs objects were lazility initalized and could end up throwing exceptions when setting the option eagerly.
The most important issue was that the LLAP IO creates its own FS object (and the above where only used for output).

A solution for all this could be the S3A **openFileWithOptions**  call that adds file options for the open File call instead of on the FS (still needs to add support for **fadvise**  though)
https://github.com/apache/hadoop/blob/trunk/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L4828

**Comment by steveloughran** [comment]
you actually want to use the openFile() API Call which is already in hadoop-3.3, but which is being tweaked (https://github.com/apache/hadoop/pull/2168) to have a standard option for seek policy for all object stores, and the ability to pass in file length -which will let the S3A & ABFS connectors skip a head probe

```java
  @Override
  public SeekableInputStream newStream() throws IOException {
    FutureDataInputStreamBuilder builder = fs.openFile(getPath())
      .opt("fs.s3a.experimental.input.fadvise", "random")  // supported in Hadoop 3.3.0
      .opt("fs.option.openfile.fadvise", "random");     // this will be the new standard one

    if (length > 0) {
      builder.opt("fs.option.openfile.length", length);    // also in the PR. Pass in the end of the split & s3a will be happy too
    }
    CompletableFuture<FSDataInputStream> streamF = builder.build();
    return HadoopStreams.wrap(FutureIOSupport.awaitFuture(streamF));
  }
```

That API is there today, if you want to try playing with it,.

**Comment by steveloughran** [comment]
(that openFileWithOptions() is how the openFile() is implemented, it's not meant to be the API call which apps make. That's covered: [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/filesystem/fsdatainputstreambuilder.html)

**Pull request merged**
