### PR TITLE
HIVE-27814: Support VIEWs in data connectors (Naveen Gangam)

### PR DESCRIPTION
**Pull request by nrg4878**
### What changes were proposed in this pull request?
Currently, the JDBC providers only support TABLE types for metadata federation. This PR is to enhance this so VIEW type can also be federated. These will also show up as tables in hive.

### Why are the changes needed?
Enhancement to existing functionality.

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
Manually

### CODE REVIEW

**Comment by nrg4878** [comment]
@zhangbutao Could you please review as well?

**Comment by zhangbutao** [comment]
//1 create a view in mysql
`mysql> create view testview as select count(*) from test;`

// 2 show view info in mysql
```
mysql> show create table testview;
+----------+--------------------------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| View     | Create View                                                                                                                                | character_set_client | collation_connection |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| testview | CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `testview` AS select count(0) AS `count(*)` from `test` | utf8                 | utf8_general_ci      |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
1 row in set (0.01 sec)
```


//3  show view info using hive beeline
```
jdbc:hive2://localhost:10000/default> show create table testview;
+----------------------------------------------------+
|                   createtab_stmt                   |
+----------------------------------------------------+
| CREATE EXTERNAL TABLE `testview`(                  |
|   `count(*)` bigint COMMENT 'from deserializer')   |
| ROW FORMAT SERDE                                   |
|   'org.apache.hive.storage.jdbc.JdbcSerDe'         |
| STORED BY                                          |
|   'org.apache.hive.storage.jdbc.JdbcStorageHandler'  |
| WITH SERDEPROPERTIES (                             |
|   'serialization.format'='1')                      |
| TBLPROPERTIES (                                    |
|   'hive.sql.database.type'='MYSQL',                |
|   'hive.sql.dbcp.password'='XXXXXXX',           |
|   'hive.sql.dbcp.username'='root',                 |
|   'hive.sql.jdbc.driver'='com.mysql.jdbc.Driver',  |
|   'hive.sql.jdbc.url'='jdbc:mysql://localhost:3306/testdb',  |
|   'hive.sql.schema'='testdb',                      |
|   'hive.sql.table'='testview')                     |
+----------------------------------------------------+
```

As we can see, it seems that `show create table` on a remote view has incorrect collumn name(count(*)). Can we say this is a problem? Should we be in line with mysql's `show create table` view?

**Comment by nrg4878** [comment]
@zhangbutao Typically, aggregates have column aliases to help understand what it represents. For example,
create view test_view as select count(*) as row_count from test_table;

If you then describe this view, the column name will be "row_count" instead of "count(*)". In Hive, we will then display row_count.

Even in the current scenario, it should work if you do a select * from the_view from hive. It will show that the value of the column "count(*)" will be whatever is returned. Or is it actually returning count(count(*)) as 1?

**Comment by zhangbutao** [comment]
@nrg4878 Thanks for explanation. `select * from the_view` from hive will return correct result. But if users don't know this is a view and will mistake `count(*)` for the  table column, then do a `select count(*) from the_view`,  the result will always return 1.

What i want to say, should we give a hint(e.g. table property) to let users know this is a view, and you must use `select * from the_view` to get the correct result.

BTW, this change is much small, we can first get it in and then think how to make it more easy-to-use.  So LGTM +1.

**Review by zhangbutao — APPROVED** [review]
+1

**Comment by nrg4878** [comment]
I had given it some thought before, whether if we should only show tables via "show tables" query and the views will only be shown via "show views" in hive. This would eliminate any confusion.

This will need changes to the IDataConnector interface, maybe new APIs getViewNames() and getView() or changes to existing one getTableNames(type) and getTable(type). This was the only reason I did not take that route. 

Maybe it is worth exploring it. What do you think ?

**Comment by zhangbutao** [comment]
> Maybe it is worth exploring it. What do you think ?

@nrg4878 Sure, it is very worth exploring and sounds interesting. Making a change on IDataConnector interface looks like the right way to go,

**Review by dengzhhu653 — APPROVED** [review]

**Pull request closed without merging**
