### PR TITLE
HIVE-26114: Fix jdbc connection hivesrerver2 using dfs command with prefix space will cause exception

### PR DESCRIPTION
**Pull request by zzzzming95**
### What changes were proposed in this pull request?

fix hive command Operation bug .

### Why are the changes needed?

jdbc connection hivesrerver2 using dfs command with prefix space will cause exception.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

```
        Connection con = DriverManager.getConnection("jdbc:hive2://10.214.35.115:10000/");
        Statement stmt = con.createStatement();
        // dfs command with prefix space or "\n"
        ResultSet res = stmt.executeQuery(" dfs -ls /");
        //ResultSet res = stmt.executeQuery("\ndfs -ls /");
```

### CODE REVIEW

**Comment by zzzzming95** [comment]
@deniskuzZ @pvary @sankarh @adesh-rao @zabetak

It's a simple bug. could you guys please review the PR?

**Comment by pvary** [comment]
@zzzzming95: Can we have a unit test which fails before the patch, and runs successfully after the patch?
Maybe `TestBeeLineDriver`, or `TestBeeLineWithArgs`, or something like them

**Comment by zzzzming95** [comment]
@pvary 

sorry for the late response...  I'll add some UTs later.

**Comment by zzzzming95** [comment]
@kgyrtkirk 
Test unstable, please rebuild CI.

@pvary  @nrg4878 
I add a UT, please review again. 

Thanks ~

**Comment by pvary** [comment]
@zzzzming95: You can rerun the tests from the jenkins UI. I restarted them, so if we have a green run, we can merge.

Thanks,
Peter

**Review by pvary — APPROVED** [review]

**Comment by pvary** [comment]
Also started a flaky test checker for the failed test, to see if it is indeed flaky: http://ci.hive.apache.org/job/hive-flaky-check/559/

**Comment by pvary** [comment]
@zzzzming95: Please ping me later if we have further results here. I expect to be busy this week, and forget things 😄

**Comment by zzzzming95** [comment]
@pvary 

Now run green , please merge this pr . thanks ~

**Comment by pvary** [comment]
@zzzzming95: Any preferred name to use in the commit log? The only full name I have found is `Shezm`
It would look like this:

> HIVE-26114: Fix jdbc connection hivesrerver2 using dfs command with prefix space will cause exception (Shezm reviewed b Peter Vary)

**Comment by zzzzming95** [comment]
@pvary 

> HIVE-26114: Fix jdbc connection hivesrerver2 using dfs command with prefix space will cause exception (Shezm reviewed b Peter Vary)

It is OK ~

**Pull request merged**
