### PR TITLE
HIVE-26757: Add sfs+ofs support

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds sfs+ofs support to mirror sfs+o3fs. ofs is a newer protocol by Ozone that's meant to replace o3fs.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@kgyrtkirk this looks like all that was done to include o3fs support. However I haven't been able to get it working, I still run into `org.apache.hadoop.fs.UnsupportedFileSystemException No FileSystem for scheme "sfs+ofs"` trying to use it in Impala. Any ideas on things I've missed?

**Comment by kgyrtkirk** [comment]
looks enough to me; if it works via cmdline with something like
```
export ??=ql.jar
hadoop dfs -ls sfs+file:///etc/passwd
hadoop dfs -ls sfs+ofs://...
```
if that works then the problem will be on the impala side...

**Comment by MikaelSmith** [comment]
Ok, that test with my jar built from source works with ofs now. Do you have any suggestions for tests? I didn't really see any covering the other filesystems.

**Comment by abstractdog** [comment]
I don't know the implementation details of the original SingleFileSystem, but the manner of addition looks convenient, so this patch also looks good to me
we haven't added tests for specific underlying filesystems so far, if manual tests worked for ofs, this is good to go

**Review by abstractdog — APPROVED** [review]

**Review by kgyrtkirk — APPROVED** [review]

**Pull request merged**
