### PR TITLE
Revert "HIVE-28417: Bump Log4j2 to 2.24.1 to facilitate compilation of GraalVM Native Image"

### PR DESCRIPTION
**Pull request by zhangbutao**
Reverts apache/hive#5375

Try to resolve [HIVE-28611](https://issues.apache.org/jira/browse/HIVE-28611)

### CODE REVIEW

**Review by deniskuzZ — APPROVED** [review]
+1

**Review by okumin — APPROVED** [review]
Checked this would correctly revert https://github.com/apache/hive/pull/5375/files

**Comment by zhangbutao** [comment]
https://github.com/apache/hive/pull/5530 is trying to fix the skipped tests issue by upgrading Maven SureFire Plugin. Let's disscuss if we can merge https://github.com/apache/hive/pull/5530 to fix the issue.

**Comment by deniskuzZ** [comment]
@zhangbutao, I've reverted to unblock everyone.

**Comment by zhangbutao** [comment]
> @zhangbutao, I've reverted to unblock everyone.  original upgrade PR is supposed to have that change.

No problem we can revert it first. we can continue to test HIVE-28417 after HIVE-28519 is merged.

**Pull request merged**
