### PR TITLE
HIVE-27077: Upgrade to Antlr4

### PR DESCRIPTION
**Pull request by mlorek**
### What changes were proposed in this pull request?
new module to host antlr4 based hive grammar

### Why are the changes needed?
to phase out obsolete antlr3 based grammar

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
build

### CODE REVIEW

**Comment by mlorek** [comment]
@zabetak can you recommend any reviewer?

**Comment by zabetak** [comment]
@mlorek Thanks for the PR. I don't think the PR can go in as it is right now. We cannot maintain two different grammars for v3 and v4 and as it is right now the v4 proposal has zero test coverage. 

Are you planning to create follow-up tasks? What's your final goal?

**Comment by mlorek** [comment]
> @mlorek Thanks for the PR. I don't think the PR can go in as it is right now. We cannot maintain two different grammars for v3 and v4 and as it is right now the v4 proposal has zero test coverage.
> 
> Are you planning to create follow-up tasks? What's your final goal?

my plan was to implement new parser that uses antlr 4.
to start that work we still need antlr4 grammar and a new module, and I am happy to maintain it

**Comment by zabetak** [comment]
@mlorek Can you please send an email to dev@hive with a concrete proposal of what you are trying to achieve. From my perspective it is still not completely clear what's the end goal and how we are going to move towards it.

Some quick questions from the top of my mind:
* Is the idea to keep both v3 and v4 parsers?
* Are the parers gonna be functionally equivalent?
* How are we gonna test the new parser?
* Which parser will be used in tests?
* What are the advantages of having/moving to v4?
* Are there any disadvantages?

**Comment by TuroczyX** [comment]
Sorry for dumb question but where do we use antlr? It is in the query analyzer or in the parser?  
Also what is the purpose of this library here?  (I'm not familiar with that and I'm asking because I'm curious :) ) 

Does this change introduce any breaking change? As I see from the antlr page it is 20% faster the 4 then the previous which is nice. Also in the hive 4 (4.1?) we are able to introduce if it won't introduce breaking change.  

But It would be great to have an understating of the risks and motivation.

**Comment by zhangbutao** [comment]
Antlr3 has been lost support long long ago. It will be great to upgrade to Antlr4. Antrl4 grammar is more simple and cleaner than Antlr3. 
But i think it is not easy to do this, there is maybe some Incompatibilities need to be fixed.
Please see this ticket: https://issues.apache.org/jira/browse/HIVE-23177
@mlorek Could you please give more feadback? Thanks.

**Comment by deniskuzZ** [comment]
@kasakrisz haven't we already upgraded to ANTLR 4?

**Comment by kasakrisz** [comment]
@deniskuzZ 
AFAIK Hive uses antlr in 3 cases:
1. Sql query parser - antlr 3
2. HPL/SQL parser - antlr 4
3. Filter expression parser when pulling partition metadata via hms api - this was recently upgraded to antlr 4

**Comment by zabetak** [comment]
The pre-commit tests have run 9 times so far for this PR while its context and purpose remain unclear. I am closing this down to avoid wasting more cloud resources. Let's use the respective HIVE-27077 or dev@ list to reach some consensus before re-opening this PR.

**Pull request closed without merging**
