### PR TITLE
HIVE-26450: Use a lightweight oracle image

### PR DESCRIPTION
**Pull request by abstractdog**
### What changes were proposed in this pull request?
Changing oracle docker image.

### Why are the changes needed?
Optimizing precommit.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
```
mvn install  -Pitests,iceberg -Dtest=TestMiniLlapLocalCliDriver -Dqfile=jdbc_table_with_schema_oracle.q,qt_database_all.q,qt_database_oracle.q
```

### CODE REVIEW

**Review by zabetak — APPROVED** [review]
+1 pending tests. The size difference between the images is impressive.

**Comment by abstractdog** [comment]
passes locally, fails in precommit, currently checking, reproduced with flaky-check: http://ci.hive.apache.org/job/hive-flaky-check/577/
```
docker: Error response from daemon: manifest for gvenzl/oracle-xe:18.4.0-slim not found.
See 'docker run --help'.
```

**Comment by zabetak** [comment]
> which is LOL, this image does exist, this command works locally:

Are the docker versions the same (locally and in the container)?

**Comment by zabetak** [comment]
```bash
$ docker manifest inspect gvenzl/oracle-xe:18.4.0-slim
no such manifest: docker.io/gvenzl/oracle-xe:18.4.0-slim
```
```bash
$ docker manifest inspect pvargacl/oracle-xe-18.4.0:latest
{...}

**Pull request merged**
