### PR TITLE
HIVE-21489: EXPLAIN command throws ClassCastException in Hive

### PR DESCRIPTION
**Pull request by ramesh0201**

### CODE REVIEW

**Comment by zeroflag** [comment]
LGTM, with one note, both SemanticAnalyzer and ExplainSemanticAnalyzer extends from BaseSemanticAnalyzer, wouldn't have made sense to put the getter there?

**Comment by ramesh0201** [comment]
@zeroflag thanks for the review, did I address your comment completely?

**Comment by zeroflag** [comment]
@ramesh0201 the pCtx is both defined in the base class and in the subclass. This can be confusing. Isn't it enough to only define it in the base and use the inherited field in the subclass?

**Comment by ramesh0201** [comment]
@zeroflag  That makes sense. I have updated the patch. Can you please take a look at this?

**Comment by zeroflag** [comment]
@ramesh0201 thanks, LGTM +1

**Review by pgaref — APPROVED** [review]

**Pull request merged**
