### PR TITLE
HIVE-28165: HiveSplitGenerator: send splits through filesystem instead of RPC in case of big payload

### PR DESCRIPTION
**Pull request by abstractdog**
This simply reopens https://github.com/apache/hive/pull/5174 after tez 0.10.4 is released

### CODE REVIEW

**Comment by abstractdog** [comment]
@deniskuzZ : very same bits as approved in https://github.com/apache/hive/pull/5174, can you please approve this one as well? now it's unblocked due to released Tez 0.10.4

**Comment by abstractdog** [comment]
there is a failing test, need to check tomorrow:
https://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-5449/1/tests

**Review by deniskuzZ — APPROVED** [review]
LGTM +1, pending tests

**Comment by abstractdog** [comment]
totally unrelated failures due to docker problems, grr:
https://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-5449/2/tests
restarting test

**Pull request merged**
