### PR TITLE
HIVE-27864 Update plugin for SBOM generation to 2.7.10

### PR DESCRIPTION
**Pull request by VinodAnandan**
### What changes were proposed in this pull request?

Update the CycloneDX Maven plugin for SBOM generation to 2.7.10

### CODE REVIEW

**Comment by ayushtkn** [comment]
Can you create a Jira for this & prefix that in the title like HIVE-XXXX: Update...

**Review by aturoczy — APPROVED** [review]
+1

**Comment by VinodAnandan** [comment]
> Can you create a Jira for this & prefix that in the title like HIVE-XXXX: Update...

@ayushtkn Done

**Review by ayushtkn — APPROVED** [review]
LGTM

**Pull request merged**
