### PR TITLE
HIVE-27261: Backport HIVE-27258 to branch-3

### PR DESCRIPTION
**Pull request by vihangk1**
### What changes were proposed in this pull request?
This PR backports HIVE-27258 to branch-3 since the issue also affects branch-3.

### Why are the changes needed?
Backport HIVE-27261 to branch-3

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing unit tests cover this functionality.

### CODE REVIEW

**Comment by vihangk1** [comment]
The test which is failing doesn't fail for me on my local when I run the split. Also, looks totally unrelated. I think we should disable it for now and investigate it separately. @amanraj2520 What do you think?

**Comment by amanraj2520** [comment]
@vihangk1 I think we can disable the test. Looks like it fails because of some thrift connection issue. If this passes in the local it should be fine according to me.

**Review by amanraj2520 — APPROVED** [review]
+1 LGTM

**Comment by amanraj2520** [comment]
I retriggered and the failing test passed. Some other intermittent issue came up again. This is good to merge

**Comment by vihangk1** [comment]
Thanks @amanraj2520. Merged into branch-3.

**Pull request merged**
