### PR TITLE
HIVE-24571: Redundant code in SemanticAnalyzer.java file

### PR DESCRIPTION
**Pull request by zzccctv**
ParseDriver pd = new ParseDriver() 
This code is redundant code, it is recommended to delete it

### CODE REVIEW

**Comment by zzccctv** [comment]
@kgyrtkirk checks have failed，It seems to be caused by the Jenkins environment

**Comment by kgyrtkirk** [comment]
yes @zzccctv ; something wierd have happened - I never seen something like this :D

**Comment by kgyrtkirk** [comment]
oh..now I see that these changes are for branch-2. Could you please file a "HIVE" jira about this issue? And the best would be to submit the changes against the master branch first!
You might find some usefull (and optionally outdated) info in this guide: https://cwiki.apache.org/confluence/display/Hive/HowToContribute

**Comment by zzccctv** [comment]
OK,To solve the problem, I have set up an issues in JIRA,@kgyrtkirk

**Review by miklosgergely — APPROVED** [review]

**Comment by zzccctv** [comment]
@miklosgergely @kgyrtkirk It seems to be caused by the Jenkins environment. Can I submit to other branch-2？

**Pull request merged**
