### PR TITLE
HIVE-25495: Upgrade to JLine3

### PR DESCRIPTION
**Pull request by belugabehr**

### CODE REVIEW

**Comment by kgyrtkirk** [comment]
is this dependency update is being tied to the hadoop-3.3 upgrade?

**Comment by belugabehr** [comment]
@kgyrtkirk Ya, I can't get HMS to work because of clashes with JLine 2.x and JLine 3.x (Hadoop 3.3+)

**Comment by kgyrtkirk** [comment]
sqlline already seems to be pulling in some `org.jline` dependencies in the metastore-server module - so we might be already in trouble....
```
[INFO] +- sqlline:sqlline:jar:1.9.0:compile
[INFO] |  +- org.jline:jline-terminal:jar:3.12.1:compile
[INFO] |  +- org.jline:jline-reader:jar:3.12.1:compile
[INFO] |  +- org.jline:jline-terminal-jansi:jar:3.12.1:compile
[INFO] |  |  \- org.fusesource.jansi:jansi:jar:1.18:compile
[INFO] |  +- org.jline:jline-terminal-jna:jar:3.12.1:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:5.3.1:compile
[INFO] |  \- org.jline:jline-builtins:jar:3.12.1:compile
[INFO] |     \- org.jline:jline-style:jar:3.12.1:compile
[INFO] +- jline:jline:jar:2.14.6:compile
```

looking at a dependency:tree of master I've not seen jline deps in any hadoop-3.1.0 related artifacts

however I've seen some explicit excludes for jline deps in the hadoop project - so it might be possible that the dep sneaked in during a 3rd party dep upgrade?
it seem to be coming when we use hadoop-3.3.1 like this:
```
[INFO] |  +- org.apache.hadoop:hadoop-yarn-client:jar:3.3.1:compile (optional) 
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-client:jar:9.4.40.v20210413:compile (optional) 
[INFO] |  |  |  +- org.eclipse.jetty:jetty-client:jar:9.4.40.v20210413:compile (optional) 
[INFO] |  |  |  |  \- org.eclipse.jetty:jetty-http:jar:9.4.40.v20210413:compile (optional) 
[INFO] |  |  |  +- org.eclipse.jetty:jetty-util:jar:9.3.27.v20190418:compile (optional) 
[INFO] |  |  |  +- org.eclipse.jetty:jetty-io:jar:9.4.40.v20210413:compile (optional) 
[INFO] |  |  |  \- org.eclipse.jetty.websocket:websocket-common:jar:9.4.40.v20210413:compile (optional) 
[INFO] |  |  |     \- org.eclipse.jetty.websocket:websocket-api:jar:9.4.40.v20210413:compile (optional) 
[INFO] |  |  \- org.jline:jline:jar:3.9.0:compile (optional) 
```
I'm not sure if hadoop is really using it...the 3.1.0 hadoop-yarn-client also haven't dragged in a jetty.websocket as a transitive dependency...

**Comment by kgyrtkirk** [comment]
it was added in: [YARN-8778](https://github.com/apache/hadoop/commit/27ffec7ba77ba)

**Comment by ayushtkn** [comment]
@kgyrtkirk I think that was intentional only, Atleast the JLine one is:
https://issues.apache.org/jira/browse/YARN-8778?focusedCommentId=16650922&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16650922

**Pull request closed without merging**
