### PR TITLE
HIVE-25635: Upgrade libthrift from 0.14.1 to 0.16.0

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by slachiewicz** [comment]
replaces [#2739](https://github.com/apache/hive/pull/2739)

**Comment by kgyrtkirk** [comment]
it seems like this patch seem to have missed ~300 generated files ; some are under `service-rpc` and under the `serde` module; and theres also a few under `ql`

have you rebuilt the *full* project with `-Pthriftif` ?

**Comment by slachiewicz** [comment]
Unfortunately no. I saw only profile in one module and haven't had checked it in others.  

Unfortunately not all I can test locally (Protobuf3 issue).

Thx for checking. I'll try to work on other mentioned modules in next few days

**Comment by slachiewicz** [comment]
i've regenerated thrift code - let's see what ci says https://github.com/apache/hive/commit/e2decb298c73dfd127d9fc91daa68f5ce8303867 

i use macOS M1 with aarch64  and fresh java - and with old protobuf this is not yet supported. that's why i started with offering PR for protobuf in other tickets. Snappy upgrade is also one of those steps to fix build process. 
Hope slowly it can be fixed and we can build project with Java 17 ;-)

**Review by kgyrtkirk — APPROVED** [review]
branch now has the same content as I have in my local branch
+1 pending tests

**Pull request merged**
