### PR TITLE
HIVE-21488 Update Apache Parquet to 1.10.1

### PR DESCRIPTION
**Pull request by Fokko**
Fixes two bugs which were discovered in Apache Spark:
https://github.com/apache/parquet-mr/blob/master/CHANGES.md#version-1101

### CODE REVIEW

**Comment by rmsmani** [comment]
Hi @Fokko 
What's the hive Jira number for this...
If Jira is not available, then please create Jira card, 
1. Create git diff patch
2. Upload the patch to Jira 
3. Then submit patch

**Comment by Fokko** [comment]
I've opened up a ticket: https://jira.apache.org/jira/browse/HIVE-21488

**Comment by rmsmani** [comment]
Thanks, please submit the patch file in Jira.

**Comment by Fokko** [comment]
Thanks @rmsmani, I've submitted the patch.

Would it be possible to backport this to Hive 2.x as well?

**Comment by belugabehr** [comment]
The `master` branch is already at Parquet 1.11.0. thereby obsoleting this request:

https://issues.apache.org/jira/browse/HIVE-22648

If however you want this to be in Hive2 then you will need to open a new PR with a PR against Hive `branch-2`

**Pull request closed without merging**
