### PR TITLE
HIVE-27292 : Upgrade Zookeeper to 3.7.1

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-27292

Zookeper 3.6.3 is End of Life (https://endoflife.date/zookeeper)

### CODE REVIEW

**Comment by amanraj2520** [comment]
@TuroczyX I agree we can upgrade to 3.8.x but according to me it will be a major version upgrade and it would require some time to test it. Personally, I do not have an issue with this, it is just that I have run all the tests in my local keeping 3.7.1 in mind. I suggest that we can create a follow up ticket to upgrade it to 3.8.x. But if the community agrees, I can bump it to 3.8.x. Let me know your thoughts.

**Comment by TuroczyX** [comment]
Agree with your points. Let's merge this one, because we could just win with this, and let's have a follow up PR with 3.8.1.

Btw: 3.7 was even bigger release :) But I guess it should work, as I remember we did not had to many problem with zookeeper versions in the past.

**Comment by amanraj2520** [comment]
@TuroczyX Raised this draft PR - https://github.com/apache/hive/pull/4270. Will upgrade it after testing. Meanwhile if this 3.7.1 change looks good to you can you please approve this.

**Comment by TuroczyX** [comment]
@deniskuzZ Could you please check and if it is ok merge?

**Comment by deniskuzZ** [comment]
@amanraj2520 should we wait for https://github.com/apache/hive/pull/4270? I've just re-triggered it

**Comment by rakeshadr** [comment]
> Agree with your points. Let's merge this one, because we could just win with this, and let's have a follow up PR with 3.8.1.
> 
> Btw: 3.7 was even bigger release :) But I guess it should work, as I remember we did not had to many problem with zookeeper versions in the past.
> 
> PS: With a draft PR we can try it out quickly the 3.8
Hi [aturoczy](https://github.com/aturoczy),
I agree to move to 3.8.1. 
On the other side, I'd really appreciate if you could give references about the 3.7.1 deprecation plans.  I could see https://zookeeper.apache.org/releases.html still says that 3.7.1 is a stable release.

**Comment by amanraj2520** [comment]
@zabetak @ayushtkn @abstractdog Can we please merge this.

**Review by zabetak — APPROVED** [review]
LGTM. Will merge this now!

**Comment by zabetak** [comment]
@deniskuzZ I think there are some legitimate failures in https://github.com/apache/hive/pull/4270 so don't think we should wait for that one; it can go in when its ready.

**Comment by aturoczy** [comment]
@rakeshadr I track the libs / components lifecycle on this page. https://endoflife.date/zookeeper 
It is pretty accurate.

**Comment by ayushtkn** [comment]
Late into the party. But for the fact, it isn't zookeeper upgrades are too calm, actually none of the dependency upgrades are calm. ex. Hadoop's Zookeeper upgrade to 3.8.1 is in a mess : https://github.com/apache/hadoop/pull/5345

btw. do we plan to upgrade curator as well to 5.4.0? that seems to be the one supporting zk 3.7.1([CURATOR-596](https://issues.apache.org/jira/browse/CURATOR-596)), good to do so if possible

**Pull request closed without merging**
