### PR TITLE
HIVE-25506 - Ignore mulitple password sources in JdbcStorageHandler.

### PR DESCRIPTION
**Pull request by harishjp**
Removing multiple source check to prevent job failure. 

Tested using UT and in a cluster with these changes.

### CODE REVIEW

**Review by nrg4878 — APPROVED** [review]
Just a quick thought
For the test change below, the test is checking to ensure that the order of precedence for password is 1) properties 2) keystore 3) password store
should we add a comment in here as well that the test can change if this order is changed (moving to the most secure form first) or if a change is made in the future that only allows one of the passwords to be set

**Comment by harishjp** [comment]
Thanks Naveen.

I’ve added test for precedence of password based against URI, password comes before URI based one, this is to prevent a lookup from happening in tez task. There is no logical reason for keystore to have precedence over URI right now, it is just there. Ideally we should fix it so that once the password is extracted we should not copy the URI or keystore config.

I'll try to do a followup jira on this.

**Comment by nrg4878** [comment]
Fix has been committed to master. Please close the PR. Thank you

**Comment by harishjp** [comment]
Thanks Naveen for the review and merge.

**Comment by nrg4878** [comment]
please close this PR

**Pull request closed without merging**
