### PR TITLE
HIVE-20785: Typo KEQ_SEQ -> KEY_SEQ

### PR DESCRIPTION
**Pull request by Mogztter**
According to the `java.sql.DatabaseMetaData` API the key should be `KEY_SEQ`.

https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getPrimaryKeys-java.lang.String-java.lang.String-java.lang.String-

### CODE REVIEW

**Comment by Mogztter** [comment]
Is there anyone out there ? It's really a major issue with a one line fix... 🤔 
Related JIRA issue: https://issues.apache.org/jira/browse/HIVE-20785

**Comment by Mogztter** [comment]
Friendly ping @prasanthj @pvary :wink:

**Comment by prasanthj** [comment]
lgtm, +1. @Mogztter Sorry just got back from vacation. Could you please upload a patch to HIVE-20785 to trigger precommit tests? Once the test passes I will get this committed.

**Comment by Mogztter** [comment]
@prasanthj No worries. I've uploaded a patch on JIRA but nothing happened...

**Comment by prasanthj** [comment]
I can see your patch already running precommit tests https://builds.apache.org/view/H-L/view/Hive/job/PreCommit-HIVE-Build/15347/parameters/ 

It can take about 1-2 hours for the test to complete and report gets posted automatically to JIRA.

**Comment by Mogztter** [comment]
@prasanthj The build is completed

**Comment by prasanthj** [comment]
@Mogztter feel free to close this PR since the patch has been committed.

**Comment by Mogztter** [comment]
Ok thanks @prasanthj 
Out of curiosity, you don't use GitHub to merge contribution ? Next time I should create a JIRA ticket and upload a patch ?

**Comment by prasanthj** [comment]
Yeah. Not yet. Our current test infra is only integrated with Jira to trigger integration tests. Github PR's only run build as  of now and we use it as an alternative to review board for reviews. So yes hive is not there yet with full integration with github. Yes. Jira + Patch is still required for tests and committing patches. For reviews you can send PR or upload patch to review board.

**Pull request closed without merging**
