### PR TITLE
HIVE-25774: Add ASF license for newly created files in standalone-met…

### PR DESCRIPTION
**Pull request by dengzhhu653**
…astore

### How was this patch tested?
mvn clean apache-rat:check

### CODE REVIEW

**Comment by pvary** [comment]
@dengzhhu653: Could you please check the tests and fix or rerun?
Thanks, Peter

**Comment by dengzhhu653** [comment]
> @dengzhhu653: Could you please check the tests and fix or rerun? Thanks, Peter

Thank you for reminding. The failed build seems unrelated to the changes, I have triggered a new one, hope it can get a green run.

**Comment by dengzhhu653** [comment]
> > @dengzhhu653: Could you please check the tests and fix or rerun? Thanks, Peter
> 
> Thank you for reminding. The failed build seems unrelated to the changes, I have triggered a new one, hope it can get a green run.

Tests have passed，@pvary cloud you please take another look? Thanks.

**Review by pvary — APPROVED** [review]

**Comment by pvary** [comment]
Pushed to master @dengzhhu653!
It might worth to add the rat check to the CI, so we will not face this issue again. Is it possible to do it?

Thanks,
Peter

**Comment by dengzhhu653** [comment]
> Pushed to master @dengzhhu653! It might worth to add the rat check to the CI, so we will not face this issue again. Is it possible to do it?
> 
> Thanks, Peter

Thank you for the merge. Agreed, I will open another jira for this pre check.

**Pull request merged**
