### PR TITLE
HIVE-21737: Upgrade Avro to version 1.10.1

### PR DESCRIPTION
**Pull request by iemejia**
R: @sunchao

### CODE REVIEW

**Comment by sunchao** [comment]
Thanks @iemejia . Can you fix the compilation error?

**Comment by wangyum** [comment]
@sunchao @iemejia Could we release Hive 2.3.8 first?

**Comment by sunchao** [comment]
@iemejia what do you think? do you still plan to get this in 2.3.8? I'm hoping that we can catch the Spark 3.1.0 release train.

@wangyum curious if you have verified whether [this case](https://github.com/apache/spark/pull/26804#issuecomment-714729078) is resolved with Hive 2.3.8. I plan to check this by myself too before starting a new vote.

**Comment by iemejia** [comment]
Yes you are right @sunchao I care about this one, but it seems it opened a pandora box of unrelated dependency issues, it is more important to get into the Spark 3.1.0 release train so let's better go ahead with the vote without this update.

**Comment by wangyum** [comment]
Any update? Spark community has created 3.1.0 RC1: https://github.com/apache/spark/releases/tag/v3.1.0-rc1

**Comment by sunchao** [comment]
I think we just need to verify that the combination of Hive 2.3.8/Parquet 1.11.1/Avro 1.10.1 works for Spark before sending out a vote. @heuermh have you got a chance to try it out? Thanks.

**Comment by heuermh** [comment]
@sunchao With the changes in bigdatagenomics/adam#2289 to remove various workarounds, the combination in pull request https://github.com/apache/spark/pull/30517 works for us.

**Comment by sunchao** [comment]
Thanks @heuermh ! I'll start a vote on Hive 2.3.8 soon.

**Pull request closed without merging**
