### PR TITLE
HIVE-27463: Non-daemon thread prevents HMS from exiting when failed t…

### PR DESCRIPTION
**Pull request by dengzhhu653**
…o start thrift server

### What changes were proposed in this pull request?
Make the start thread non-deamon in order to exit from error when HMS starting

### Why are the changes needed?
If the thrift server has problem in initialization, the process itself will be alive until a force shutdown is triggered, during then the HMS is unable to serve the request.

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
Applied the patch to the suffered process, the issue is gone

### CODE REVIEW

**Comment by dengzhhu653** [comment]
> It wasn't a deamon before? I though it is / was

It wasn't a daemon thread(started from the main thread), the stack trace can also imply that:
```
"Thread-7" #38 prio=5 os_prio=0 tid=0x00007f813313c000 nid=0x12cc waiting on condition [0x00007f80f1581000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$5.run(HiveMetaStore.java:11950)
```
compared to a daemon thread, there is a **daemon** flag in the stack trace: 
```
"Metastore threads starter thread" #37 daemon prio=5 os_prio=0 tid=0x00007f813313a800 nid=0x12cb waiting on condition [0x00007f80f2b1d000]
```

**Review by aturoczy — APPROVED** [review]

**Comment by aturoczy** [comment]
@deniskuzZ @ayushtkn @abstractdog it is a small change, could you pls check?

**Review by deniskuzZ — APPROVED** [review]
LGTM +1, but @dengzhhu653 please fill out the description

**Comment by dengzhhu653** [comment]
> LGTM +1, but @dengzhhu653 please fill out the description

Done, thank you for the review

**Pull request merged**
