### PR TITLE
HIVE-27345: Upgrade commons-dbcp2 to 2.9.0

### PR DESCRIPTION
**Pull request by Aggarwal-Raghav**
### What changes were proposed in this pull request?
Upgrading commons-dbcp2 to 2.9.0

### Why are the changes needed?
To be on the latest version of commons-dbcp2

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Ran the Unit test of standalone-metastore/metastore-server on local machine

### CODE REVIEW

**Comment by Aggarwal-Raghav** [comment]
There is 1 test failure of: **_TestHiveMetaStoreTimeout#testResetTimeout_** and there is already a PR(#4328) HIVE-27343 for fixing this flaky test. Rest all the UT are passing.

**Comment by ayushtkn** [comment]
you need to trigger the tests again and get a green build, we don't merge to master without a green build, even the failure is known to be not related. 

painful but unfortunately that is how things are...

**Comment by Aggarwal-Raghav** [comment]
@ayushtkn, all the tests have passed 👍🏻

**Review by ayushtkn — APPROVED** [review]
Changes LGTM

**Pull request merged**
