### PR TITLE
HIVE-25707: SchemaTool may leave the metastore in-between upgrade steps

### PR DESCRIPTION
**Pull request by DanielZhu58**
### What changes were proposed in this pull request?
We only commit when all the changes in schema upgrade is successful.
Otherwise, we do not commit.

### Why are the changes needed?
Currently, as schematool applies schema changes during an upgrade, each change is autocommitted. So if it fails after applying a few changes from an upgrade file, those changes remain in the schema. So re-running the schematool fails at the first line because that change already exists.

Instead, we should create a transactional boundary between each upgrade file, aka commit only after all the changes in an upgrade file are successful.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Maven build and unit test.

### CODE REVIEW

**Comment by DanielZhu58** [comment]
@saihemanth-cloudera Could you please review this patch? Thank you.

**Review by saihemanth-cloudera — COMMENTED** [review]
-1, Looks like this patch in working as expected

**Comment by DanielZhu58** [comment]
@nrg4878 @saihemanth-cloudera Could you review this patch? Thank you.

**Review by nrg4878 — APPROVED** [review]
Change looks good to me.

**Pull request merged**
