### PR TITLE
HIVE-27749: Addendum: Fix INSERT query

### PR DESCRIPTION
**Pull request by SourabhBadhya**
### What changes were proposed in this pull request?

HIVE-27749: Addendum: Fix INSERT query

### Why are the changes needed?

One column value is missing.

### Does this PR introduce _any_ user-facing change?

No

### Is the change a dependency upgrade?

No

### How was this patch tested?

MariaDB 10.2 env

### CODE REVIEW

**Review by deniskuzZ — APPROVED** [review]
LGTM, pending tests

**Review by aturoczy — APPROVED** [review]
+1 the test is failed but not related to the change.

**Comment by aturoczy** [comment]
Can we move ahead with this change as the test is executed properly?

cc: @ayushtkn @deniskuzZ @SourabhBadhya @abstractdog

**Comment by SourabhBadhya** [comment]
All failing tests are unrelated to the PR. They are mainly JDK timestamp issues due to change in JDK version in #5004. I will proceed with merging since this is a blocker for Hive 4.0 release.
cc @aturoczy @deniskuzZ

**Pull request merged**
