### PR TITLE
HIVE-26330: Beeline client cannot get correct connection url in hive connection using zookeeper

### PR DESCRIPTION
**Pull request by AdobeStu**
### What changes were proposed in this pull request?
to get zookeeper connected string

### Why are the changes needed?
It is confused for users in using beeline to execute sqls with incorrect host. 

### Does this PR introduce _any_ user-facing change?
Yes

### How was this patch tested?
Existing test

### CODE REVIEW

**Comment by AdobeStu** [comment]
Could you please take a look? @pvary @prasanthj

**Comment by pvary** [comment]
Could you please describe the problem a bit more?

I am not entirely sure, but I think the issue you mention is that the user used `url1` for the uri as a connection string in BeeLine, and the prompt shows a different uri instead?

**Comment by AdobeStu** [comment]
> Could you please describe the problem a bit more?
> 
> I am not entirely sure, but I think the issue you mention is that the user used `url1` for the uri as a connection string in BeeLine, and the prompt shows a different uri instead?

Exactly. A zookeeper connection url will be split by ';' and get its substring from the first 45 characters. For example:

we use:
`!connect jdbc:hive2://host1:2181,host2:2181,host3:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2;

then we may get:
`0: jdbc:hive2://host1:2181>`

But actually, we could connect another host and different port like host2:10000.
I believe that this substring aims to help user know which host we has connected, so I changed it.

**Comment by pvary** [comment]
> we use: `!connect jdbc:hive2://host1:2181,host2:2181,host3:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2;`
> 
> then we may get: `0: jdbc:hive2://host1:2181>`

I think it is generated by this code in `BeeLine.java`:
```
  static String getPromptForBeeline(String url) {
    if (url == null || url.length() == 0) {
      url = "beeline";
    }
    if (url.indexOf(";") > -1) {
      url = url.substring(0, url.indexOf(";"));
    }
    if (url.indexOf("?") > -1) {
      url = url.substring(0, url.indexOf("?"));
    }
    if (url.length() > 45) {
      url = url.substring(0, 45);
    }
    return url;
  }
```

So I guess that your URL is 45 char long 😄

**Comment by AdobeStu** [comment]
> > we use: `!connect jdbc:hive2://host1:2181,host2:2181,host3:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2;`
> > then we may get: `0: jdbc:hive2://host1:2181>`
> 
> I think it is generated by this code in `BeeLine.java`:
> 
> ```
>   static String getPromptForBeeline(String url) {
>     if (url == null || url.length() == 0) {
>       url = "beeline";
>     }
>     if (url.indexOf(";") > -1) {
>       url = url.substring(0, url.indexOf(";"));
>     }
>     if (url.indexOf("?") > -1) {
>       url = url.substring(0, url.indexOf("?"));
>     }
>     if (url.length() > 45) {
>       url = url.substring(0, 45);
>     }
>     return url;
>   }
> ```
> 
> So I guess that your URL is 45 char long 😄

If we changed 45 to ... like 450, the substring can only show zhe zookeeper connection url we input like host1:2181,host2:2181,host3:2181. We still can't get server host. For example hiveserver2host:10000

**Comment by pvary** [comment]
> If we changed 45 to ... like 450, the substring can only show zhe zookeeper connection url we input like host1:2181,host2:2181,host3:2181. We still can't get server host. For example hiveserver2host:10000

The question is what do we want to see here:
- The URI which could be used to reconnect to the cluster to rerun the queries
- The specific server's URI to which we are connected to

**Comment by pvary** [comment]
> > > If we changed 45 to ... like 450, the substring can only show zhe zookeeper connection url we input like host1:2181,host2:2181,host3:2181. We still can't get server host. For example hiveserver2host:10000
> > 
> > 
> > The question is what do we want to see here:
> > 
> > * The URI which could be used to reconnect to the cluster to rerun the queries
> > * The specific server's URI to which we are connected to
> 
> As I see, I don't think it can be used to reconnect to the cluster.
> 
> * The substring is not a complete connection URI, it only has host with port.
> * For some long URIs like zookeeper connection with many hosts, 45 char long probably can't show the whole host information.

So this is a marker only for the user to help identify the session they are using.
I think having part of the original string there is more helpful than having a "somewhat unrelated" string there, even when I see why it is so confusing in your case.

**Pull request closed without merging**
