### PR TITLE
HIVE-25727: Iceberg hive catalog should create table object with init…

### PR DESCRIPTION
**Pull request by marton-bod**

### CODE REVIEW

**Review by pvary — APPROVED** [review]

**Comment by pvary** [comment]
@marton-bod: Do we want this in the Iceberg repo as well?

**Comment by marton-bod** [comment]
@pvary  Yes I think so. 
Another question: I guess if we create the table with serdeprops initially `create table ... serdeproperties ('A'='ccc')`, this `storageDescriptor()` method actually removes the existing serdeprops by reinitialising SerdeInfo completely. I wonder if we want to keep the old values if there are any

**Comment by pvary** [comment]
Definitely not in this PR.
I do not see why would we want to put info into the serdeproperties for an Iceberg table. We should put it into the table properies instead. I was thinking about the catalog name as a good candidate, but even with that we decide to put it into the table properties instead.
Any specific usecase you have in mind?

**Comment by marton-bod** [comment]
I was asking because I know we support serdeproperties and even have a test case for that:
https://github.com/apache/hive/blob/master/iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q
But I agree that in general, we should always use table props, and not serde props.

In any case, I've merged this PR. Thanks for reviewing!

**Pull request merged**
