### PR TITLE
HIVE-23483: Remove DynamicSerDe

### PR DESCRIPTION
**Pull request by dlavati**

### CODE REVIEW

**Comment by dlavati** [comment]
Looks like my new commit messed up the labeling (fyi @kgyrtkirk)
The checkout step for http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-1207/2/tests/ shows my second commit already (0ec9e25)

**Comment by dlavati** [comment]
@ashutoshc, @pgaref could you please take a look at this? Thank you!

**Comment by dlavati** [comment]
I've seen some additional usage, however I'm not sure how these are utilized, thus I left it in so far:
```
ql/src/java/org/apache/hadoop/hive/ql/io/HiveBinaryOutputFormat.java:76:          // DynamicSerDe always writes out BytesWritable
serde/src/java/org/apache/hadoop/hive/serde2/thrift/TBinarySortableProtocol.java:150:      // If the struct is null and level > 1, DynamicSerDe will call
serde/src/java/org/apache/hadoop/hive/serde2/thrift/TBinarySortableProtocol.java:418:    // slight hack to communicate to DynamicSerDe that the field ids are not
serde/src/java/org/apache/hadoop/hive/serde2/thrift/TCTLSeparatedProtocol.java:667:    // slight hack to communicate to DynamicSerDe that the field ids are not
```

**Comment by kgyrtkirk** [comment]
> Looks like my new commit messed up the labeling (fyi @kgyrtkirk)
> The checkout step for http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-1207/2/tests/ shows my second commit already ([0ec9e25](https://github.com/apache/hive/commit/0ec9e25c7497461b9ee8e1bae89e913da60e6871))

not really; what happened was that you submitted a commit while it have started processing - so it skipped the run with the first commit

**Comment by dlavati** [comment]
> > Looks like my new commit messed up the labeling (fyi @kgyrtkirk)
> > The checkout step for http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-1207/2/tests/ shows my second commit already ([0ec9e25](https://github.com/apache/hive/commit/0ec9e25c7497461b9ee8e1bae89e913da60e6871))
> 
> not really; what happened was that you submitted a commit while it have started processing - so it skipped the run with the first commit

I see, thanks. It was just strange that the pending label is left there, even though the test actually ran and passed.

**Comment by pgaref** [comment]
> I've seen some additional usage, however I'm not sure how these are utilized, thus I left it in so far:
> 
> ```
> ql/src/java/org/apache/hadoop/hive/ql/io/HiveBinaryOutputFormat.java:76:          // DynamicSerDe always writes out BytesWritable
> serde/src/java/org/apache/hadoop/hive/serde2/thrift/TBinarySortableProtocol.java:150:      // If the struct is null and level > 1, DynamicSerDe will call
> serde/src/java/org/apache/hadoop/hive/serde2/thrift/TBinarySortableProtocol.java:418:    // slight hack to communicate to DynamicSerDe that the field ids are not
> serde/src/java/org/apache/hadoop/hive/serde2/thrift/TCTLSeparatedProtocol.java:667:    // slight hack to communicate to DynamicSerDe that the field ids are not
> ```

I am under the impression that TCTLSeparatedProtocol is also not only used by DynamicSerDe.
Regarding the DynamicSerDe comments I would either try to track why they are there (or if the functionality is needed at all) -- or completely remove them to avoid confusion. Backup option would be to note DynamicSerDe is now not supported (as you did above)

**Comment by dlavati** [comment]
The record writing I've reverted is used by a number of other SerDes and the comment in it was due to DynamicSerDe being the first which used the related classes. The failing tests passed now locally.

**Comment by dlavati** [comment]
I can't repro these failures locally. These tests look flaky:
   

-  Testing / split-19 / Archive / org.apache.hadoop.hive.ql.txn.compactor.TestMmCompactorOnMr.testMmMinorCompactionWithSchemaEvolutionAndBuckets
-     Testing / split-16 / Archive / org.apache.hadoop.hive.ql.TestWarehouseExternalDir.testExternalDefaultPaths
-     Testing / split-16 / Archive / org.apache.hadoop.hive.ql.TestWarehouseExternalDir.
-     Testing / split-14 / Archive / org.apache.hadoop.hive.cli.TestMiniDruidCliDriver.testCliDriver[druidmini_dynamic_partition]

**Comment by dlavati** [comment]
+1 flaky: `    Testing / split-14 / Archive / org.apache.hadoop.hive.cli.split20.TestMiniLlapLocalCliDriver.testCliDriver[schema_evol_text_vec_part_all_primitive]`

**Comment by dlavati** [comment]
+2 flaky / locally passing:

- `Testing / split-20 / Archive / org.apache.hadoop.hive.ql.parse.TestReplicationScenariosIncrementalLoadAcidTables.testAcidTableIncrementalReplication`
-  `Testing / split-20 / Archive / org.apache.hive.jdbc.TestJdbcWithMiniHS2.testParallelCompilation4`

**Comment by dlavati** [comment]
Thank you @pgaref, @kgyrtkirk for the reviews!

**Pull request merged**
