### PR TITLE
HIVE-24771: Fix hang of TransactionalKafkaWriterTest

### PR DESCRIPTION
**Pull request by kokila-19**
### What changes were proposed in this pull request?
Enable TransactionalKafkaWriterTest

### Why are the changes needed?
The flaky test started passing http://ci.hive.apache.org/job/hive-flaky-check/728/ , so enabling the test again.

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
Existing Unit tests and flaky check.

### CODE REVIEW

**Review by akshat0395 — APPROVED** [review]

**Comment by akshat0395** [comment]
LGTM +1

**Review by aturoczy — APPROVED** [review]
+1

**Comment by kokila-19** [comment]
TransactionalKafkaWriterTest has 3 TestCases.
http://ci.hive.apache.org/job/hive-flaky-check/727/  -> This executed all three test cases and it failed for testcase **writerFencedOut**

http://ci.hive.apache.org/job/hive-flaky-check/728/ -> writerFencedOut is not enabled, It still has ignore annotation. Class Level ignore annotation is removed so that only two testcases are enabled which are passing in flaky test.

**Comment by zabetak** [comment]
@kokila-19 Thanks for clarifying I missed the fact that the 727 and 728 runs were executed in different revisions.

**Review by zabetak — APPROVED** [review]
LGTM, will merge soon.

**Pull request closed without merging**
