### PR TITLE
[HIVE-28123] Add Generated Protobuf code for 3.24.4 Upgrade

### PR DESCRIPTION
**Pull request by Indhumathi27**
### What changes were proposed in this pull request?
Add the correct generated protobuf code with version 3.24.4

### Why are the changes needed?
Protobuf upgraded with incorrect generated protobuf code [HIVE-27845](https://issues.apache.org/jira/browse/HIVE-27845)

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
It is a by product of a dependency upgrade

### How was this patch tested?
Jenkins

### CODE REVIEW

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by tanishq-chugh** [comment]
LGTM  👍 
cc: @ayushtkn

**Comment by ayushtkn** [comment]
@Indhumathi27 The commit message template for Hive doesn't use [<jira id>], but it is like HIVE-28123: <description>, please use the same from next time.
I changed it to correct one while merging

**Comment by Indhumathi27** [comment]
> @Indhumathi27 The commit message template for Hive doesn't use [], but it is like [HIVE-28123](https://issues.apache.org/jira/browse/HIVE-28123): , please use the same from next time. I changed it to correct one while merging

sure.. will do that. Thank you @ayushtkn

**Pull request merged**
