### PR TITLE
Removed period

### PR DESCRIPTION
**Pull request by fredster33**
Other bullet points in the README don't have a period, so I removed one of them.

_Hopefully this PR doesn't require a JIRA issue, as it is a minor fix to the README._

### What changes were proposed in this pull request?
Grammar has ben fixed for the README.

### Why are the changes needed?
N/A

### Does this PR introduce _any_ user-facing change?
This changes the README.

### How was this patch tested?
No tests added, as this is just a fix for the README.

### CODE REVIEW

**Comment by fredster33** [comment]
@kgyrtkirk any updates?

**Comment by fredster33** [comment]
Bumping this.

**Comment by fredster33** [comment]
Rebumping

**Comment by fredster33** [comment]
Ugh, please no. This bot is quite possibly one of the worst things about GitHub. https://drewdevault.com/2021/10/26/stalebot.html

**Comment by kgyrtkirk** [comment]
@fredster33 you are proposing the change of a single `.` in this repository; you should file a jira ticket to make changes in this repo - and reference that in the PR. 

stale bot has its use - it will notify the author that the PR did not get any attention; what do you think - leaving an PR open for 3 years is any better? will it be merged after that amount of time - I don't think so.

to be straight with you: fixing a period in the README of this project will not change anything...you could probably fix spelling issues; see HIVE-24390 for details.

**Comment by fredster33** [comment]
.

**Pull request closed without merging**
