### PR TITLE
HIVE-27347: Addendum: count(*) should be using Iceberg stats only if there are no deletes

### PR DESCRIPTION
**Pull request by deniskuzZ**
### What changes were proposed in this pull request?
Do not rely on iceberg summary information in case of deletes

### Why are the changes needed?

Iceberg summary stats could be off in case of concurrent deletes: 
https://github.com/apache/iceberg/blob/477da36e3fd5be7f96903010557ddf5ebfad7c6d/api/src/main/java/org/apache/iceberg/RowDelta.java#L132-L133

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

iceberg_stats.q

### CODE REVIEW

**Comment by ayushtkn** [comment]
there is test failure reported, which say data size got changed for the iceberg table, how this affected the data size? or the stat got corrected or got screwed or some flakiness

**Comment by deniskuzZ** [comment]
> there is test failure reported, which say data size got changed for the iceberg table, how this affected the data size? or the stat got corrected or got screwed or some flakiness

who knows, I don't trust iceberg stats anymore

**Comment by ayushtkn** [comment]
> who knows, I don't trust iceberg stats anymore

LOL :-P I am still unable to control my laughter as I write this

**Comment by deniskuzZ** [comment]
> > who knows, I don't trust iceberg stats anymore
> 
> LOL :-P I am still unable to control my laughter as I write this

after checking looks like Iceberg stats = Hive stats, however, size on a server 

> > who knows, I don't trust iceberg stats anymore
> 
> LOL :-P I am still unable to control my laughter as I write this

after checking looks like Iceberg stats and Hive numbers are the same, however, the data size has changed.

**Comment by aturoczy** [comment]
> > there is test failure reported, which say data size got changed for the iceberg table, how this affected the data size? or the stat got corrected or got screwed or some flakiness
> 
> who knows, I don't trust iceberg stats anymore

image

**Pull request merged**
