### PR TITLE
HIVE-26617: Remove unused configurations

### PR DESCRIPTION
**Pull request by dengzhhu653**

### CODE REVIEW

**Review by ayushtkn — APPROVED** [review]
LGTM, if no test failures.

"Remove unused configurations" might be a better title

**Review by zabetak — APPROVED** [review]
LGTM. If you can also identify which commit made them noop and add the respective links in the JIRA that would be great!

**Comment by dengzhhu653** [comment]
> LGTM. If you can also identify which commit made them noop and add the respective links in the JIRA that would be great!

Done

**Comment by zabetak** [comment]
@dengzhhu653  Many thanks for adding the extra info! It is extremely useful (and saves time) when other people are trying to understand why some properties disappeared.

**Pull request merged**
