### PR TITLE
HIVE-27087: Fix TestMiniSparkOnYarnCliDriver test failures on branch-3

### PR DESCRIPTION
**Pull request by vihangk1**
### What changes were proposed in this pull request?
This PR re-enables `TestMiniSparkOnYarnCliDriver` tests on branch-3 by making the following changes:
1. Downgrade netty to 4.1.51.Final since spark tests error out with `FieldNotFound` errors at 4.1.69.Final.
2. Reverts HIVE-21044 since it introduces an unbounded list which causes OOMs for these tests. It is unclear how that logger gets configured, but a revert was preferred instead of finding why it gets configured in the HoS tests to expediate branch-3 stability. If needed, we can backport HIVE-21044 again after fixing it.
3. Removes kryo dependency from qtest-spark because it causes class loader issues which were also reported in HIVE-20747

Some tests like orc_merge*.q are still failing with a diff in q.out due to replication factor of the dfs listing in the output. It is unclear what is causing this. I confirmed that those tests also failing on the our last released version on branch-3 3.1.3 so they are probably a known old problem unrelated to recent commits post 3.1.3. FWIW, those tests work successfully on local.

### Why are the changes needed?
Fix breaking tests and stabilizing branch-3

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
CI job

### CODE REVIEW

**Comment by vihangk1** [comment]
Looking into the why the tests fail on the job. They work for me locally except (ignoring the user name) in the q.out file differences.

**Comment by vihangk1** [comment]
Retriggered the tests to rule out infra issues.

**Comment by amanraj2520** [comment]
@vihangk1 I testes in my local. The failing tests in this Jenkins builds are replicating. Any idea why is the diff ?

Mostly I can see the tests differ by a value of 3 instead of 1

**Comment by vihangk1** [comment]
> 

Yes, the q.out file differences are reproducible. I need to look into those as well. Right now I am focusing on the split4 test failures which worked for me locally but failed on jenkins job. I think they are related to https://issues.apache.org/jira/browse/HIVE-20747. I am looking into them.

**Comment by vihangk1** [comment]
Hi @amanraj2520 Can you share the command you run to reproduce the q.out diff failures. When I run them on my machine, these test fail with a diff error (username difference only).

**Comment by amanraj2520** [comment]
@vihangk1 That is the interesting thing. Same for me. Only username is different.  The value is 3 in my local.

**Comment by vihangk1** [comment]
Can you paste the diffs that you see when you run locally? Thanks!

**Comment by amanraj2520** [comment]
image

@vihangk1 FYI

**Comment by amanraj2520** [comment]
image

@vihangk1 FYI. I have attached a snippet of a failing test. Only username is different.

**Comment by amanraj2520** [comment]
Sure, let me also look into these today.

**Comment by amanraj2520** [comment]
I cannot repro in my local as well. Checking still.

**Comment by vihangk1** [comment]
@zabetak I am running out of ideas here. Any idea why the replication factor seen in the q.out is 1 instead of 3. I cannot reproduce it on my local. All the q.out file diff failures work for me on my local.

**Comment by vihangk1** [comment]
Interestingly I ran a precommit job against the released 3.1.3 code and I find the same tests with the same q.out differences. Given that we have previously released Hive in spite of those test failures and the fact that they are not locally reproducible (both running single test and running the full split) I think we can merge this PR and accept these tests are known failures. I think there is still value to keep them running in case additional diffs pop out later. Any objections to merging this PR? @amanraj2520 @zabetak ?

**Comment by amanraj2520** [comment]
@vihangk1 According to me, I think if it fails in Hive-3.1.3 as well. I think we should change to 1 instead of 3 so that the overall build looks good. And commit the changes in some other PR.

**Comment by zabetak** [comment]
> I am running out of ideas here. Any idea why the replication factor seen in the q.out is 1 instead of 3
@vihangk1 Did you debug the creation of the file locally to see which codepath sets the replication factor to 1? Maybe there is some logic to adapt the replication factor based on other things leading to the different behavior when running in CI.

**Comment by vihangk1** [comment]
> @vihangk1 Did you debug the creation of the file locally to see which codepath sets the replication factor to 1? Maybe there is some logic to adapt the replication factor based on other things leading to the different behavior when running in CI.

@zabetak I tried to look into this but there was nothing obvious that came out. I am not convinced that this is a bug yet. The replication factor is decided by the HDFS configuration `dfs.replication.factor` and I don't see any code in HoS or Hive which would affect that. Can we consider masking the replication factor for these tests for spark tests? If this was a real bug, someone would have reported it by now since it also happens on 3.1.3 so there is a high likelihood that this is related to our test environment.

**Comment by vihangk1** [comment]
I disabled the orc_merge*.q on `TestMiniSparkOnYarnCliDriver` because it is unclear why they fail on CI but not on local. We have made substantial progress in this PR by re-enabling a lot of tests on TestMiniSparkOnYarnCliDriver. I think we should merge this PR now and take up the orc_merge*.q in a separate ticket. I don't believe those are blockers for branch-3 since the same failures are also present in the released version and they are not reproducible on local.

**Comment by amanraj2520** [comment]
@vihangk1 Thanks for working on this. We have fixed 7-8 tests on branch-3 from the time this branch was cut. Just one request, can you once merge your branch with current branch-3 so that we have a combined list of remaining test failures after this fix. This would give us the concrete next action items.

**Comment by vihangk1** [comment]
> @vihangk1 Thanks for working on this. We have fixed 7-8 tests on branch-3 from the time this branch was cut. Just one request, can you once merge your branch with current branch-3 so that we have a combined list of remaining test failures after this fix. This would give us the concrete next action items.

yes, I had rebased my branch to the latest from branch-3 before pushing my last commit. The test result do not have any TestMiniSparkOnYarnCliDriver failures now. There are 2 new test failures which don't look related.

**Comment by vihangk1** [comment]
@zabetak Do you have any further comments? I created https://issues.apache.org/jira/browse/HIVE-27146 to follow up on the orc_merge*.q files on TestMiniSparkOnYarnCliDriver separately.

**Comment by amanraj2520** [comment]
TestJdbcGenericUDTFGetSplits test is flaky. I can confirm this. Seen this failing in a lot of PRs and passing in some.

**Review by sankarh — APPROVED** [review]
+1, LGTM
I agree to create follow-up ticket for the flaky tests and merge this PR.
Thanks @vihangk1 and @amanraj2520 for your efforts to fix the tests in branch-3!

When this PR gets merged, pls remove 3.2.0 from "Fix version" field in [HIVE-21044](https://issues.apache.org/jira/browse/HIVE-21044).

**Comment by vihangk1** [comment]
Thanks @sankarh, @amanraj2520 for your review and @zabetak for your help.

**Pull request merged**
