### PR TITLE
HIVE-26705. Fix Typo in hive-kudu-handler.

### PR DESCRIPTION
**Pull request by slfan1989**
JIRA: HIVE-26705. Fix Typo in hive-kudu-handler.

When reading the code, I found typo and repaired the typo of the moudle.

### CODE REVIEW

**Comment by slfan1989** [comment]
@ayushtkn Can you help review this pr? Thank you very much!

**Review by cnauroth — APPROVED** [review]
+1 (non-binding)

Thank you, @slfan1989 !

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by slfan1989** [comment]
> +1 (non-binding)
> 
> Thank you, @slfan1989 !

@cnauroth Thank you very much for your help reviewing the code!

**Comment by slfan1989** [comment]
> LGTM

@ayushtkn Thank you very much for your help reviewing the code and merging the pr!

**Pull request merged**
