### PR TITLE
HIVE-23930: Upgrade to tez 0.10.x

### PR DESCRIPTION
**Pull request by abstractdog**
initial commit, compiles successfully, good for a ptest

### CODE REVIEW

**Comment by kgyrtkirk** [comment]
@abstractdog  you could kill the prechecks in the Jenkinsfile temporarily...doesn't this needs jdk11 as well?

**Comment by abstractdog** [comment]
> @abstractdog you could kill the prechecks in the Jenkinsfile temporarily...doesn't this needs jdk11 as well?

@kgyrtkirk : JDK11 is not a must-have for newer tez versions
finally, I reproduced this issue locally, seems like the artifacts of tez 0.10.1-SNAPSHOT somehow don't contain the changes of TEZ-4145, otherwise, it should compile
https://github.com/apache/tez/commit/7dbec63e1f97eea95ab998e16ffcd592ff6be332#diff-358f7c423b64e350b9cae8462c24de20R60

**Comment by abstractdog** [comment]
@kgyrtkirk : could you please check what to do in order to start testing?
I can see: "kgyrtkirk added tests pending and removed tests failed labels 4 hours ago", and travis-ci is passed (which is compilation as far as I can see), but I cannot see a testing phase

**Comment by kgyrtkirk** [comment]
it's waiting for execution:
http://ci.hive.apache.org/job/hive-precommit/job/PR-1311/3/console

**Comment by abstractdog** [comment]
> it's waiting for execution:
> http://ci.hive.apache.org/job/hive-precommit/job/PR-1311/3/console

cool, thanks! it's just confusing that I can see "All checks have passed, 1 successful check"

**Comment by abstractdog** [comment]
@kgyrtkirk : another issue, if you have the chance to take a look...pr-merge fails with:
`[2020-07-28T16:22:54.138Z] [ERROR] Failed to execute goal on project hive-shims-0.23: Could not resolve dependencies for project org.apache.hive.shims:hive-shims-0.23:jar:4.0.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.tez:tez-api:jar:0.10.1-SNAPSHOT, org.apache.tez:tez-runtime-library:jar:0.10.1-SNAPSHOT, org.apache.tez:tez-mapreduce:jar:0.10.1-SNAPSHOT, org.apache.tez:tez-tests:jar:tests:0.10.1-SNAPSHOT: Could not find artifact org.apache.tez:tez-api:jar:0.10.1-SNAPSHOT in wonder (http://artifactory/artifactory/wonder) -> [Help 1]`

is it possible to enable SNAPSHOTS for "wonder"? tez 0.10.1-SNAPSHOT artifacts are present in:
https://repository.apache.org/snapshots/org/apache/tez/tez-runtime-library/0.10.1-SNAPSHOT/
and works for me locally without using a settings.xml

**Comment by belugabehr** [comment]
FYI, I just figured out that this is blocking Hive adoption of JDK 11 (see HIVE-22415)

**Comment by abstractdog** [comment]
green run with released tez 0.10.0 artifacts + the contents of HIVE-23190, HIVE-24108
cc: @ashutoshc

**Comment by abstractdog** [comment]
this is pushed to master directly with HIVE-24108, HIVE-23190

**Pull request closed without merging**
