### PR TITLE
HIVE-26668: Upgrade ORC version to 1.6.11

### PR DESCRIPTION
**Pull request by glapark**
With ORC 1.6.9, setting hive.exec.orc.default.compress to ZSTD can generate IllegalStateException. This is fixed in ORC-965.

### CODE REVIEW

**Review by cnauroth — COMMENTED** [review]
This looks good to me. I applied the patch locally and ran all of the ORC tests.

Jenkins reported a failure in `TestMiniLlapLocalCliDriver`. I'm going to try running that one locally too to see if reproduces, but it will take a while. I'll report back here with the results.

**Review by cnauroth — COMMENTED** [review]
I'm getting a few failures in `TestMiniLlapLocalCliDriver` without the patch, so it's unclear to me if the failure on Jenkins indicates a real problem.

I also reviewed ORC's changelog between 1.6.9 and 1.6.11. I didn't note anything concerning from an upgrade or compatibility perspective.

I also noticed that the latest available release in the 1.6 line is actually 1.6.14. Maybe we should consider upgrading to that one. @glapark , what do you think?

**Comment by mr3project** [comment]
> 

I think upgrading to 1.6.14 is fine. I tested 1.6.11 because this is the version that fixes the Zstd problem.

**Comment by glapark** [comment]
> I'm getting a few failures in `TestMiniLlapLocalCliDriver` without the patch, so it's unclear to me if the failure on Jenkins indicates a real problem.
> 
> I also reviewed ORC's changelog between 1.6.9 and 1.6.11. I didn't note anything concerning from an upgrade or compatibility perspective.
> 
> I also noticed that the latest available release in the 1.6 line is actually 1.6.14. Maybe we should consider upgrading to that one. @glapark , what do you think?

I think upgrading to 1.6.14 is fine. I tested 1.6.11 because this is the version that fixes the Zstd problem.

**Pull request closed without merging**
