### PR TITLE
HIVE-27688 hive MoveTask cannot show the correct exception message

### PR DESCRIPTION
**Pull request by liangyu-1**
### What changes were proposed in this pull request?

I modified how the Exception was thrown in org/apache/hadoop/hive/ql/metadata/Hive.java.

### Why are the changes needed?

As I have described in [HIVE-27688](https://issues.apache.org/jira/browse/HIVE-27688?jql=project%20%3D%20HIVE%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(ylllllllll)%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)
when you insert into hive table's partition, you will get the correct exception message when you insert **into** table, but You will get useless message when you insert **overwrite** table. This will make a confusion when tracing the problem.

### Does this PR introduce _any_ user-facing change?

No

### Is the change a dependency upgrade?

no

### How was this patch tested?

I rebuild the package and test it, it gives me correct exception message.

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
There is a logic insider getHiveException()
```
    if (e.getMessage() != null) {
      hiveErrMsg = String.format("%s%s%s", msg, ": ",
          Splitter.on(System.getProperty("line.separator")).split(e.getMessage()).iterator()
              .next());
    } else {
      hiveErrMsg = msg;
    }
```

Why this doesn't kick in? Can you extend a test case as well. I guess this case is handled via [HIVE-16960](https://issues.apache.org/jira/browse/HIVE-16960)

**Comment by liangyu-1** [comment]
> There is a logic insider getHiveException()
> 
> ```
>     if (e.getMessage() != null) {
>       hiveErrMsg = String.format("%s%s%s", msg, ": ",
>           Splitter.on(System.getProperty("line.separator")).split(e.getMessage()).iterator()
>               .next());
>     } else {
>       hiveErrMsg = msg;
>     }
> ```
> 
> Why this doesn't kick in? Can you extend a test case as well. I guess this case is handled via [HIVE-16960](https://issues.apache.org/jira/browse/HIVE-16960)

@ayushtkn 
These two cases might be a little different, because the ErrorMsg returned from these cases are different.

```  
public static ErrorMsg getErrorMsg(Exception e) {
    if (e instanceof AccessControlException) {
      return ACCESS_DENIED;
    }
    if (e instanceof NSQuotaExceededException) {
      return QUOTA_EXCEEDED;
    }
    if (e instanceof DSQuotaExceededException) {
      return QUOTA_EXCEEDED;
    }
    if (e instanceof UnresolvedPathException) {
      return UNRESOLVED_PATH;
    }
    if (e instanceof FileNotFoundException) {
      return FILE_NOT_FOUND;
    }
    return UNRESOLVED_RT_EXCEPTION;
  }
```
In case [HIVE-16960](https://issues.apache.org/jira/browse/HIVE-16960), the Exception is the instance of AccessControlException so the ErrorMsg returned is `ACCESS_DENIED`, then hiveErrMsg will be showed to users.

 But in my case the Exception is HiveException, which cannot be found in the exception list, and ErrorMsg returned will be `UNRESOLVED_RT_EXCEPTION`. Then the hiveErrMsg will not be showed. 

I will try to reproduce this issue in test cases.

**Comment by liangyu-1** [comment]
@ayushtkn 
Hi, I have added a new unit test on how the dirty message was shown, and how to prevent this.
Please help me check this.

**Comment by liangyu-1** [comment]
I found another case that cannot give me the correct exception message:
when I use pyhive to load data, I accidentally set a wrong config `hive.exec.copyfile.maxnumfiles` to string "100L". when I try to load data, it returns that `(statusCode=3, infoMessages=[ *org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.MoveTask. org.apache. hadoop.hive.ql.metadata.HiveException: Unable to move source hdfs://dmp/xxx to destination hdfs://dmp/xxx`

this dirty message really confused me, and I checked deeply into the log in hiveserver2, and find the stacktrace of this exception.

It's the same reason with the issue I explained before, the error message was erased in method `getHiveException(e, msg)`.

**Comment by liangyu-1** [comment]
Why I cannot trigger Jenkins when I made new commit?

**Pull request closed without merging**
