### PR TITLE
HIVE-26906 : Backport of HIVE-19313 : TestJdbcWithDBTokenStoreNoDoAs tests are failing (Peter …

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-26906

### CODE REVIEW

**Comment by amanraj2520** [comment]
@cnauroth FYI raised this a separate PR.

**Comment by amanraj2520** [comment]
@zabetak @abstractdog Can you please review and approve this. A simple backport.

**Review by cnauroth — APPROVED** [review]
+1 (non-binding)

It looks like a clean backport. I applied locally and ran the tests successfully.

Thank you, @amanraj2520 !

**Review by abstractdog — APPROVED** [review]
+1

**Pull request merged**
