### PR TITLE
HIVE-26879: Backport of HIVE-23323: Add qsplits profile

### PR DESCRIPTION
**Pull request by amanraj2520**
Backport of HIVE-23323: Add qsplits profile to branch-3

### CODE REVIEW

**Comment by amanraj2520** [comment]
@abstractdog @zabetak Can you please merge this PR. Just a backport. It was also merged in branch-3.1.

**Comment by abstractdog** [comment]
sorry, I'm a bit confused now, maybe it's not the proper location, but please let me know:
1. what was branch-3.1?
2. what's the current release we're targeting?

**Comment by amanraj2520** [comment]
@abstractdog 
1. Branch-3.1 was the branch from where Hive 3.1.3 release was taken
2. The current release that we are targeting is 3.2.0. But the current release will be taken from branch-3 instead of branch-3.1. That's why we need to cherry pick this change in branch-3 so that we make sure that we are not missing any commits that went into hive-3.1.3 release.

I was just saying that since this commit resolves a lot of test cases and also it was present in branch-3.1(or hive-3.1.3 release) therefore we can merge it to branch-3 since it is not present there currently.

**Comment by amanraj2520** [comment]
@abstractdog Just for your information. These were the steps that I was targetting for 3.2.0 release :
1. Ensure Green build for branch-3. JIRA : https://issues.apache.org/jira/browse/HIVE-26836
2. Cherry pick the diff between branch-3.1 and branch-3 to branch-3. This will make sure that release 3.2.0 is not missing any commit from release 3.1.3. I have also done that comparison in this JIRA. JIRA : https://issues.apache.org/jira/browse/HIVE-26752
3. Then only after 1 and 2 are successfully done we will integrate new features on branch-3 as I had mailed the OSS community.

**Comment by amanraj2520** [comment]
Let me know if you have any questions

**Comment by abstractdog** [comment]
thanks @amanraj2520 , maybe I missed the email thread about this, makes sense
also, thanks for making sure to include all patches to branch-3 that are already present in branch-3.1!
let me find some time to review

**Comment by amanraj2520** [comment]
No worries @abstractdog. Thanks a lot for your efforts in reviewing this and making my progress faster. Let me know if you have any concerns. I will try to reply asap.

**Review by cnauroth — APPROVED** [review]
Thank you, @amanraj2520 . This looks like a good clean backport.

Several of the new files are missing ASF license headers. I see they were added later in [HIVE-23621](https://issues.apache.org/jira/browse/HIVE-23621): Enforce ASF headers on source files (https://github.com/apache/hive/pull/1062)

+1 (non-binding), assuming either your or I can queue up a backport of HIVE-23621 after this goes in.

**Comment by amanraj2520** [comment]
@cnauroth Will make note of this. Fyi created a Backport task https://issues.apache.org/jira/browse/HIVE-26886

Will work on it once this goes in. Thanks for the suggestion.

**Review by abstractdog — APPROVED** [review]
+1

**Pull request merged**
