### PR TITLE
HIVE-13877 Fixed the problem with Hplsql UDF doesn't work in Hive Cli

### PR DESCRIPTION
**Pull request by jiangxt2**
Hive cli will throw "Error evaluating hplsql" exception when i use the hplsql udf like "SELECT hplsql('hello[:1]', columnName) FROM tableName". So, this request exists to fix that problem.

### CODE REVIEW

**Comment by jiangxt2** [comment]
Is it my fault? How can i fix it? thx my bro. :)

**Comment by dmtolpeko** [comment]
Can you create a Hive JIRA for this problem? Github is just a mirror

**Comment by jiangxt2** [comment]
@dmtolpeko Hi, I created a JIRA for this problem.
The url is https://issues.apache.org/jira/browse/HIVE-13877
What should I do next?

**Comment by dmtolpeko** [comment]
I will review your changes and create a patch.

**Comment by jiangxt2** [comment]
@dmtolpeko OK, I GOT IT. Thanks veri much. I'll wait for your response.

**Comment by vishurkamble** [comment]
Can somebody tell me, is UDF running in hive or not?  I tried some code fix but no luck. Still getting same error: PFB
2016-10-22 09:49:54,311 WARN  [main] mapreduce.TableMapReduceUtil: The hbase-prefix-tree module jar containing PrefixTreeCodec is not present.  Continuing without it.

Logging initialized using configuration in file:/etc/hive/conf.dist/hive-log4j.properties
Added [/home/cloudera/hplsql-0.3.17/hplsql.jar] to class path
Added resources: [/home/cloudera/hplsql-0.3.17/hplsql.jar]
Added [/home/cloudera/hplsql-0.3.17/antlr-runtime-4.5.jar] to class path
Added resources: [/home/cloudera/hplsql-0.3.17/antlr-runtime-4.5.jar]
Added resources: [/home/cloudera/hplsql-0.3.17/hplsql-site.xml]
Added resources: [/home/cloudera/hplsql-0.3.17/.hplsqlrc]
OK
Time taken: 1.294 seconds
OK
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/parquet/lib/parquet-hadoop-bundle-1.5.0-cdh5.8.0.jar!/shaded/parquet/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/parquet/lib/parquet-format-2.1.0-cdh5.8.0.jar!/shaded/parquet/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/parquet/lib/parquet-pig-bundle-1.5.0-cdh5.8.0.jar!/shaded/parquet/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/hive/lib/hive-exec-1.1.0-cdh5.8.0.jar!/shaded/parquet/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/hive/lib/hive-jdbc-1.1.0-cdh5.8.0-standalone.jar!/shaded/parquet/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [shaded.parquet.org.slf4j.helpers.NOPLoggerFactory]
Configuration file: file:/home/cloudera/hplsql-0.3.17/hplsql-site.xml
Parser tree: (program (block (stmt (expr_stmt (expr (expr_atom (ident hello))))) (stmt (expr_stmt (expr (expr_atom (ident [:1])))))))
INLCUDE CONTENT .hplsqlrc (non-empty)
Ln:1 CREATE FUNCTION hello
Failed with exception java.io.IOException:org.apache.hadoop.hive.ql.metadata.HiveException: Error evaluating hplsql
Time taken: 1.129 seconds
WARN: The method class org.apache.commons.logging.impl.SLF4JLogFactory#release() was invoked.
WARN: Please see http://www.slf4j.org/codes.html#release for an explanation.
Oct 22, 2016 9:50:12 AM WARNING: parquet.hadoop.ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
Oct 22, 2016 9:50:12 AM INFO: parquet.hadoop.InternalParquetRecordReader: RecordReader initialized will read a total of 53 records.
Oct 22, 2016 9:50:12 AM INFO: parquet.hadoop.InternalParquetRecordReader: at row 0. reading next block
Oct 22, 2016 9:50:12 AM INFO: parquet.hadoop.InternalParquetRecordReader: block read in memory in 33 ms. row count = 53

**Pull request closed without merging**
