### PR TITLE
HIVE-25616: [FOLLOWUP] Set auth privileges should respect getauth

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Set auth privileges should respect getauth.

### Why are the changes needed?

Recover tests `org.apache.hadoop.hive.metastore.TestHiveMetaStore.testPartition`

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass `org.apache.hadoop.hive.metastore.TestHiveMetaStore.testPartition`

### CODE REVIEW

**Comment by pan3793** [comment]
ping @nssalian @vihangk1

**Comment by pan3793** [comment]
This recovers all `testPartitions` UTs.
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3602/7/tests

**Comment by pan3793** [comment]
would you like to take a look? @vihangk1

**Comment by pan3793** [comment]
ping @nssalian @vihangk1, it's a backport issue

**Comment by pan3793** [comment]
ping @sunchao, this is backport issue, and is necessary for 2.3.10

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by sunchao** [comment]
Merged, thanks!

**Pull request merged**
