### PR TITLE
HIVE-26339: HIVE-26047 Related LIKE pattern issues

### PR DESCRIPTION
**Pull request by ryukobayashi**
### What changes were proposed in this pull request?

Vectorized LIKE udf is taking proportionately higher time depending on the size of input string in UDF. And, I found a problem with some regular expressions.

### Why are the changes needed?

To support filter condition based on input data.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added testcase as part of PR.

### CODE REVIEW

**Comment by ryukobayashi** [comment]
@zabetak I have fixed the following PR, Could you take a look this? https://github.com/apache/hive/pull/3117

**Comment by zabetak** [comment]
Hey @ryukobayashi thanks for the PR. I am quite busy for the next 8-10 days so not sure if I will find time to review.

**Comment by ryukobayashi** [comment]
Thanks! @zabetak Got it, I will wait till then.

**Comment by ryukobayashi** [comment]
@zabetak Is it still going to take time?

**Pull request closed without merging**
