### PR TITLE
HIVE-25320: Purge hive.optimize.sort.dynamic.partition

### PR DESCRIPTION
**Pull request by sneakyburro**
### What changes were proposed in this pull request?

Remove all usages of `hive.optimize.sort.dynamic.partition` in query tests

### Why are the changes needed?
`hive.optimize.sort.dynamic.partition` was deprecated and defuncted in source code base. The usages in query tests should be cleaned up.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
rerun unit test and query tests

### CODE REVIEW

**Comment by miklosgergely** [comment]
HiveConf.ConfVars.HIVEOPTSORTDYNAMICPARTITION was not removed, though the jira says that it should be removed too. Is there a reason not to do so?

**Comment by sneakyburro** [comment]
> HiveConf.ConfVars.HIVEOPTSORTDYNAMICPARTITION was not removed, though the jira says that it should be removed too. Is there a reason not to do so?

I thought it refers to remove references of HIVEOPTSORTDYNAMICPARTITION in tests as well. I'm cleaning it up now!

**Comment by belugabehr** [comment]
+1 pending tests

**Review by miklosgergely — APPROVED** [review]

**Comment by belugabehr** [comment]
Can you please change PR (and JIRA) title to:

bq. HIVE-25320: Purge hive.optimize.sort.dynamic.partition

Please?

**Comment by sneakyburro** [comment]
> Can you please change PR (and JIRA) title to:
> 
> > HIVE-25320: Purge hive.optimize.sort.dynamic.partition
> 
> Please?

done

**Pull request merged**
