### PR TITLE
HIVE-27623: Backport of HIVE-26081: Upgrade ant to 1.10.9 (Ashish Sharma, reviewed by Adesh Rao)

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link - https://issues.apache.org/jira/browse/HIVE-27623

### CODE REVIEW

**Comment by deniskuzZ** [comment]
@amanraj2520, could you please raise a single backport request instead of 20+. it blocks the master branch development

**Comment by amanraj2520** [comment]
@deniskuzZ I understand that. Individual tickets are necessary to keep proper track of the tickets that went into the 3.2.0 release. Apologises if your development got delayed. Will trigger one or two PRs from now on at a time.

**Comment by amanraj2520** [comment]
@deniskuzZ I understand that. Individual tickets are necessary to keep proper track of the tickets that went into the 3.2.0 release. Apologises if your development got delayed. Will trigger one or two PRs from now on at a time.

**Comment by amanraj2520** [comment]
@deniskuzZ @vihangk1 @sankarh Can you please review and merge this

**Review by sankarh — APPROVED** [review]

**Pull request merged**
