### PR TITLE
HIVE-26675: Update Iceberg from 0.14.1 to 1.0.0

### PR DESCRIPTION
**Pull request by zhangbutao**
### Why are the changes needed?

https://iceberg.apache.org/releases/#100-release

The 1.0.0 release officially guarantees the stability of the Iceberg API.

### CODE REVIEW

**Comment by zhangbutao** [comment]
Strangely, I can't trigger the continuous-integration.

**Comment by zhangbutao** [comment]
Strangely, i can not trigger the continuous-integration to run qtest.

**Review by cnauroth — APPROVED** [review]
+1 (non-binding)

I applied the patch locally and verified that all Iceberg tests pass. @zhangbutao , thank you!

**Comment by rbalamohan** [comment]
LGTM. +1

**Pull request merged**
