### PR TITLE
Hive 21221

### PR DESCRIPTION
**Pull request by odraese**
From https://issues.apache.org/jira/browse/HIVE-21221

When HiveServer2 comes up, it skips the start of the WebUI if
1) hive.in.test is set to true
AND
2) the WebUI port is not specified or default (hive.server2.webui.port)
 
Right now, on LLAP daemon start, it is only checked if hive is in test (condition 1) above.
 
The LLAP Daemon start up code (to skip WebUI creation) should be consistent with HS2, therefore if a port is specified (other than the default), the WebUI should also be started in test mode.

### CODE REVIEW

**Comment by odraese** [comment]
@beltran Can you please review/pull? Thx.

**Comment by djhwx** [comment]
I looked at the code. Its pretty straight forward. I can push it if the test run completes soon.

**Comment by beltran** [comment]
LGTM

**Comment by belugabehr** [comment]
Issue resolved in JIRA:

https://issues.apache.org/jira/browse/HIVE-21221

**Pull request closed without merging**
