### PR TITLE
HIVE-26079: Upgrade Protobuf to 3.21.1

### PR DESCRIPTION
**Pull request by slachiewicz**
Tags for the Reproducible builds

### CODE REVIEW

**Comment by ayushtkn** [comment]
Got it sorted here: 3498
Not moving above 3.7.1 to keep it sync with Hadoop

**Comment by slachiewicz** [comment]
ok - that was previously my work here #3309

**Comment by slachiewicz** [comment]
reason to use [3.21.1 and not previous is only becouse previous version dont have feature to use protoc on macos m1.

**Comment by ayushtkn** [comment]
3.19.2 should also allow I feel:
https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.19.2/

I wanted to stay with Hadoop for now. OSX won't be used for actual deployments though, but yes for dev env for sure.(I am myself on OSX)

These google dependencies are very good with breaking backward compat, As of now I think I just had 2 HBase failures, which I got fixed, Hopefully won't have any other. But I can check with folks like what issues can it have if we move above hadoop, earlier both hadoop & hive were on 2.5.0

**Comment by slachiewicz** [comment]
no, anything bellow 3.21.0-rc-2  was wrong.. I've been testing builds on Hive ;-)

https://github.com/protocolbuffers/protobuf/issues/9973

**Pull request closed without merging**
