### PR TITLE
HIVE-23901: Overhead of Logger in ColumnStatsMerger damage the perfor…

### PR DESCRIPTION
**Pull request by hsnusonic**
…mance

### CODE REVIEW

**Comment by belugabehr** [comment]
The current implementation is purposeful.  This is an abstract class.  The idea is that every subclass gets it's own logger.  With the implementation proposed in this PR, every subclass will have the same logger.  This makes logging very difficult to tease out.

Can you please elaborate on the performance implications here?  If it's absolutely required, it is better that each subclass have their own Logger than to inherit a logger in this fashion.

**Comment by belugabehr** [comment]
This only happens if these objects are being instantiated repeatedly. May need to look at that.

**Comment by hsnusonic** [comment]
@belugabehr Thank you for pointing out that.

The problem happens in [here](https://github.com/apache/hive/blob/master/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/aggr/LongColumnStatsAggregator.java#L110) and other aggregators. When a table has many partitions, the merger is being instantiated repeatedly.

Yeah, I think each subclass has its own Logger is a good idea.

**Comment by nrg4878** [comment]
IsColumnStatsMerger a class internal to hive? I think it is but I am not certain. Otherwise changing the method name might be an issue.

**Comment by hsnusonic** [comment]
@nrg4878 the method doMerge is declared as protected originally and is used only in class *ColumnStatsMerger, so it seems fine to be reduced to only one method merge.

**Comment by nrg4878** [comment]
fix has been committed to master. Please close out this PR.

**Pull request closed without merging**
