### PR TITLE
HIVE-27434: Preparing for 4.0.0-beta-1 development

### PR DESCRIPTION
**Pull request by zabetak**
### What changes were proposed in this pull request?
1. Extend Copyright to 2023 in NOTICE files
2. Set version to 4.0.0-beta-1-SNAPSHOT in pom files
3. Prepare metastore install/upgrade scripts for 4.0.0-beta-1 release

### Why are the changes needed?
The changes are needed in order to do the release of 4.0.0-beta-1

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests should suffice

### CODE REVIEW

**Review by aturoczy — APPROVED** [review]
+2 :) 

image

**Comment by zabetak** [comment]
There is one test failure but it corresponds to a known flaky test that is actively worked on (https://issues.apache.org/jira/browse/HIVE-27429). Re-launching the tests is not necessary.

**Review by deniskuzZ — APPROVED** [review]
LGTM +1, pending tests

**Review by ayushtkn — APPROVED** [review]
Changes LGTM
Maybe we have to check the https://github.com/apache/hive/tree/master/binary-package-licenses
some might be outdated and some may be missing, that dir was done some 7 years ago

**Pull request closed without merging**
