### PR TITLE
HIVE-26259: Alter Function should also update resource uris

### PR DESCRIPTION
**Pull request by wecharyu**
### What changes were proposed in this pull request?
Add the alteration of resource uris for Function while calling `alter_function` api.

### Why are the changes needed?
Computing engines will load the jar of permanent UDF based on the resource uris, if we changed the resource uris through `alter_function` api, which apparently won't work, we will not able to use this UDF because of the lack of jars.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Add an unit test:
```bash
mvn test -Dtest=org.apache.hadoop.hive.metastore.TestObjectStore#testFunctionOps -pl :hive-standalone-metastore-server
```

### CODE REVIEW

**Comment by wecharyu** [comment]
@pvary @ayushtkn Could you review this PR?

**Comment by pvary** [comment]
Do we have SQL support for this? If yes, then we might want to write a query test for it.

Also, please rebase, to fix the failing test.

Thanks, Peter

**Review by pvary — APPROVED** [review]

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by wecharyu** [comment]
Hi @pvary thanks for your concern. It is indeed important to do authorization for operating UDF. 
But I do not think it should be an admin privilege for the user level function, user should be able to create or alter their UDF, so an `OWNER_PRIV` is enough just like #3360.
Also, we can achieve the authorization in Hive MetaStore by `MetaStorePreEventListener`, I think it can be done after #3360 because there will be some similar code.

**Comment by pvary** [comment]
> Hi @pvary thanks for your concern. It is indeed important to do authorization for operating UDF. But I do not think it should be an admin privilege for the user level function, user should be able to create or alter their UDF, so an `OWNER_PRIV` is enough just like #3360.

Makes sense

> Also, we can achieve the authorization in Hive MetaStore by `MetaStorePreEventListener`, I think it can be done after #3360 because there will be some similar code.

I would prefer to have a security check already at hand when we enable the alter function.

**Comment by wecharyu** [comment]
> I would prefer to have a security check already at hand when we enable the alter function.

OK, I will also add the security check here.

**Comment by wecharyu** [comment]
@ayushtkn could you take a look again and check if there is any change required?

**Pull request closed without merging**
