### PR TITLE
HIVE-24860: Shut down DbTxnManager heartbeatExecutorService at session close

### PR DESCRIPTION
**Pull request by klcopp**
### What changes were proposed in this pull request?
Shut down thread pool HeartbeatExecutorService upon session close.

### Why are the changes needed?
If the HeartBeaterExecutorService isn't shut down, UDF classes belonging to the session's UDFClassLoader (which was the session thread's context classloader at HeartBeaterExecutorService creation) could pile up and cause Metaspace OOM.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manually

### CODE REVIEW

**Review by pvary — APPROVED** [review]

**Comment by deniskuzZ** [comment]
@klcopp, with HIVE-24179 heartbeatExecutorService was made to be a global to avoid multiple shutdown hooks for the same threadpool.

**Comment by pvary** [comment]
> @klcopp, with [HIVE-24179](https://issues.apache.org/jira/browse/HIVE-24179) heartbeatExecutorService was made to be a global to avoid multiple shutdown hooks for the same threadpool. cc @zabetak

Thanks for catching this @deniskuzZ!

Strange thing that the service is static, but not initialized in a static way.
The first user might set the pool size to a small one, and then later ones can not change it... Is there any particular reason behind this?

**Comment by deniskuzZ** [comment]
> > @klcopp, with [HIVE-24179](https://issues.apache.org/jira/browse/HIVE-24179) heartbeatExecutorService was made to be a global to avoid multiple shutdown hooks for the same threadpool. cc @zabetak
> 
> Thanks for catching this @deniskuzZ!
> 
> Strange thing that the service is static, but not initialized in a static way.
> The first user might set the pool size to a small one, and then later ones can not change it... Is there any particular reason behind this?

I don't think we should allow to change this config at session level. Idea was to have a single threadpool for txn heartbeating job. Btw initialization is also under the static method.

**Comment by pvary** [comment]
> I don't think we should allow to change this config at session level. Idea was to have a single threadpool for txn heartbeating job. Btw initialization is also under the static method.

Yeah, `DbTxnManager.initHeartbeatExecutorService()` is static-like - would it hurt to create the ExecutorService in a static block - using the global config, and use this service everywhere?

**Review by zabetak — APPROVED** [review]
LGTM

**Pull request closed without merging**
