### PR TITLE
HIVE-23998: Upgrade guava to 27 for Hive 2.3 branch

### PR DESCRIPTION
**Pull request by viirya**
### What changes were proposed in this pull request?

This PR proposes to upgrade Guava to 27 in Hive 2.3 branch.

### Why are the changes needed?

When trying to upgrade Guava in Spark, found the following error. A Guava method became package-private since Guava version 20. So there is incompatibility with Guava versions > 19.0.

```
sbt.ForkMain$ForkError: sbt.ForkMain$ForkError: java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.hadoop.hive.ql.exec.FetchOperator
	at org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:108)
	at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:87)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:541)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1317)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1457)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1237)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1227)
```

### Does this PR introduce _any_ user-facing change?

Yes. This upgrades Guava to 27.

### How was this patch tested?

Built Hive locally.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao I saw the test was timeout, can we re-trigger the test?

**Comment by sunchao** [comment]
Sure @viirya - restarted

**Comment by viirya** [comment]
Thanks, is it only re-triggerable by Hive committers?

**Comment by sunchao** [comment]
I think so. You can sign-in with your github account and see if the option is there.

**Comment by viirya** [comment]
This was successfully built. How do I trigger the test?

**Comment by viirya** [comment]
Seems a label "tests pending" is needed for triggering testing?

**Comment by sunchao** [comment]
@viirya added test pending - let's see

**Comment by viirya** [comment]
@sunchao looks like it doesn't trigger testing. 

@kgyrtkirk Hi, do you know how to trigger the tests? thanks.

**Comment by sunchao** [comment]
@viirya It may be because the PR action only support master and branch-2 right now, not branch-2.3. I suggest you submit a patch to the JIRA ticket similar to https://issues.apache.org/jira/browse/HIVE-22249.

**Comment by viirya** [comment]
@sunchao Ok, I see. I will do. Thanks.

**Comment by sunchao** [comment]
It seems the patch approach also doesn't work. ping @pvary @kgyrtkirk : do you know a way to trigger tests? thanks.

**Comment by sunchao** [comment]
Oops. Sorry I merged this by mistake. Will create a PR to revert it.

**Comment by viirya** [comment]
Oh ok. I need to create a new PR for this?

**Comment by sunchao** [comment]
No there is already a PR to revert it (see above message). I'll get it merged soon.

**Comment by viirya** [comment]
Oh, I mean a new PR for this change.

**Comment by sunchao** [comment]
@viirya Yes please do. Sorry about that :(

**Comment by viirya** [comment]
No problem at all. @sunchao

**Comment by sunchao** [comment]
@viirya reverted - please ping me on the new PR and let's see if we can figure this testing thing out.

**Pull request merged**
