### PR TITLE
HIVE-25357: Fix the checkstyle issue in HiveIcebergMetaHook and the iceberg test issues to unblock the pre-commit tests

### PR DESCRIPTION
**Pull request by kuczoram**
…aks the build

### CODE REVIEW

**Review by marton-bod — APPROVED** [review]

**Review by szlta — APPROVED** [review]

**Comment by pvary** [comment]
Do we know what caused the issue? Can we just revert the change?

**Comment by kuczoram** [comment]
> Do we know what caused the issue? Can we just revert the change?

Most probably this one: https://issues.apache.org/jira/browse/HIVE-25276
The build failure is definitely because of this patch, as the build failed on that commit. The tests are also very probably.
Are you ok to revert it?

**Comment by pvary** [comment]
> Are you ok to revert it?

Sure. Revert it, and later we will try to find out what caused the conflict. The change had a green run before the merge, so there should be some other conflicting change, and the 2 of them are causing the issues together. 

But if we know the last one we definitely want to revert it

**Comment by kuczoram** [comment]
> > Are you ok to revert it?
> 
> Sure. Revert it, and later we will try to find out what caused the conflict. The change had a green run before the merge, so there should be some other conflicting change, and the 2 of them are causing the issues together.
> 
> But if we know the last one we definitely want to revert it

Ok, created a PR for the revert:
https://github.com/apache/hive/pull/2505

Yes, most probably there is some interference with a previous PR. We can find out which one and can fix it later then.

**Comment by kuczoram** [comment]
Close this PR, as the problematic commit got reverted, so we will have time to fix the tests properly.

**Comment by marton-bod** [comment]
Looking at the history of HiveIcebergMetaHook changes: https://github.com/apache/hive/commits/master/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
It's almost certainly a conflict with this: https://issues.apache.org/jira/browse/HIVE-25256
My patch got merged yesterday (changing the metahook), the stats generation changed the metahook too but its green run was 5 days old, then it was merged too -> BOOM!

**Pull request closed without merging**
