### PR TITLE
HIVE-24468: Use Event Time instead of Current Time in Notification Lo…

### PR DESCRIPTION
**Pull request by belugabehr**
…g DB Entry

### CODE REVIEW

**Comment by pvary** [comment]
Could this cause out of order notification timestamps? If we are sure that nobody relies on timestamps to check notification order (bad practice) then we can change, but I would be cautious about changing this, as notifications are widely used API.

**Comment by belugabehr** [comment]
@pvary Thanks for the review.

So, the answer is yes.  The timestamps could be out of order.

If two instances of HMS are running at the same time, and let's say they both create events at times T and T+1.

The HMS which generates the event at time T could experience a long GC and then try to submit it to the DB.  At that point, the event at T+1 is going to be submitted first to the table, and receive a lower ID.

However, there does not seem to be any documentation around this constraint.

1. Is there docs somewhere that state that the event times will always be increasing from one record to the next?
2. Isn't it a bit confusing that they are assigned an arbitrary time that masks that true event time (debugging, audit issues)?
3. The time stamps are generated using each HMS's "now" time, which could possibly not be adequately synced across HMS instances and this issue of in-order timestamps is in jeopardy.  If in-order timestamps are a requirement, they should be generated using the `now()` of the SQL server itself as a single source of "now" truth.

Thanks!

**Comment by pvary** [comment]
> So, the answer is yes. The timestamps could be out of order.

Before this patch the timestamps were in order as we locked the NEXT_EVENT_ID table with SELECT FOR UPDATE, so the timestamp was aligned with the EVENT_ID. (There might be some exceptions if some backend RDBMS reuses the value returned by the function now() in a single transaction, but I think we should overlook this for now 😄)

After this PR the timestamps could become out of order. Which is IMHO an API change even if the order requirement is not documented. So the users should be aware of this change and we should seriously consider this before proceeding.

Good to have you back and starting to cleaning up these stuff!
Thanks,
Peter

**Comment by belugabehr** [comment]
@pvary 

I agree with your understanding that the SELECT FOR UPDATE is a lock, and therefore the time is the same, but imagine if the HMS clock on two instances were off by 5s (or more).  The HMS with the slower clock would generate events that were earlier in time, but with a higher ID.  So there is not strong enforcement of the time being sequential.  It's all based on the HMS clocks being in sync and trusting those clocks.

**Comment by belugabehr** [comment]
@pvary Just so we are clear "now()" is not an SQL function.  It's implemented on this DBListener class:

```
  private int now() {
    long millis = System.currentTimeMillis();
    millis /= 1000;
    if (millis > Integer.MAX_VALUE) {
      LOG.warn("We've passed max int value in seconds since the epoch, " +
          "all notification times will be the same!");
      return Integer.MAX_VALUE;
    }
    return (int)millis;
  }
```

https://github.com/apache/hive/blob/master/hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java#L941-L950

**Comment by aasha** [comment]
+1

**Review by nrg4878 — APPROVED** [review]
Looks good to me.

**Pull request merged**
