### PR TITLE
HIVE-28373: Iceberg: Refactor the code of HadoopTableOptions

### PR DESCRIPTION
**Pull request by BsoBird**
PR: core:Refactor the code of HadoopTableOptions
https://github.com/apache/iceberg/pull/10623 
All test cases can be found in this PR
HIVE-ISSUE: https://issues.apache.org/jira/browse/HIVE-28373

### CODE REVIEW

**Comment by BsoBird** [comment]
@deniskuzZ 
Hello. I'm submitting the fix I originally submitted to iceberg here.

**Comment by deniskuzZ** [comment]
@BsoBird, add new class to the excludes list
````
                  <excludes>
                      **/HadoopInputFile.class
                      **/SerializableTable.class
                  </excludes>
````

**Comment by BsoBird** [comment]
> @BsoBird, add original iceberg class to the excludes list
> 
> ```
> <excludes>
>     **/HadoopInputFile.class
> +   **/HadoopTableOperations.class
>     **/SerializableTable.class
> </excludes>
> ```

done

**Comment by ayushtkn** [comment]
can you explain the changes & the issues being solved here? Is there a possibility to extend some tests, if it is fixing any bug or so?

**Comment by BsoBird** [comment]
> can you explain the changes & the issues being solved here? Is there a possibility to extend some tests, if it is fixing any bug or so?

This PR solves the reliability problem of hadoopcatalog.With this PR. hadoopcatalog commits are atomic operations.

I submitted this PR to the iceberg community, but the iceberg community did not accept this PR, they don't want to support FileSystemCatalog further.

But HIVE has scenarios where external tables are created using hadoop_catalog, so I think at least this PR needs to be merged into HIVE.

All test cases can be viewed in the ICEBERG Community PR.

**Comment by ayushtkn** [comment]
> All test cases can be viewed in the ICEBERG Community PR. https://github.com/apache/iceberg/pull/10623/files#diff-5eae15702389a4a8e2eff932cd5567ac53d68941833556e52c688de77a03fa4e

there are test files for Iceberg in Hive code also, you can port this test in Hive, maybe in this directory:
https://github.com/apache/hive/tree/master/iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive

**Comment by BsoBird** [comment]
@ayushtkn 
Sir, I tried to port the test cases, but I found out that we are placing the iceberg patch in the patch directory, which has to be compiled for the patch to take effect, and it is not possible to test the patch separately.But this patch is very difficult to reproduce the bug directly from outside via SQL.

**Comment by deniskuzZ** [comment]
build failed with indentation checks - checkstyle stuff

as for tests, can't we also move them to patched modules as well?

**Comment by BsoBird** [comment]
> build failed with indentation checks - checkstyle stuff
> 
> as for tests, can't we also move them to patched modules as well?

Sir, it's difficult to test this class directly in the HIVE code because of the special compilation method we use to integrate the patch into HIVE.  But let me try. I'll also fix the checkstyle related problems.

**Comment by BsoBird** [comment]
@zhangbutao  @deniskuzZ @ayushtkn 
Sir. I submitted the relevant patch and ported the relevant test-case.

**Review by deniskuzZ — DISMISSED** [review]
LGTM +1, pending tests
let's wait for [HIVE-28421](https://issues.apache.org/jira/browse/HIVE-28421) to get the test run

**Comment by BsoBird** [comment]
@deniskuzZ 
Sir, when this PR is merged, can you retest [HIVE-28366](https://issues.apache.org/jira/browse/HIVE-28366) with hadoopcatalog?

**Comment by deniskuzZ** [comment]
@BsoBird, have you considered using HiveCatalog (backed by HMS) instead of HadoopCatalog? Wonder if there were some restrictions or specific use-cases.

**Comment by BsoBird** [comment]
> @BsoBird, have you considered using HiveCatalog (backed by HMS) instead of HadoopCatalog? Wonder if there were some restrictions or user specific use-cases.
@deniskuzZ 
Hi. We can't use HMScatalog to replace fsCatalog at the moment, because in our production environment, we are currently running multiple versions of HIVE/SPARK at the same time. HIVE3+SPARK serves some of the users, and HIVE4 serves some others. But they need to share the same ICEBERG data.So, we have to choose a lightweight catalog for sharing data between different computing engines.

**Comment by BsoBird** [comment]
@deniskuzZ 
I'm sure that other users have encountered problems similar to mine when upgrading to HIVE4. For example: Trino/spark/starRocks/impala and other third-party systems rely on a lower version of HIVE, but HIVE itself has the need to upgrade to version 4.X. This will result in multiple versions of HIVE coexisting. On this basis, the only way to share the same iceberg data is to choose a non-HMS-CATALOG implementation.  In order to reduce the complexity of the component stack, choosing hadoopCatalog is of course the first option to consider.

**Comment by deniskuzZ** [comment]
@BsoBird, thanks for the detailed explanation. Hive-3 & Hive-4 could have schema incompatibility

**Comment by simhadri-g** [comment]
[HIVE-28421](https://issues.apache.org/jira/browse/HIVE-28421) has been merged . 
I think we should rebase  to run the tests right?

**Comment by deniskuzZ** [comment]
tests passed, however, sonar reported number of issues that need to be resolved

**Comment by BsoBird** [comment]
done

**Comment by BsoBird** [comment]
@deniskuzZ 
Sir, if you have time, could you recheck this PR?Tks.

**Review by simhadri-g — APPROVED** [review]
LGTM

**Comment by BsoBird** [comment]
Tks!

**Pull request merged**
