### PR TITLE
HIVE-27030 : Upgrade HIVE to Hadoop 3.3.4

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-27030

### CODE REVIEW

**Comment by amanraj2520** [comment]
@abstractdog @ayushtkn @zabetak @kgyrtkirk Can you please review this.

**Review by ayushtkn — CHANGES_REQUESTED** [review]
Is it working with Tez, last time when we tried to move to 3.3.3, we moved back because of Tez.
It got me a green build though.
https://github.com/apache/hive/pull/3279#issuecomment-1141893046

**Comment by ayushtkn** [comment]
>  But in that case, we can ignore this commit in Hive 4.x release. We can still have this PR merged to Hive master I think.

This is not how things work, 4.x release is going to be from master branch, so why we will merge this. Secondly, a lot of developer develop on the master branch, we can't make the master '**knowingly**' unstable.

Secondly, This is dupe to #3578, and has a mention on the Tez ticket as well

**Comment by amanraj2520** [comment]
Got it Ayush. Will see if we can make a Tez release 0.10.3 first and then re-open this if required. Thanks for the review.

**Comment by amanraj2520** [comment]
Closing this for now. Will reopen if required. @zabetak @ayushtkn @abstractdog

**Pull request closed without merging**
