### PR TITLE
HIVE-27599: ConvertAstToSearchArg improvement with output and typo in comments

### PR DESCRIPTION
**Pull request by xuzifu666**
### What changes were proposed in this pull request?
improve output close automicly

### Why are the changes needed?
output need close automicly and some typo in comments

### Does this PR introduce _any_ user-facing change?
no

### Is the change a dependency upgrade?
no

### How was this patch tested?
can be used

### CODE REVIEW

**Comment by xuzifu666** [comment]
cc @ayushtkn have a review plz

**Comment by xuzifu666** [comment]
cc @dengzhhu653

**Comment by xuzifu666** [comment]
@ayushtkn could you have a review or this pr need to close?

**Review by ayushtkn — APPROVED** [review]
LGTM, will merge tommorrow if no further comments.

**Comment by xuzifu666** [comment]
> LGTM, will merge tomorrow if no further comments.

ok，thanks and ci had passed sucussfully @ayushtkn

**Pull request merged**
