### PR TITLE
HIVE-27757: Upgrade hadoop to 3.3.6.

### PR DESCRIPTION
**Pull request by ayushtkn**
### What changes were proposed in this pull request?

Upgrade Hadoop

### Why are the changes needed?

Better usablility

### Does this PR introduce _any_ user-facing change?

Nopes

### How was this patch tested?

Jenkins

### CODE REVIEW

**Review by SourabhBadhya — APPROVED** [review]
LGTM +1

**Comment by simhadri-g** [comment]
LGTM +1 (non-binding)

**Comment by amanraj2520** [comment]
Sorry for the late comment. Just a question @ayushtkn https://github.com/apache/hive/pull/4025 will this not be an issue here? That's why we had not upgraded to 3.3.4, right?

**Comment by ayushtkn** [comment]
We upgraded in Tez to 3.3.6 as well
https://github.com/apache/tez/commit/50380751b7e7e628aeb40a985b94aba98d2a88db

The master will release 4.0 GA, that will have the newer tez, we would be having a newer release from tez by EOY

**Comment by amanraj2520** [comment]
Thanks for the clarification Ayush

**Pull request merged**
