### PR TITLE
HIVE-28328:Hive Compilation Failed Due to License-Maven-Plugin URL Mismatch Error

### PR DESCRIPTION
**Pull request by basapuram-kumar**
### What changes were proposed in this pull request?
[HIVE-28328](https://issues.apache.org/jira/browse/HIVE-28328)
as per the above jira, hive compilation is failing on both master and branch-4.0 with the mentioned failures. This PR handles the failures.

### Why are the changes needed?
HIve compilation is failing with **branch-4.0** and **master** master too.

### Does this PR introduce _any_ user-facing change?
No

### Is the change a dependency upgrade?
No

### How was this patch tested?
compiled with the patch, it went well.

### CODE REVIEW

**Comment by Aggarwal-Raghav** [comment]
@basapuram-kumar, this is not failing for me, I tried with the same command present in the JIRA. Attaching the screenshot
Screenshot 2024-06-17 at 8 54 03 PM

I have seen license related error in my org artifactory but not in opensource.

**Comment by basapuram-kumar** [comment]
Hello @Aggarwal-Raghav,

Thank you for looking into this issue. The compilation error I'm encountering is related to the 'APACHE-2.0' license keys. This error occurs consistently across different machines I've tried.

The solution I provided addresses the issue by adding the Apache-2.0 license file URLs in the pom.xml. This change appears to resolve the problem. I don't see any failures related to our organization's Artifactory.

**Comment by deniskuzZ** [comment]
@basapuram-kumar, I can't repro it either

**Comment by ayushtkn** [comment]
not sure what you are doing here. if master build was broken all PRs build would be failing. Not sure about the Profiles you are putting in, half of them don't exist in hive.

try a simple
```
mvn clean install -DskipTests -Pdist
```
and see if it work, if it does, then there ain't any problem, I doubt the use of ``-pl :hive-packaging`` in your command as well, try without that

**Pull request closed without merging**
