### PR TITLE
HIVE-27209: Backport HIVE-24569 to branch-3: LLAP daemon leaks file descriptors/log4j appenders

### PR DESCRIPTION
**Pull request by guptanikhil007**
HIVE-24569: LLAP daemon leaks file descriptors/log4j appenders
Author: (Stamatis Zampetakis, reviewed by Jesus Camacho Rodriguez)

Closes apache/hive#1952

Cherry-picked from 53793a33dacf908b8d3779c88abd045299e78c9b

### What changes were proposed in this pull request?

Based on ee4e1f3c3bdf8e644143f8039cbda55d97710461
But modified to exclude tests that require JUnit5 and minor changes in the constructor of
LLapRandomAccessFileAppender to account for the differences in the versions log4j.version.

### Why are the changes needed?

This Backport was already done in branch-3.1 using this [HIVE-24569](https://issues.apache.org/jira/browse/HIVE-24569) so we need to backport the same to branch-3.

### CODE REVIEW

**Comment by amanraj2520** [comment]
+1 LGTM

**Comment by guptanikhil007** [comment]
@vihangk1 and @sankarh Can you review this?

**Comment by sankarh** [comment]
@guptanikhil007 Why test changes are not ported?

**Comment by guptanikhil007** [comment]
@sankarh This is ported from the original branch-3.1 cherry-pick not master.

**Comment by guptanikhil007** [comment]
https://github.com/apache/hive/pull/1952

**Review by sankarh — APPROVED** [review]

**Pull request merged**
