### PR TITLE
HIVE-23620: Moving to SpotBugs that is actively maintained

### PR DESCRIPTION
**Pull request by pgaref**
Change-Id: I54ca2e805732692784d64d7d05004e1866fcc815

### CODE REVIEW

**Comment by pgaref** [comment]
Thoughts here? @kgyrtkirk  @abstractdog

**Comment by kgyrtkirk** [comment]
cool!
perfectly makes sense to me; but let's wait when we don't use the ptest server anymore - this might affect it

**Comment by kgyrtkirk** [comment]
ptest is disabled, I think we can get this in; however I've just merged #1069...does this need any jenkinsfile changes?

**Comment by pgaref** [comment]
> ptest is disabled, I think we can get this in; however I've just merged #1069...does this need any jenkinsfile changes?

Hey @kgyrtkirk -- yes we will need to use spotbugs syntax instead in the precheck, let me update the PR and test.

In the meanwhile, I also added storage-api to the check list so https://issues.apache.org/jira/browse/HIVE-23617 that can be now pushed.

**Comment by pgaref** [comment]
> > ptest is disabled, I think we can get this in; however I've just merged #1069...does this need any jenkinsfile changes?
> 
> Hey @kgyrtkirk -- yes we will need to use spotbugs syntax instead in the precheck, let me update the PR and test.
> 
> In the meanwhile, I also added storage-api to the check list so #1063 can also be now pushed.

Updated

**Pull request merged**
