### PR TITLE
HIVE-26912: Publish SBOM artifacts

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to publish SBOM artifacts along with the other Apache projects.

- https://cwiki.apache.org/confluence/display/COMDEV/SBOM

Here is an article to give some context.
- https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/

Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).

This PR uses one of the Maven plugin, [CycloneDX maven plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin), a lightweight software bill of materials (SBOM) standard designed for use in application security contexts and supply chain component analysis.

https://maven.apache.org/plugins/index.html#misc

### Why are the changes needed?

This is helpful for the users who want to check the artifacts.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

`hive-common-4.0.0-SNAPSHOT.jar` will have `hive-common-4.0.0-SNAPSHOT-cyclonedx.xml` and `hive-common-4.0.0-SNAPSHOT-cyclonedx.json` files addtionally.
```
$ mvn install -pl common -DskipTests
...

$ ls -al /Users/dongjoon/.m2/repository/org/apache/hive/hive-common/4.0.0-SNAPSHOT/
total 2976
drwxr-xr-x  9 dongjoon  staff     288 Jan  9 00:52 .
drwxr-xr-x  4 dongjoon  staff     128 Jan  9 00:52 ..
-rw-r--r--  1 dongjoon  staff     332 Jan  9 00:52 _remote.repositories
-rw-r--r--  1 dongjoon  staff  394918 Jan  9 00:52 hive-common-4.0.0-SNAPSHOT-cyclonedx.json
-rw-r--r--  1 dongjoon  staff  348460 Jan  9 00:52 hive-common-4.0.0-SNAPSHOT-cyclonedx.xml
-rw-r--r--  1 dongjoon  staff  147479 Jan  9 00:52 hive-common-4.0.0-SNAPSHOT-tests.jar
-rw-r--r--  1 dongjoon  staff  594455 Jan  9 00:52 hive-common-4.0.0-SNAPSHOT.jar
-rw-r--r--  1 dongjoon  staff   13790 Jan  6 14:27 hive-common-4.0.0-SNAPSHOT.pom
-rw-r--r--  1 dongjoon  staff    1330 Jan  9 00:52 maven-metadata-local.xml
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @sunchao and @prasanthj ?

**Comment by prasanthj** [comment]
+1

**Review by prasanthj — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @prasanthj !

**Review by sunchao — APPROVED** [review]

**Comment by sunchao** [comment]
Merged, thanks @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sunchao and @prasanthj !

**Comment by ayushtkn** [comment]
Does this lead to printing some error messages while doing a maven build. I tried doing a maven install and there were bunch of such messages 
```
[INFO] ------------------------------------------------------------------------
[INFO] CycloneDX: Resolving Dependencies
[ERROR] An error occurred attempting to read POM
org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'project' (position: START_TAG seen ...</dependencies>\n    <project>... @35:14) 
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.checkUnknownElement (MavenXpp3Reader.java:178)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel (MavenXpp3Reader.java:2309)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read (MavenXpp3Reader.java:3872)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read (MavenXpp3Reader.java:595)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read (MavenXpp3Reader.java:609)
    at org.cyclonedx.maven.BaseCycloneDxMojo.readPom (BaseCycloneDxMojo.java:759)
    at org.cyclonedx.maven.BaseCycloneDxMojo.extractPom (BaseCycloneDxMojo.java:718)
    at org.cyclonedx.maven.BaseCycloneDxMojo.convert (BaseCycloneDxMojo.java:479)
    at org.cyclonedx.maven.CycloneDxMojo.execute (CycloneDxMojo.java:70)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
```

**Comment by dongjoon-hyun** [comment]
I didn't see that message when I ran `mvn install -DskipTests`. What is your command, @ayushtkn ?

**Comment by dongjoon-hyun** [comment]
Let me double-check the log, @ayushtkn .

**Comment by dongjoon-hyun** [comment]
Thank you, @ayushtkn . I confirmed that I missed `13` occurrences. 
```
$ mvn install -DskipTests > /tmp/log
$ grep XmlPullParserException /tmp/log | wc -l
      13
```

Although `CycloneDX` generates SBOM files, I'm investigating those 13 modules now to find the root cause.
```
[INFO] --- cyclonedx-maven-plugin:2.7.3:makeBom (default) @ hive-llap-server ---
[INFO] CycloneDX: Parameters
[INFO] ------------------------------------------------------------------------
[INFO] schemaVersion          : 1.4
[INFO] includeBomSerialNumber : true
[INFO] includeCompileScope    : true
[INFO] includeProvidedScope   : true
[INFO] includeRuntimeScope    : true
[INFO] includeTestScope       : false
[INFO] includeSystemScope     : true
[INFO] includeLicenseText     : false
[INFO] outputReactorProjects  : true
[INFO] outputFormat           : all
[INFO] outputName             : bom
[INFO] ------------------------------------------------------------------------
[INFO] CycloneDX: Resolving Dependencies
[ERROR] An error occurred attempting to read POM
org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'project' (position: START_TAG seen ...</dependencies>\n    <project>... @35:14)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.checkUnknownElement (MavenXpp3Reader.java:178)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel (MavenXpp3Reader.java:2309)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read (MavenXpp3Reader.java:3872)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read (MavenXpp3Reader.java:595)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read (MavenXpp3Reader.java:609)
    at org.cyclonedx.maven.BaseCycloneDxMojo.readPom (BaseCycloneDxMojo.java:759)
    at org.cyclonedx.maven.BaseCycloneDxMojo.extractPom (BaseCycloneDxMojo.java:718)
    at org.cyclonedx.maven.BaseCycloneDxMojo.convert (BaseCycloneDxMojo.java:479)
    at org.cyclonedx.maven.CycloneDxMojo.execute (CycloneDxMojo.java:70)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] CycloneDX: Creating BOM
[INFO] CycloneDX: Writing BOM (XML): /Users/dongjoon/APACHE/hive/llap-server/target/bom.xml
[INFO] CycloneDX: Validating BOM (XML): /Users/dongjoon/APACHE/hive/llap-server/target/bom.xml
[INFO] CycloneDX: Writing BOM (JSON): /Users/dongjoon/APACHE/hive/llap-server/target/bom.json
[INFO] CycloneDX: Validating BOM (JSON): /Users/dongjoon/APACHE/hive/llap-server/target/bom.json
[INFO]
[INFO] --- maven-jar-plugin:3.2.0:test-jar (default) @ hive-llap-server ---
[INFO] Building jar: /Users/dongjoon/APACHE/hive/llap-server/target/hive-llap-server-4.0.0-SNAPSHOT-tests.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ hive-llap-server ---
[INFO] Installing /Users/dongjoon/APACHE/hive/llap-server/target/hive-llap-server-4.0.0-SNAPSHOT.jar to /Users/dongjoon/.m2/repository/org/apache/hive/hive-llap-server/4.0.0-SNAPSHOT/hive-llap-server-4.0.0-SNAPSHOT.jar
[INFO] Installing /Users/dongjoon/APACHE/hive/llap-server/pom.xml to /Users/dongjoon/.m2/repository/org/apache/hive/hive-llap-server/4.0.0-SNAPSHOT/hive-llap-server-4.0.0-SNAPSHOT.pom
[INFO] Installing /Users/dongjoon/APACHE/hive/llap-server/target/bom.xml to /Users/dongjoon/.m2/repository/org/apache/hive/hive-llap-server/4.0.0-SNAPSHOT/hive-llap-server-4.0.0-SNAPSHOT-cyclonedx.xml
[INFO] Installing /Users/dongjoon/APACHE/hive/llap-server/target/bom.json to /Users/dongjoon/.m2/repository/org/apache/hive/hive-llap-server/4.0.0-SNAPSHOT/hive-llap-server-4.0.0-SNAPSHOT-cyclonedx.json
[INFO] Installing /Users/dongjoon/APACHE/hive/llap-server/target/hive-llap-server-4.0.0-SNAPSHOT-tests.jar to /Users/dongjoon/.m2/repository/org/apache/hive/hive-llap-server/4.0.0-SNAPSHOT/hive-llap-server-4.0.0-SNAPSHOT-tests.jar
```

Here is the list of modules.
- hive-llap-server
- hive-llap-ext-client
- hive-service
- hive-accumulo-handler
- hive-jdbc
- hive-cli
- hive-hbase-handler
- hive-hcatalog-core
- hive-hcatalog-pig-adapter
- hive-hcatalog-server-extensions
- hive-webhcat-java-client
- hive-webhcat
- hive-packaging

Sorry for this trouble. I'll ping you guys once more, @ayushtkn , @sunchao , @prasanthj .

**Comment by dongjoon-hyun** [comment]
The root cause is one of the transitive dependencies of `hbase-server` and `hbase-mapreduce`.
- https://github.com/apache/hive/blob/25c78a0d392ede731bfb5ecd7b2159be4887f182/llap-server/pom.xml#L412-L445

**Comment by dongjoon-hyun** [comment]
Here is the root cause. `jamon-runtime`'s pom file is invalid because it has nested `project` tag. Given that, I'll exclude it from Hbase dependency to fix the warning issue.
- https://repo1.maven.org/maven2/org/jamon/jamon-runtime/2.3.1/jamon-runtime-2.3.1.pom

**Comment by dongjoon-hyun** [comment]
I made a PR to fix the issue.
- #3932

**Pull request merged**
