### PR TITLE
HIVE-27540 : Fixed orc_merge10.q test

### PR DESCRIPTION
**Pull request by amanraj2520**

### CODE REVIEW

**Comment by amanraj2520** [comment]
@sankarh Can you please review this

**Review by ayushtkn — COMMENTED** [review]
The output is changing, how is the test flaky? it should be failing itself if the output is different, right?

**Comment by amanraj2520** [comment]
Hi @ayushtkn You are correct. I was going to change the title. This not not a flaky test at all.

**Comment by amanraj2520** [comment]
All the PRs in branch-3 were committed after the build was green. No test was skipped and if the pr was red, we did not allow to commit. Not sure why this test started failing in branch-3. Any suggestion @ayushtkn

**Review by sankarh — APPROVED** [review]

**Comment by ayushtkn** [comment]
Thanx Aman for the details, couldn’t check further, Please proceed, don’t hold for me

**Comment by amanraj2520** [comment]
Thanks Ayush. @sankarh Can we please merge this.

**Pull request merged**
