### PR TITLE
HIVE-27508 : Backport of HIVE-21584 to branch-3.1

### PR DESCRIPTION
**Pull request by amanraj2520**

### CODE REVIEW

**Comment by vihangk1** [comment]
Took a quick look and compared with the original PR for HIVE-21584. I am not sure of the state of tests in branch-3.1 but based on `There are 0 new tests failing, 51 existing` it looks like none of them are new failures.

**Comment by amanraj2520** [comment]
@vihangk1 These tests were failing in branch-3.1 since the beginning. No work was put into this. The correctness of this PR will be determined by tests passing in branch-3

**Review by vihangk1 — APPROVED** [review]
LGTM

**Comment by vihangk1** [comment]
merged into branch-3.1

**Pull request merged**
