### PR TITLE
HIVE-27532: Missing semicolon in show create table output

### PR DESCRIPTION
**Pull request by soumyakanti3578**
### What changes were proposed in this pull request?

`SHOW CREATE TABLE` doesn't add a `;` in the `CREATE` output. This patch corrects the behaviour.

### Why are the changes needed?

Without this change, `SHOW CREATE TABLE` output is incorrect.

### Does this PR introduce _any_ user-facing change?

Yes, this is technically a user facing change as the show create table output has changed with the addition of the semicolon.

### Is the change a dependency upgrade?

No

### How was this patch tested?

`mvn test -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite=true -Dqfile=show_create_table.q`

### CODE REVIEW

**Review by ayushtkn — COMMENTED** [review]
Is this a regression? Which version of hive used to have a ; and can you link the ticket which broke this behaviour.

I think show create database also doesn't have a ;.

**Comment by soumyakanti3578** [comment]
Hey @ayushtkn,
Now that `SHOW CREATE TABLE` outputs multiple statements for `CREATE` and `ALTER`s, we need a semicolon at the end of the `CREATE` statement.

**Comment by jfsii** [comment]
> Hey @ayushtkn,
> Now that `SHOW CREATE TABLE` outputs multiple statements for `CREATE` and `ALTER`s, we need a semicolon at the end of the `CREATE` statement.

I agree we should add the ; since it outputs multiple statements sometimes to facilitate copy/paste/execute a bit better.
If SHOW CREATE DATABASE doesn't add the ; , I'm inclined to suggest you add it just for consistency between the statements.

**Comment by soumyakanti3578** [comment]
@jfsii @ayushtkn 
Currently `SHOW CREATE DATABASE` doesn't add a `;`, however, `EXPLAIN DDL SELECT * FROM TABLE` does, as can be seen [here](https://github.com/apache/hive/blob/master/ql/src/test/results/clientpositive/llap/partition_explain_ddl.q.out#L402).

So, for consistency, I will add a semi colon [here](https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/ddl/database/showcreate/ShowCreateDatabaseOperation.java#L72).

I am also planning to move the closing paren and semicolon `);` to a new line. This will prevent them from getting masked and can then be picked up if q.out files change.

**Comment by ayushtkn** [comment]
any pointers how does impala behaves? In general CLI level changes are considered incompatible changes, & I think this is there since legacy time & not a regression
; is not part of the query but used to terminate a query in beeline, if someone is doing driver.execute or using java application to submit a query I don't think he would require a ;

**Comment by soumyakanti3578** [comment]
From my experiments, it looks like in Impala `SHOW CREATE TABLE` includes the constraints with the columns, not as `ALTER TABLE` statements, which is the case in Hive.

I agree with your points that `;` has not been there since the beginning, however, currently if you do a `SHOW CREATE TABLE`, you get a CREATE statement with no `;`, and then you can get a bunch of ALTERs with semicolons ([example](https://github.com/apache/hive/blob/master/ql/src/test/results/clientpositive/llap/show_create_table.q.out#L114)). `Explain DDL`s also work similarly ([example](https://github.com/apache/hive/blob/master/ql/src/test/results/clientpositive/llap/constraints_explain_ddl.q.out#L102)).

I think we should keep these consistent, either all statements should have semi colons or none of them. Having semicolons in all of them helps with copying and pasting.

**Comment by soumyakanti3578** [comment]
We could also add the `;` only when there is at least one `ALTER` after the `CREATE`.
Currently for `SHOW CREATE TABLE`, we either get this:
> create table test(...)...tblproperties(...)

or this:

> create table test(...)...tblproperties(...)
> alter table....;
> alter table....;
> alter table....;

But we can add the `;` in all but the last statement, so we'd either get this:
> create table test(...)...tblproperties(...)

or this:

> create table test(...)...tblproperties(...);
> alter table....;
> alter table....;
> alter table....

@ayushtkn @jfsii @zabetak @kasakrisz @scarlin-cloudera What do you all think?

**Comment by scarlin-cloudera** [comment]
I think leaving the semi-colon off of the last query statement is a good compromise between keeping backward compatibility and fixing this issue.

Most people probably don't use constraints and therefore only have the one statement when they do a "show create table".   So they wouldn't have any regression from their current way of doing things.

If they did have constraints, I doubt they were parsing all the statements to insert the missing semi-colon after the create table.  If they did, they should have reported it as a bug instead of hacking around it.  So I think leaving a semi-colon off of the last "alter add constraint" statement works while adding the semi-colon after the "create table"

**Comment by jfsii** [comment]
I think putting the semicolon everywhere is the best decision. I think the concerns about backwards compatibility are a bit overblown. If someone somewhere is taking SHOW CREATE output and passing it to driver directly I would be surprised (though I've been surprised before). As for not adding it to just the last line output, that seems to me to needlessly complicate this in the interest of compromise with no real up side. The other option I could possibly buy-in to is no semicolons everywhere, but I think I'd rather optimize for the copy paste pattern then what I would guess is the less likely passing directly to a driver use case (I do think some other systems - do not put the semi colons but they also do not emit multiple SQL statements in the output). Either way in the end it should be consistent.

**Comment by ayushtkn** [comment]
I think we should only put ; in case there are multiple statements only, and maintain compat with the normal create statement. Considering nobody has use case for such a old behaviour is like "only we use the product" and we are ok with it and this is against the spirit of opensource

**Comment by jfsii** [comment]
@ayushtkn 

I feel like this a bit of a bike shedding argument at this point. I think everyones opinions on this topic is valid in one way or another and will back the consensus view. I think @zabetak's opinion here would be good (and may be different than my opinion) and a nice tie breaker.

> Considering nobody has use case for such a old behaviour is like "only we use the product" and we are ok with it and this is against the spirit of opensource.
I did not mean to suggest anything remotely what you imply with this statement. I just stated that I feel the concerns about backwards compatibility in this specific area are likely overblown in my opinion. I can not see how my statement and participation in this discussion would be considered against the "spirit of open-source" - if anything I would consider it an example of the spirit of open source.

When are we allowed to break compatibility? We are in the middle of a release push for 4.0.0. I would think breaking compatibility for something like this, now would be a good time. Anything we do that is not a new feature changes behavior/compatibility and you could use the same argument against any change (Though I do tend to agree in general, that needlessly changing things that break compatibility is undesirable).

I think consistency is important - otherwise you have to handle both cases as an end user. My vote is either to always have the semi-colons or never have them. I lean towards having them, but I can see the other way as a good choice too (not having them at all).

**Comment by ayushtkn** [comment]
I gave a quick shot on **Impala** and it doesn't have a semi-colon either
image

Atleast for the normal show create table command & so does hive as of today for normal show create table

I checked Spark's official documentation
https://spark.apache.org/docs/3.0.0-preview/sql-ref-syntax-aux-show-create-table.html

It doesn't have a semi-colon either
image

Tried on **Spark Shell**:
spark-show


Checked **MySql** doc as well:
https://dev.mysql.com/doc/refman/8.0/en/show-create-table.html
image


Maybe I am checking the wrong pages or did something wrong while trying these commands. I have limited to NIL experience in these technologies...

But in general also CLI output irrespective of other engines should be maintained, these aren't my thoughts. This is actually documented in the Hadoop Compat guidelines, which Hive was a part

image

And it is not just for the sake of writing, these compat rules are indeed followed even for minor and things which are considered to be good. My intentions aren't to use compat guidelines to stop anyone from doing anything or impose to folks what just I believe. I can quote an example where I was a participant as well for a cli change which is indeed good for users and quite trivial as well and it got reverted, though it looked good, just for the sake of compat
https://issues.apache.org/jira/browse/HDFS-13732?focusedCommentId=16685728&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16685728

> When are we allowed to break compatibility? 

The answer is Never, we aren't allowed to break compatibility, we break it only incase of unavoidable circumstances following a certain pattern, like deprecating and stuff like that, that also can be surpassed in case of security issues and things like that. This is what my limited experience in the ecosystem says.

But if people feel it is a good thing & we should go with it, I won't block it, upto you folks!!! 
-0

**Comment by jfsii** [comment]
Re: @ayushtkn I think my response earlier may have been too strong (maybe I woke up grumpy). Your points are valid and fair, as are mine. They should be considered which is why I would like a 3rd opinion.

> Research about other systems.

We had also done this research. The point in prior comments is that other systems do not output multiple lines.

> Maybe I am checking the wrong pages or did something wrong while trying these commands.

No, you are not wrong here. 

> This is actually documented in the Hadoop Compat guidelines, which Hive was a part

Thank you for sharing this document. I would consider Hive and Hadoop/Hdfs different projects with different guidelines, policies and goals. (However, I am not a committer here and I may not be familiar with how these policies are applied to Hive). I agree with what I think the intent of this guideline is - which is to not break consumers of the CLI in which automation is built around or other consumers use. I'd argue that this shouldn't be a "must" for Hive SQL statement output (maybe for beeline output and options) - but we ALSO should take care not to change things that complicate the lives of the users of Hive.

> The answer is Never, we aren't allowed to break compatibility, we break it only incase of unavoidable circumstances following a certain pattern, like deprecating and stuff like that, that also can be surpassed in case of security issues and things like that. This is what my limited experience in the ecosystem says.

I think this is an unreasonable viewpoint. I think there should be point in time in which backwards compatibility should be able to broken in order to move the project forward and/or to remove features that no longer make sense. However - on the other hand I think there are areas where Hive should get better at this and it is important to call them out for discussion (like you are doing here).

Again, we can find consensus here and move forward. I prefer consistency all ;'s or no ;'s - but I can also live with your suggestion of single line having none and multi-statement having ;'s.

**Comment by jfsii** [comment]
Actually - thinking about it and talking with @scarlin-cloudera a bit and re-reading what @ayushtkn wrote.
I can get behind:
> I think we should only put ; in case there are multiple statements only, and maintain compat with the normal create statement.

I think I'd prefer if it were everywhere, but I think the above is also a good solution. Having it nowhere only really works if SHOW CREATE TABLE outputs multiple rows with one statement per line (I think it outputs it as row containing all statements).

**Comment by ayushtkn** [comment]
Exploring a bit more
FWIW. Semi colon is the default delimiter not the only delimiter beeline can have,
Launch your beeline session like
```
beeline -u 'jdbc:hive2://localhost:10000/' --delimiter='$'
```
And now this will use $ to terminate the queries rather than ;
So, having those ; doesn't make sense, when the delimiter changes to something else, so the problem is not around semicolon but delimiter.

Secondly, 
> We had also done this research. The point in prior comments is that other systems do not output multiple lines.

 [HIVE-25652](https://issues.apache.org/jira/browse/HIVE-25652) added these alter statements where as other systems don't add these lines, I feel we went wrong there itself, checking the example mentioned in that ticket, We created a table using a **single** create statement, & in the show create table output for the same create we show a different skeleton create statement & bunch of alter to reach the state which that 'single' create statement led to, and as the research says other system don't operate that way but return the same create statement which was used to create the table.

I think we should also get rid of these alters & operate the way other engines operate and I feel that is the correct way.

**Comment by jfsii** [comment]
@ayushtkn Fair points. Though I am not strictly of the mind that we must match other systems in this area since there isn’t a defined standard for these statements. However, it does solve all the edge cases that we have been debating.

How hard is it to roll these into the create statement? @soumyakanti3578 
Do we support these types of statements?

**Comment by scarlin-cloudera** [comment]
@ayushtkn 

If it turns out it is hard to put it all in one statement, it's probably not going to get done anytime soon.  I believe this is the case.

In that case, we have two choices:

1) Abandon the patch and do nothing.  In which case, we have a status quo of semi-colons on the alter statement but none on the first statement.  That's a little yucky and heinous in my opinion since that causes a headache on a cut and paste of the show command.  
2) Put no semi-colon if there is only one statement and all semi-colons on all statements.  This is something you sorta agreed to before and, imo, is definitely better than 1)

**Pull request closed without merging**
