### PR TITLE
HIVE-26896 : Test fixes for lineage3.q and load_static_ptn_into_bucketed_table.q

### PR DESCRIPTION
**Pull request by amanraj2520**
These tests were fixed in branch-3.1 as part of Hive 3.1.3 release therefore backporting the same in branch-3. Commit ID : 9fef6b4c

### CODE REVIEW

**Review by cnauroth — COMMENTED** [review]
Hello @amanraj2520 . The JIRA issue mentions that this is a backport. For reference, could you please link to the original JIRA issue/commit that contained the fix? Thanks!

**Comment by amanraj2520** [comment]
Hi @cnauroth @abstractdog @zabetak This fix went int branch-3.1 without any JIRA created. If you search "Test fixes for lineage3.q and load_static_ptn_into_bucketed_table.q" on branch-3.1 commits. You will find this commit. Attaching the commit id : 9fef6b4c FYI. Do I need to do anything else? If not can we merge this PR.

**Review by zabetak — CHANGES_REQUESTED** [review]
The `lineage3` test does not seem to run on branch-3 so the summary and changes are bit misleading.
```
$ wget -qnv http://ci.hive.apache.org/job/hive-precommit/job/branch-3/12/testReport/api/json -O - | jq '.suites[].cases[] | {className, name, status} | select(.name | match("lineage","load_static"))'
{
  "className": "org.apache.hadoop.hive.cli.split7.TestCliDriver",
  "name": "testCliDriver[lineage1]",
  "status": "PASSED"
}
{
  "className": "org.apache.hadoop.hive.cli.split7.TestCliDriver",
  "name": "testCliDriver[load_static_ptn_into_bucketed_table]",
  "status": "FAILED"
}
```
Please update JIRA and PR accordingly.

**Comment by amanraj2520** [comment]
@zabetak lineage3 would run after this https://github.com/apache/hive/pull/3859 is merged. I had checked it in a sample branch after merging this change.

**Comment by zabetak** [comment]
@amanraj2520 OK then we should wait for #3859 to get in before merging this change.

**Comment by amanraj2520** [comment]
@zabetak Yes we can wait. I have no issue in that. In fact its better that way. But since this change went in branch-3.1 from where Hive-3.1.3 was cut (also in Hive-3.1.3 this commit is present), I was thinking that we can merge this.

**Comment by amanraj2520** [comment]
Hi @zabetak Can you please review and merge this. http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3929/2/tests You can find the failing tests in the latest branch-3 PR run

**Comment by amanraj2520** [comment]
@zabtek can you please approve this and merge.

**Comment by zabetak** [comment]
Hey @amanraj2520, I will merge this once I see that the two tests mentioned here are:
# failing on the last precommit run in branch-3 
# not failing on the last precommit run in this PR.

`lineage3` seems to pass here http://ci.hive.apache.org/job/hive-precommit/job/branch-3/15

**Comment by amanraj2520** [comment]
@zabetak I cannot find any test case where lineage3 failed. I will revert the lineage3 fix and rename this PR.

**Comment by amanraj2520** [comment]
@zabetak Modified it. Kindly review this.

**Pull request closed without merging**
