### PR TITLE
HIVE-28304: Replace org.apache.log4j.Logger with org.slf4j.Logger

### PR DESCRIPTION
**Pull request by ngsg**
### What changes were proposed in this pull request?

 Replace org.apache.log4j.Logger with org.slf4j.Logger.

### Why are the changes needed?

Logger should be created via facade(SLF4J), but some classes still directly access to Logger implementation. This patch fixes this issue.

### Does this PR introduce _any_ user-facing change?

No
### Is the change a dependency upgrade?

No

### How was this patch tested?

This patch was not tested as it just changes logger instantiation code.

### CODE REVIEW

**Review by okumin — APPROVED** [review]

**Review by zhangbutao — COMMENTED** [review]
Are there other places where `org.apache.log4j.Logger` is being used?
If not, can we remove the `log4j-1.2-api ` dependency?  For example, I see that hive install package has the jar `log4j-1.2-api-2.18.0.jar`.

**Comment by ngsg** [comment]
@zhangbutao, there is no `org.apache.log4j.Logger` import in Hive project.
Let me test Hive if we could remove `log4j-1.2-api` dependency or not.

**Comment by ngsg** [comment]
I tried compiling Hive without `log4j-1.2-api`, but the compilation failed as some code still rely on it. So we can not remove `log4j-1.2-api` dependency as of now.

maven failure message:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project hive-common: Compilation failure
[ERROR] /data2/hive-lngsg/common/src/java/org/apache/hadoop/hive/common/JvmMetrics.java:[185,20] cannot access org.apache.log4j.AppenderSkeleton
[ERROR]   class file for org.apache.log4j.AppenderSkeleton not found
```

**Review by zhangbutao — APPROVED** [review]
LGTM +1

**Comment by zhangbutao** [comment]
@okumin Sorry for forgetting add your name into the commit message. :(

**Pull request merged**
