### PR TITLE
HIVE-24248: TestMiniLlapLocalCliDriver[subquery_join_rewrite] is flaky

### PR DESCRIPTION
**Pull request by dengzhhu653**

### CODE REVIEW

**Comment by kgyrtkirk** [comment]
@kasakrisz could you please take a look? I think we have the same resultset in a different order...
so SORT_QUERY_RESULTS should have ignored this difference

**Comment by kasakrisz** [comment]
I run this test locally using current master and got the same result like in this PR.
Let's wait for flaky test run results.

**Comment by dengzhhu653** [comment]
@kasakrisz @kgyrtkirk The flaky test runs successfully:
http://ci.hive.apache.org/job/hive-flaky-check/126/

**Review by kasakrisz — APPROVED** [review]

**Comment by dengzhhu653** [comment]
Reopen it to check the failed xml reading.

**Comment by kgyrtkirk** [comment]
test seems to be stable
http://ci.hive.apache.org/job/hive-flaky-check/131/

**Pull request merged**
