### PR TITLE
HIVE-23485: Bound GroupByOperator stats using largest NDV among columns

### PR DESCRIPTION
**Pull request by zabetak**
### What changes were proposed in this pull request?
Update estimations for group by operator to take into account the largest NDV among the columns participating in the aggregation.

### Why are the changes needed?
Improve accuracy of statistics.

### Does this PR introduce _any_ user-facing change?
May result in plan changes.

### How was this patch tested?
```
mvn -pl itests/qtest -Pqsplits -Pitests test -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite
mvn -pl itests/qtest -Pqsplits -Pitests test -Dtest=TestTezTPCDS30TBPerfCliDriver -Dtest.output.overwrite

```

### CODE REVIEW

**Review by kgyrtkirk — COMMENTED** [review]
I've not seen any changes beyond rowNum diffs in the q.outs

**Comment by zabetak** [comment]
> I've not seen any changes beyond rowNum diffs in the q.outs

So far I haven't seen major differences either: `rowNums` and as expected `minReductionHashAggr`.

**Review by kgyrtkirk — APPROVED** [review]

**Comment by zabetak** [comment]
Hey @kgyrtkirk , tests are green so it would be nice to get this in before conflicts start to emerge again :)

**Comment by kgyrtkirk** [comment]
yeah; I also tried to not forgot it :D
I hope the changes are still good :)

**Pull request merged**
