### PR TITLE
HIVE-27089 : Test fixes for orc_merge*.q

### PR DESCRIPTION
**Pull request by amanraj2520**
JIRA link : https://issues.apache.org/jira/browse/HIVE-27089

### CODE REVIEW

**Comment by amanraj2520** [comment]
@zabetak @abstractdog Can you please approve and merge this. All other failures are intermittent or existing issues.

**Comment by zabetak** [comment]
@amanraj2520 Thanks for the patch. Any ideas which commit broke these tests? Can you link the respective JIRA tickets?

**Comment by amanraj2520** [comment]
@zabetak I think it is either of this PR - https://github.com/apache/hive/pull/4046 or https://github.com/apache/hive/pull/4014.

**Comment by amanraj2520** [comment]
@zabetak @abstractdog Please ignore my above message. I found the commit that caused this failure. I have reverted that commit and tested it. This is the commit that brought the failure - HIVE-27016 . Pull request - https://github.com/apache/hive/pull/4013. On reverting I can see -rw getting replaced by -r--
image

This has run in my local so its USER is different.
@sunchao @yigress Is the fix I did an expected behaviour as a result of this commit or does there need to be a change in this https://github.com/apache/hive/pull/4013

**Comment by yigress** [comment]
@zabetak @amanraj2520 I wonder if we should continue with this fix, rather than revert HIVE-27016? The reason is that I see in branch-4 the permissions were changed as proposed here in HIVE-22589, but it is not apparent to me that HIVE-22589 itself causes the permission changes, so it looks like the orc_merge* tests permissions should have been updated. 

I agree that stabilizing the tests is the first priority in branch-3 right now. Our users looking forward to the next branch-3 release as branch-4 seems a bit too far, this feature is very important for users who are staying on branch-3 with storagehandlers.  We will watch branch-3 progress and not making addons until tests are stabilized.

**Comment by amanraj2520** [comment]
@zabetak @abstractdog Can you please review and merge this PR.

**Comment by amanraj2520** [comment]
Thanks @yigress for the comments

**Comment by amanraj2520** [comment]
@zabetak @abstractdog Can you please review and merge this

**Review by zabetak — CHANGES_REQUESTED** [review]
> I wonder if we should continue with this fix, rather than revert [HIVE-27016](https://issues.apache.org/jira/browse/HIVE-27016)? The reason is that I see in branch-4 the permissions were changed as proposed here in [HIVE-22589](https://issues.apache.org/jira/browse/HIVE-22589), but it is not apparent to me that [HIVE-22589](https://issues.apache.org/jira/browse/HIVE-22589) itself causes the permission changes, so it looks like the orc_merge* tests permissions should have been updated.

I checked branch-4 and the permissions did not change as part of HIVE-22589; they changed after HIVE-21305.

I am not insisting on reverting HIVE-27016 but in order for this fix to get in somebody needs to explain why it is OK to update the orc_merge files:
* Why HIVE-27016 is causing these changes?
* Why is it OK to have different permissions when creating ORC directories?

**Comment by amanraj2520** [comment]
@zabetak Not sure about the reason. But will investigate. @yigress @sunchao Can you please check this

**Comment by yigress** [comment]
Thank you @zabetak for pointing to the correct HIVE-21305 that changed permissions for the test files. HIVE-21305 suggests that with IO cache and without IO cache the file permissions will be different, so that gives the impression that in LLAP the permissions is not really an issue?  
I tested this with non-LLAP hive, there is no permissions change before or after HIVE-27016. As HIVE-27016 invokes Outputcommitter on Tez-AM, so my guess is that in LLAP it causes file write (in these orc file tests) with the changed permissions, however in non-LLAP this only affects storagehandler type tables so the output permissions for orc tables remain unchanged. 

This calls for difference of outputs file permissions in LLAP and non-LLAP, wonder has this been discussed before?

**Comment by amanraj2520** [comment]
@zabetak Can you suggest what according to you is the right approach to fix this?

**Comment by amanraj2520** [comment]
@zabetak Can you please suggest what should be done for these test fixes

**Comment by yigress** [comment]
@zabetak this seems to be file permission differences in llap and non-llap setup. If you think it better to revert HIVE-27016 first to unblock tests, I am fine with it.

**Comment by zabetak** [comment]
@yigress I am not sure if it is LLAP related. If you check the `orc_merge1.q` file there are three `dfs -ls` operations always following an `INSERT OVERWRITE TABLE` query. I assume that the `OVERWRITE` query rewrites the directory every time. 

Before HIVE-27016:
```
INSERT OVERWRITE TABLE
dfs -ls
-rw-r--r--
INSERT OVERWRITE TABLE
dfs -ls
-rw-rw-rw-
INSERT OVERWRITE TABLE
dfs -ls
-rw-rw-rw-
```

After HIVE-27016:
```
INSERT OVERWRITE TABLE
dfs -ls
-rw-rw-rw-
INSERT OVERWRITE TABLE
dfs -ls
-rw-rw-rw-
INSERT OVERWRITE TABLE
dfs -ls
-rw-rw-rw-
```
Worth mentioning that even before HIVE-27016 we have directories created with `-rw-rw-rw-` just not the first time.

There must be a code-path that operates with different permissions and this is definitely a bug. If someone can pinpoint the exact reason of why this happens and raise a JIRA that would be great.

However, given that permission differences existed even before HIVE-27016, I will not consider HIVE-27016 as a regression so I am OK to simply update the .q.out files for the moment.

**Review by zabetak — APPROVED** [review]

**Comment by yigress** [comment]
@zabetak thank you for taking time detailed analysis!

**Pull request closed without merging**
