### PR TITLE
HIVE-25544: Remove Dependency of hive-meta-common From hive-common

### PR DESCRIPTION
**Pull request by belugabehr**

### CODE REVIEW

**Review by kgyrtkirk — CHANGES_REQUESTED** [review]

**Comment by belugabehr** [comment]
CI is timing out,.. trying again,...

**Comment by belugabehr** [comment]
```
[2021-09-27T17:32:45.684Z] Digest: sha256:90c1ddddb38152f7260014bc4d3d10209cebbd5e25346cea07b00efd8e36028e
[2021-09-27T17:32:46.263Z] Status: Downloaded newer image for postgres:latest
[2021-09-27T17:33:54.106Z] 206c95085bbcf9b468aadcca8986b306fb2d1c16927ecd296cda321a1fb7584a
[2021-09-27T17:33:54.106Z] waiting for postgres to be available...
[2021-09-27T17:39:00.975Z] timeout reached before the port went into state "inuse"
script returned exit code 1
```

Hmmm

**Comment by kgyrtkirk** [comment]
```
[2021-09-27T17:39:00.975Z] timeout reached before the port went into state "inuse"
script returned exit code 1
```
the above is fixed now - but we have some failing tests....

**Comment by belugabehr** [comment]
@kgyrtkirk Thanks for the feedback. 

FYI.  I am not ignoring your previous comments about de-duplication.  I just am trying to get this to run first and then I can work backwards and optimize the solution. :)

**Pull request closed without merging**
