### PR TITLE
HIVE-26620: Remove unused imports for ThriftBinaryCLIService class

### PR DESCRIPTION
**Pull request by xiuzhu9527**
### What changes were proposed in this pull request?

Remove unused imports for org.apache.hive.service.cli.thrift.ThriftBinaryCLIService class

### Why are the changes needed?

Remove unused imports for org.apache.hive.service.cli.thrift.ThriftBinaryCLIService class

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No.

### CODE REVIEW

**Comment by xiuzhu9527** [comment]
@ayushtkn Can you help review this pr? Thank you very much!

**Review by ayushtkn — COMMENTED** [review]
You need to create a Jira for this and add the jira id in the PR title

**Comment by xiuzhu9527** [comment]
@ayushtkn  Thank you very much for your reply，I created a jira for this PR

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by xiuzhu9527** [comment]
Thanks, @ayushtkn

**Pull request merged**
